import type { Locale } from "./locale";

export type AppTab = "explorar" | "capsulas" | "viaje" | "mesa" | "cuenta";

const es = {
  appName: "Mapucoin",
  location: "Chile",
  openMarketing: "Sitio",
  tabs: {
    explorar: "Explorar",
    capsulas: "Cápsulas",
    viaje: "Viaje",
    mesa: "Mesa",
    cuenta: "Cuenta",
  },
  explorarLead:
    "Chile por paisaje. Toca un destino o una cápsula en el mapa. Lo más cercano a ti primero.",
  searchPlaces: "Buscar destino o cápsula…",
  nearby: "Cerca de ti",
  locating: "Buscando tu ubicación…",
  useLocation: "Usar mi ubicación",
  locationDenied: "Activa la ubicación para ordenar por distancia.",
  planThis: "Planificar este destino",
  seeCapsule: "Ver cápsula",
  from: "desde",
  away: "de distancia",
  all: "Todos",
  capsulasLead:
    "Una casa cápsula por paisaje — cobre, vidrio y madera — operada por partners locales. Reserva con Stripe.",
  book: "Reservar",
  booking: "Reservando…",
  bookThis: "Reservar esta cápsula",
  perNight: "por noche",
  nights: "Noches",
  guests: "Viajeros",
  payStripe: "Pagar con Stripe",
  noStripe: "Stripe no está configurado en este servidor.",
  bookNeedProfile: "Completa nombre y correo en Cuenta para reservar.",
  bookFail: "No se pudo iniciar el pago.",
  viajeLead:
    "Elige paisaje y presupuesto. Mapucoin arma cápsula, mesa y actividades, y Grok responde.",
  paidBanner: "Pago recibido. Te escribimos con el check-in de la cápsula.",
  mesaLead:
    "La mesa del territorio y lo que se hace ahí: astronomía, surf, cata, trekking, kayak, ski.",
  food: "Gastronomía",
  activities: "Actividades",
  account: {
    lead: "Tu ficha de viajero. Reservas, datos de contacto y rol en Mapucoin.",
    name: "Nombre",
    email: "Correo",
    phone: "Teléfono",
    city: "Ciudad",
    instagram: "Instagram",
    role: "Rol",
    save: "Guardar",
    saving: "Guardando…",
    saved: "Perfil guardado.",
    saveError: "No se pudo guardar.",
    logout: "Salir",
    bookings: "Tus reservas",
    noBookings: "Aún no hay reservas. Elige una cápsula y paga con Stripe.",
    partnerCta: "Ingresar como partner",
    partnerLead: "Operas una cápsula, una mesa o un tour. Postula desde aquí.",
    roles: {
      traveler: "Viajero",
      partner: "Partner",
    },
    nameError: "Escribe tu nombre.",
    emailError: "Correo inválido.",
    instagramError: "Instagram inválido.",
  },
  sessionNeeded: "Entra para abrir la App Mapucoin.",
  loginTitle: "Entrar",
  signupTitle: "Crear cuenta",
  loginCta: "Entrar",
  signupCta: "Crear cuenta",
  password: "Contraseña",
  passwordConfirm: "Confirmar contraseña",
  orContinue: "o continúa con correo",
  googleCta: "Continuar con Google",
  googleUnconfigured: "Google no está configurado en este servidor.",
  googleDenied: "Cancelaste el acceso con Google.",
  googleError: "No se pudo entrar con Google.",
  needAccount: "¿No tienes cuenta? Crear una",
  haveAccount: "¿Ya tienes cuenta? Entrar",
  loginError: "Correo o contraseña incorrectos.",
  signupError: "No se pudo crear la cuenta.",
  nameRequired: "Escribe tu nombre.",
  passwordShort: "La contraseña debe tener al menos 8 caracteres.",
  passwordMismatch: "Las contraseñas no coinciden.",
  sending: "Enviando…",
};

const en: typeof es = {
  appName: "Mapucoin",
  location: "Chile",
  openMarketing: "Site",
  tabs: {
    explorar: "Explore",
    capsulas: "Capsules",
    viaje: "Trip",
    mesa: "Table",
    cuenta: "Account",
  },
  explorarLead:
    "Chile by landscape. Tap a destination or capsule on the map. Nearest to you first.",
  searchPlaces: "Search destination or capsule…",
  nearby: "Near you",
  locating: "Finding your location…",
  useLocation: "Use my location",
  locationDenied: "Turn on location to sort by distance.",
  planThis: "Plan this destination",
  seeCapsule: "See capsule",
  from: "from",
  away: "away",
  all: "All",
  capsulasLead:
    "One capsule home per landscape — copper, glass and wood — run by local partners. Book with Stripe.",
  book: "Book",
  booking: "Booking…",
  bookThis: "Book this capsule",
  perNight: "per night",
  nights: "Nights",
  guests: "Travelers",
  payStripe: "Pay with Stripe",
  noStripe: "Stripe is not configured on this server.",
  bookNeedProfile: "Add your name and email in Account to book.",
  bookFail: "Could not start checkout.",
  viajeLead:
    "Choose landscape and budget. Mapucoin builds capsule, table and activities, and Grok answers.",
  paidBanner: "Payment received. We will write with capsule check-in.",
  mesaLead:
    "The table of the territory and what you do there: astronomy, surf, tasting, trekking, kayak, ski.",
  food: "Gastronomy",
  activities: "Activities",
  account: {
    lead: "Your traveler file. Bookings, contact details and role on Mapucoin.",
    name: "Name",
    email: "Email",
    phone: "Phone",
    city: "City",
    instagram: "Instagram",
    role: "Role",
    save: "Save",
    saving: "Saving…",
    saved: "Profile saved.",
    saveError: "Could not save.",
    logout: "Log out",
    bookings: "Your bookings",
    noBookings: "No bookings yet. Pick a capsule and pay with Stripe.",
    partnerCta: "Join as a partner",
    partnerLead: "You run a capsule, a table or a tour. Apply from here.",
    roles: {
      traveler: "Traveler",
      partner: "Partner",
    },
    nameError: "Enter your name.",
    emailError: "Invalid email.",
    instagramError: "Invalid Instagram.",
  },
  sessionNeeded: "Sign in to open the Mapucoin App.",
  loginTitle: "Log in",
  signupTitle: "Create account",
  loginCta: "Log in",
  signupCta: "Create account",
  password: "Password",
  passwordConfirm: "Confirm password",
  orContinue: "or continue with email",
  googleCta: "Continue with Google",
  googleUnconfigured: "Google is not configured on this server.",
  googleDenied: "You canceled Google access.",
  googleError: "Could not sign in with Google.",
  needAccount: "No account? Create one",
  haveAccount: "Already have an account? Log in",
  loginError: "Wrong email or password.",
  signupError: "Could not create the account.",
  nameRequired: "Enter your name.",
  passwordShort: "Password must be at least 8 characters.",
  passwordMismatch: "Passwords do not match.",
  sending: "Sending…",
};

const pt: typeof es = {
  appName: "Mapucoin",
  location: "Chile",
  openMarketing: "Site",
  tabs: {
    explorar: "Explorar",
    capsulas: "Cápsulas",
    viaje: "Viagem",
    mesa: "Mesa",
    cuenta: "Conta",
  },
  explorarLead:
    "Chile por paisagem. Toque um destino ou cápsula no mapa. O mais perto de você primeiro.",
  searchPlaces: "Buscar destino ou cápsula…",
  nearby: "Perto de você",
  locating: "Buscando sua localização…",
  useLocation: "Usar minha localização",
  locationDenied: "Ative a localização para ordenar por distância.",
  planThis: "Planejar este destino",
  seeCapsule: "Ver cápsula",
  from: "a partir de",
  away: "de distância",
  all: "Todos",
  capsulasLead:
    "Uma casa cápsula por paisagem — cobre, vidro e madeira — operada por partners locais. Reserve com Stripe.",
  book: "Reservar",
  booking: "Reservando…",
  bookThis: "Reservar esta cápsula",
  perNight: "por noite",
  nights: "Noites",
  guests: "Viajantes",
  payStripe: "Pagar com Stripe",
  noStripe: "Stripe não está configurado neste servidor.",
  bookNeedProfile: "Complete nome e e-mail em Conta para reservar.",
  bookFail: "Não foi possível iniciar o pagamento.",
  viajeLead:
    "Escolha paisagem e orçamento. O Mapucoin monta cápsula, mesa e atividades, e o Grok responde.",
  paidBanner: "Pagamento recebido. Escrevemos com o check-in da cápsula.",
  mesaLead:
    "A mesa do território e o que se faz lá: astronomia, surf, degustação, trekking, caiaque, ski.",
  food: "Gastronomia",
  activities: "Atividades",
  account: {
    lead: "Sua ficha de viajante. Reservas, contato e papel no Mapucoin.",
    name: "Nome",
    email: "E-mail",
    phone: "Telefone",
    city: "Cidade",
    instagram: "Instagram",
    role: "Papel",
    save: "Salvar",
    saving: "Salvando…",
    saved: "Perfil salvo.",
    saveError: "Não foi possível salvar.",
    logout: "Sair",
    bookings: "Suas reservas",
    noBookings: "Ainda não há reservas. Escolha uma cápsula e pague com Stripe.",
    partnerCta: "Entrar como partner",
    partnerLead: "Você opera uma cápsula, uma mesa ou um tour. Candidate-se aqui.",
    roles: {
      traveler: "Viajante",
      partner: "Partner",
    },
    nameError: "Escreva seu nome.",
    emailError: "E-mail inválido.",
    instagramError: "Instagram inválido.",
  },
  sessionNeeded: "Entre para abrir o App Mapucoin.",
  loginTitle: "Entrar",
  signupTitle: "Criar conta",
  loginCta: "Entrar",
  signupCta: "Criar conta",
  password: "Senha",
  passwordConfirm: "Confirmar senha",
  orContinue: "ou continue com e-mail",
  googleCta: "Continuar com Google",
  googleUnconfigured: "Google não está configurado neste servidor.",
  googleDenied: "Você cancelou o acesso com Google.",
  googleError: "Não foi possível entrar com Google.",
  needAccount: "Não tem conta? Criar uma",
  haveAccount: "Já tem conta? Entrar",
  loginError: "E-mail ou senha incorretos.",
  signupError: "Não foi possível criar a conta.",
  nameRequired: "Escreva seu nome.",
  passwordShort: "A senha deve ter pelo menos 8 caracteres.",
  passwordMismatch: "As senhas não coincidem.",
  sending: "Enviando…",
};

const fr: typeof es = {
  appName: "Mapucoin",
  location: "Chili",
  openMarketing: "Site",
  tabs: {
    explorar: "Explorer",
    capsulas: "Capsules",
    viaje: "Voyage",
    mesa: "Table",
    cuenta: "Compte",
  },
  explorarLead:
    "Le Chili par paysage. Touchez une destination ou une capsule sur la carte. Le plus proche d’abord.",
  searchPlaces: "Chercher une destination ou une capsule…",
  nearby: "Près de vous",
  locating: "Recherche de votre position…",
  useLocation: "Utiliser ma position",
  locationDenied: "Activez la localisation pour trier par distance.",
  planThis: "Planifier cette destination",
  seeCapsule: "Voir la capsule",
  from: "à partir de",
  away: "de distance",
  all: "Tous",
  capsulasLead:
    "Une maison capsule par paysage — cuivre, verre et bois — gérée par des partenaires locaux. Réservez avec Stripe.",
  book: "Réserver",
  booking: "Réservation…",
  bookThis: "Réserver cette capsule",
  perNight: "par nuit",
  nights: "Nuits",
  guests: "Voyageurs",
  payStripe: "Payer avec Stripe",
  noStripe: "Stripe n’est pas configuré sur ce serveur.",
  bookNeedProfile: "Ajoutez nom et e-mail dans Compte pour réserver.",
  bookFail: "Impossible de lancer le paiement.",
  viajeLead:
    "Choisissez paysage et budget. Mapucoin compose capsule, table et activités, et Grok répond.",
  paidBanner: "Paiement reçu. Nous écrivons avec le check-in de la capsule.",
  mesaLead:
    "La table du territoire et ce que l’on y fait : astronomie, surf, dégustation, trekking, kayak, ski.",
  food: "Gastronomie",
  activities: "Activités",
  account: {
    lead: "Votre fiche voyageur. Réservations, contact et rôle sur Mapucoin.",
    name: "Nom",
    email: "E-mail",
    phone: "Téléphone",
    city: "Ville",
    instagram: "Instagram",
    role: "Rôle",
    save: "Enregistrer",
    saving: "Enregistrement…",
    saved: "Profil enregistré.",
    saveError: "Impossible d’enregistrer.",
    logout: "Sortir",
    bookings: "Vos réservations",
    noBookings: "Pas encore de réservation. Choisissez une capsule et payez avec Stripe.",
    partnerCta: "Devenir partenaire",
    partnerLead: "Vous tenez une capsule, une table ou un tour. Candidatez ici.",
    roles: {
      traveler: "Voyageur",
      partner: "Partenaire",
    },
    nameError: "Écrivez votre nom.",
    emailError: "E-mail invalide.",
    instagramError: "Instagram invalide.",
  },
  sessionNeeded: "Connectez-vous pour ouvrir l’App Mapucoin.",
  loginTitle: "Connexion",
  signupTitle: "Créer un compte",
  loginCta: "Connexion",
  signupCta: "Créer un compte",
  password: "Mot de passe",
  passwordConfirm: "Confirmer le mot de passe",
  orContinue: "ou continuer avec l’e-mail",
  googleCta: "Continuer avec Google",
  googleUnconfigured: "Google n’est pas configuré sur ce serveur.",
  googleDenied: "Vous avez annulé l’accès Google.",
  googleError: "Impossible de se connecter avec Google.",
  needAccount: "Pas de compte ? En créer un",
  haveAccount: "Déjà un compte ? Connexion",
  loginError: "E-mail ou mot de passe incorrect.",
  signupError: "Impossible de créer le compte.",
  nameRequired: "Écrivez votre nom.",
  passwordShort: "Le mot de passe doit avoir au moins 8 caractères.",
  passwordMismatch: "Les mots de passe ne correspondent pas.",
  sending: "Envoi…",
};

const it: typeof es = {
  appName: "Mapucoin",
  location: "Cile",
  openMarketing: "Sito",
  tabs: {
    explorar: "Esplora",
    capsulas: "Capsule",
    viaje: "Viaggio",
    mesa: "Tavola",
    cuenta: "Account",
  },
  explorarLead:
    "Il Cile per paesaggio. Tocca una destinazione o una capsula sulla mappa. Prima il più vicino a te.",
  searchPlaces: "Cerca destinazione o capsula…",
  nearby: "Vicino a te",
  locating: "Cerco la tua posizione…",
  useLocation: "Usa la mia posizione",
  locationDenied: "Attiva la posizione per ordinare per distanza.",
  planThis: "Pianifica questa destinazione",
  seeCapsule: "Vedi capsula",
  from: "da",
  away: "di distanza",
  all: "Tutti",
  capsulasLead:
    "Una casa capsula per paesaggio — rame, vetro e legno — gestita da partner locali. Prenota con Stripe.",
  book: "Prenota",
  booking: "Prenotazione…",
  bookThis: "Prenota questa capsula",
  perNight: "a notte",
  nights: "Notti",
  guests: "Viaggiatori",
  payStripe: "Paga con Stripe",
  noStripe: "Stripe non è configurato su questo server.",
  bookNeedProfile: "Completa nome e email in Account per prenotare.",
  bookFail: "Impossibile avviare il pagamento.",
  viajeLead:
    "Scegli paesaggio e budget. Mapucoin compone capsula, tavola e attività, e Grok risponde.",
  paidBanner: "Pagamento ricevuto. Scriviamo con il check-in della capsula.",
  mesaLead:
    "La tavola del territorio e cosa si fa lì: astronomia, surf, degustazione, trekking, kayak, sci.",
  food: "Gastronomia",
  activities: "Attività",
  account: {
    lead: "La tua scheda viaggiatore. Prenotazioni, contatti e ruolo su Mapucoin.",
    name: "Nome",
    email: "Email",
    phone: "Telefono",
    city: "Città",
    instagram: "Instagram",
    role: "Ruolo",
    save: "Salva",
    saving: "Salvataggio…",
    saved: "Profilo salvato.",
    saveError: "Impossibile salvare.",
    logout: "Esci",
    bookings: "Le tue prenotazioni",
    noBookings: "Nessuna prenotazione. Scegli una capsula e paga con Stripe.",
    partnerCta: "Entra come partner",
    partnerLead: "Gestisci una capsula, una tavola o un tour. Candidati da qui.",
    roles: {
      traveler: "Viaggiatore",
      partner: "Partner",
    },
    nameError: "Scrivi il tuo nome.",
    emailError: "Email non valida.",
    instagramError: "Instagram non valido.",
  },
  sessionNeeded: "Accedi per aprire l’App Mapucoin.",
  loginTitle: "Accedi",
  signupTitle: "Crea account",
  loginCta: "Accedi",
  signupCta: "Crea account",
  password: "Password",
  passwordConfirm: "Conferma password",
  orContinue: "oppure continua con email",
  googleCta: "Continua con Google",
  googleUnconfigured: "Google non è configurato su questo server.",
  googleDenied: "Hai annullato l’accesso con Google.",
  googleError: "Impossibile accedere con Google.",
  needAccount: "Non hai un account? Creane uno",
  haveAccount: "Hai già un account? Accedi",
  loginError: "Email o password errati.",
  signupError: "Impossibile creare l’account.",
  nameRequired: "Scrivi il tuo nome.",
  passwordShort: "La password deve avere almeno 8 caratteri.",
  passwordMismatch: "Le password non coincidono.",
  sending: "Invio…",
};

export const appCopy = { es, en, pt, fr, it } as const;

export function at(locale: Locale) {
  return appCopy[locale] ?? appCopy.es;
}
