import type { Locale } from "./locale";

export type AppTab = "explorar" | "capsulas" | "viaje" | "mesa" | "cuenta";

const es = {
  appName: "Mapucoin",
  location: "Chile",
  openMarketing: "Sitio",
  tabs: {
    explorar: "Explorar",
    capsulas: "Cápsulas",
    viaje: "Viaje",
    mesa: "Gastronomía",
    cuenta: "Cuenta",
  },
  explorarLead:
    "Chile por paisaje. Toca un destino o una cápsula en el mapa. Lo más cercano a ti primero.",
  searchPlaces: "Buscar destino o cápsula…",
  nearby: "Cerca de ti",
  locating: "Buscando tu ubicación…",
  useLocation: "Usar mi ubicación",
  locationDenied: "Activa la ubicación para ordenar por distancia.",
  planThis: "Planificar este destino",
  seeCapsule: "Ver cápsula",
  from: "desde",
  away: "de distancia",
  all: "Todos",
  capsulasLead:
    "Una casa cápsula por paisaje — cobre, vidrio y madera — operada por partners locales. Reserva con Stripe.",
  book: "Reservar",
  booking: "Reservando…",
  bookThis: "Reservar esta cápsula",
  perNight: "por noche",
  nights: "Noches",
  guests: "Viajeros",
  payStripe: "Pagar con Stripe",
  noStripe: "Stripe no está configurado en este servidor.",
  bookNeedProfile: "Completa nombre y correo en Cuenta para reservar.",
  bookFail: "No se pudo iniciar el pago.",
  viajeLead:
    "Elige paisaje y presupuesto. Mapucoin arma cápsula, gastronomía y actividades, y Grok responde.",
  paidBanner: "Pago recibido. Te escribimos con el check-in de la cápsula.",
  mesaLead:
    "La gastronomía del territorio y lo que se hace ahí: astronomía, surf, cata, trekking, kayak, ski.",
  food: "Gastronomía",
  activities: "Actividades",
  account: {
    lead: "Tu ficha de viajero. Reservas, datos de contacto y rol en Mapucoin.",
    name: "Nombre",
    email: "Correo",
    phone: "Teléfono",
    city: "Ciudad",
    instagram: "Instagram",
    role: "Rol",
    save: "Guardar",
    saving: "Guardando…",
    saved: "Perfil guardado.",
    saveError: "No se pudo guardar.",
    logout: "Salir",
    bookings: "Tus reservas",
    noBookings: "Aún no hay reservas. Elige una cápsula y paga con Stripe.",
    partnerCta: "Ingresar como partner",
    partnerLead: "Operas una cápsula, gastronomía o un tour. Postula desde aquí.",
    roles: {
      traveler: "Viajero",
      partner: "Partner",
    },
    nameError: "Escribe tu nombre.",
    emailError: "Correo inválido.",
    instagramError: "Instagram inválido.",
    biometricTitle: "Entrar con el pulgar",
    biometricHint:
      "Desbloquea Mapucoin con tu huella, Face ID o Windows Hello en este dispositivo.",
    biometricOn: "Activado",
    biometricOff: "Desactivado",
    biometricEnableHint: "Activa el interruptor y confirma con tu huella.",
    biometricEnabled: "Ya puedes entrar a la app con tu huella.",
    biometricDisabled: "Entrada con huella desactivada.",
    biometricNeedLogin: "Entra primero para activar la huella.",
    biometricUnavailable:
      "Este dispositivo no tiene huella, Face ID o Windows Hello disponible.",
    biometricFailed: "No se pudo verificar la huella. Inténtalo de nuevo.",
    biometricPromptTitle: "¿Entrar con tu pulgar?",
    biometricPromptBody:
      "La próxima vez entra a Mapucoin con tu huella en este dispositivo.",
    biometricPromptLater: "Ahora no",
    biometricPromptEnable: "Activar huella",
    biometricProcessing: "Esperando tu huella…",
  },
  sessionNeeded: "Entra para abrir la App Mapucoin.",
  loginTitle: "Entrar",
  signupTitle: "Crear cuenta",
  loginCta: "Entrar",
  signupCta: "Crear cuenta",
  password: "Contraseña",
  passwordConfirm: "Confirmar contraseña",
  orContinue: "o continúa con correo",
  googleCta: "Continuar con Google",
  googleUnconfigured: "Google no está configurado en este servidor.",
  googleDenied: "Cancelaste el acceso con Google.",
  googleError: "No se pudo entrar con Google.",
  needAccount: "¿No tienes cuenta? Crear una",
  haveAccount: "¿Ya tienes cuenta? Entrar",
  loginError: "Correo o contraseña incorrectos.",
  signupError: "No se pudo crear la cuenta.",
  nameRequired: "Escribe tu nombre.",
  passwordShort: "La contraseña debe tener al menos 8 caracteres.",
  passwordMismatch: "Las contraseñas no coinciden.",
  sending: "Enviando…",
  biometricEnter: "Entrar con el pulgar",
  biometricProcessing: "Esperando tu huella…",
  biometricRetry: "Vuelve a colocar el pulgar",
  biometricFailed: "No se pudo verificar la huella. Inténtalo de nuevo.",
  biometricUnavailable:
    "Este dispositivo no tiene huella, Face ID o Windows Hello disponible.",
  biometricExpired: "La sesión con huella expiró. Entra con email o Google.",
  biometricLockTitle: "Mapucoin",
  biometricLockSubtitle: "Coloca tu pulgar en el sensor",
  biometricUsePassword: "Usar contraseña",
};

const en: typeof es = {
  appName: "Mapucoin",
  location: "Chile",
  openMarketing: "Site",
  tabs: {
    explorar: "Explore",
    capsulas: "Capsules",
    viaje: "Trip",
    mesa: "Gastronomy",
    cuenta: "Account",
  },
  explorarLead:
    "Chile by landscape. Tap a destination or capsule on the map. Nearest to you first.",
  searchPlaces: "Search destination or capsule…",
  nearby: "Near you",
  locating: "Finding your location…",
  useLocation: "Use my location",
  locationDenied: "Turn on location to sort by distance.",
  planThis: "Plan this destination",
  seeCapsule: "See capsule",
  from: "from",
  away: "away",
  all: "All",
  capsulasLead:
    "One capsule home per landscape — copper, glass and wood — run by local partners. Book with Stripe.",
  book: "Book",
  booking: "Booking…",
  bookThis: "Book this capsule",
  perNight: "per night",
  nights: "Nights",
  guests: "Travelers",
  payStripe: "Pay with Stripe",
  noStripe: "Stripe is not configured on this server.",
  bookNeedProfile: "Add your name and email in Account to book.",
  bookFail: "Could not start checkout.",
  viajeLead:
    "Choose landscape and budget. Mapucoin builds capsule, gastronomy and activities, and Grok answers.",
  paidBanner: "Payment received. We will write with capsule check-in.",
  mesaLead:
    "The gastronomy of the territory and what you do there: astronomy, surf, tasting, trekking, kayak, ski.",
  food: "Gastronomy",
  activities: "Activities",
  account: {
    lead: "Your traveler file. Bookings, contact details and role on Mapucoin.",
    name: "Name",
    email: "Email",
    phone: "Phone",
    city: "City",
    instagram: "Instagram",
    role: "Role",
    save: "Save",
    saving: "Saving…",
    saved: "Profile saved.",
    saveError: "Could not save.",
    logout: "Log out",
    bookings: "Your bookings",
    noBookings: "No bookings yet. Pick a capsule and pay with Stripe.",
    partnerCta: "Join as a partner",
    partnerLead: "You run a capsule, gastronomy or a tour. Apply from here.",
    roles: {
      traveler: "Traveler",
      partner: "Partner",
    },
    nameError: "Enter your name.",
    emailError: "Invalid email.",
    instagramError: "Invalid Instagram.",
    biometricTitle: "Unlock with your thumb",
    biometricHint:
      "Unlock Mapucoin with your fingerprint, Face ID, or Windows Hello on this device.",
    biometricOn: "On",
    biometricOff: "Off",
    biometricEnableHint: "Flip the switch and confirm with your fingerprint.",
    biometricEnabled: "You can now enter the app with your fingerprint.",
    biometricDisabled: "Fingerprint unlock turned off.",
    biometricNeedLogin: "Sign in first to enable fingerprint.",
    biometricUnavailable:
      "This device has no fingerprint, Face ID, or Windows Hello available.",
    biometricFailed: "Fingerprint could not be verified. Try again.",
    biometricPromptTitle: "Unlock with your thumb?",
    biometricPromptBody:
      "Next time, enter Mapucoin with your fingerprint on this device.",
    biometricPromptLater: "Not now",
    biometricPromptEnable: "Enable fingerprint",
    biometricProcessing: "Waiting for your fingerprint…",
  },
  sessionNeeded: "Sign in to open the Mapucoin App.",
  loginTitle: "Log in",
  signupTitle: "Create account",
  loginCta: "Log in",
  signupCta: "Create account",
  password: "Password",
  passwordConfirm: "Confirm password",
  orContinue: "or continue with email",
  googleCta: "Continue with Google",
  googleUnconfigured: "Google is not configured on this server.",
  googleDenied: "You canceled Google access.",
  googleError: "Could not sign in with Google.",
  needAccount: "No account? Create one",
  haveAccount: "Already have an account? Log in",
  loginError: "Wrong email or password.",
  signupError: "Could not create the account.",
  nameRequired: "Enter your name.",
  passwordShort: "Password must be at least 8 characters.",
  passwordMismatch: "Passwords do not match.",
  sending: "Sending…",
  biometricEnter: "Sign in with your thumb",
  biometricProcessing: "Waiting for your fingerprint…",
  biometricRetry: "Place your finger on the sensor again",
  biometricFailed: "Fingerprint could not be verified. Try again.",
  biometricUnavailable:
    "This device has no fingerprint, Face ID, or Windows Hello available.",
  biometricExpired: "Fingerprint session expired. Sign in with email or Google.",
  biometricLockTitle: "Mapucoin",
  biometricLockSubtitle: "Place your finger on the sensor",
  biometricUsePassword: "Use password",
};

const pt: typeof es = {
  appName: "Mapucoin",
  location: "Chile",
  openMarketing: "Site",
  tabs: {
    explorar: "Explorar",
    capsulas: "Cápsulas",
    viaje: "Viagem",
    mesa: "Gastronomia",
    cuenta: "Conta",
  },
  explorarLead:
    "Chile por paisagem. Toque um destino ou cápsula no mapa. O mais perto de você primeiro.",
  searchPlaces: "Buscar destino ou cápsula…",
  nearby: "Perto de você",
  locating: "Buscando sua localização…",
  useLocation: "Usar minha localização",
  locationDenied: "Ative a localização para ordenar por distância.",
  planThis: "Planejar este destino",
  seeCapsule: "Ver cápsula",
  from: "a partir de",
  away: "de distância",
  all: "Todos",
  capsulasLead:
    "Uma casa cápsula por paisagem — cobre, vidro e madeira — operada por partners locais. Reserve com Stripe.",
  book: "Reservar",
  booking: "Reservando…",
  bookThis: "Reservar esta cápsula",
  perNight: "por noite",
  nights: "Noites",
  guests: "Viajantes",
  payStripe: "Pagar com Stripe",
  noStripe: "Stripe não está configurado neste servidor.",
  bookNeedProfile: "Complete nome e e-mail em Conta para reservar.",
  bookFail: "Não foi possível iniciar o pagamento.",
  viajeLead:
    "Escolha paisagem e orçamento. O Mapucoin monta cápsula, gastronomia e atividades, e o Grok responde.",
  paidBanner: "Pagamento recebido. Escrevemos com o check-in da cápsula.",
  mesaLead:
    "A gastronomia do território e o que se faz lá: astronomia, surf, degustação, trekking, caiaque, ski.",
  food: "Gastronomia",
  activities: "Atividades",
  account: {
    lead: "Sua ficha de viajante. Reservas, contato e papel no Mapucoin.",
    name: "Nome",
    email: "E-mail",
    phone: "Telefone",
    city: "Cidade",
    instagram: "Instagram",
    role: "Papel",
    save: "Salvar",
    saving: "Salvando…",
    saved: "Perfil salvo.",
    saveError: "Não foi possível salvar.",
    logout: "Sair",
    bookings: "Suas reservas",
    noBookings: "Ainda não há reservas. Escolha uma cápsula e pague com Stripe.",
    partnerCta: "Entrar como partner",
    partnerLead: "Você opera uma cápsula, gastronomia ou um tour. Candidate-se aqui.",
    roles: {
      traveler: "Viajante",
      partner: "Partner",
    },
    nameError: "Escreva seu nome.",
    emailError: "E-mail inválido.",
    instagramError: "Instagram inválido.",
    biometricTitle: "Entrar com o polegar",
    biometricHint:
      "Desbloqueie o Mapucoin com sua digital, Face ID ou Windows Hello neste dispositivo.",
    biometricOn: "Ativado",
    biometricOff: "Desativado",
    biometricEnableHint: "Ative o interruptor e confirme com a digital.",
    biometricEnabled: "Já pode entrar no app com a digital.",
    biometricDisabled: "Entrada com digital desativada.",
    biometricNeedLogin: "Entre primeiro para ativar a digital.",
    biometricUnavailable:
      "Este dispositivo não tem digital, Face ID ou Windows Hello disponível.",
    biometricFailed: "Não foi possível verificar a digital. Tente de novo.",
    biometricPromptTitle: "Entrar com o polegar?",
    biometricPromptBody:
      "Da próxima vez entre no Mapucoin com a digital neste dispositivo.",
    biometricPromptLater: "Agora não",
    biometricPromptEnable: "Ativar digital",
    biometricProcessing: "Aguardando sua digital…",
  },
  sessionNeeded: "Entre para abrir o App Mapucoin.",
  loginTitle: "Entrar",
  signupTitle: "Criar conta",
  loginCta: "Entrar",
  signupCta: "Criar conta",
  password: "Senha",
  passwordConfirm: "Confirmar senha",
  orContinue: "ou continue com e-mail",
  googleCta: "Continuar com Google",
  googleUnconfigured: "Google não está configurado neste servidor.",
  googleDenied: "Você cancelou o acesso com Google.",
  googleError: "Não foi possível entrar com Google.",
  needAccount: "Não tem conta? Criar uma",
  haveAccount: "Já tem conta? Entrar",
  loginError: "E-mail ou senha incorretos.",
  signupError: "Não foi possível criar a conta.",
  nameRequired: "Escreva seu nome.",
  passwordShort: "A senha deve ter pelo menos 8 caracteres.",
  passwordMismatch: "As senhas não coincidem.",
  sending: "Enviando…",
  biometricEnter: "Entrar com o polegar",
  biometricProcessing: "Aguardando sua digital…",
  biometricRetry: "Coloque o polegar no sensor de novo",
  biometricFailed: "Não foi possível verificar a digital. Tente de novo.",
  biometricUnavailable:
    "Este dispositivo não tem digital, Face ID ou Windows Hello disponível.",
  biometricExpired: "A sessão com digital expirou. Entre com email ou Google.",
  biometricLockTitle: "Mapucoin",
  biometricLockSubtitle: "Coloque o polegar no sensor",
  biometricUsePassword: "Usar senha",
};

const fr: typeof es = {
  appName: "Mapucoin",
  location: "Chili",
  openMarketing: "Site",
  tabs: {
    explorar: "Explorer",
    capsulas: "Capsules",
    viaje: "Voyage",
    mesa: "Gastronomy",
    cuenta: "Compte",
  },
  explorarLead:
    "Le Chili par paysage. Touchez une destination ou une capsule sur la carte. Le plus proche d’abord.",
  searchPlaces: "Chercher une destination ou une capsule…",
  nearby: "Près de vous",
  locating: "Recherche de votre position…",
  useLocation: "Utiliser ma position",
  locationDenied: "Activez la localisation pour trier par distance.",
  planThis: "Planifier cette destination",
  seeCapsule: "Voir la capsule",
  from: "à partir de",
  away: "de distance",
  all: "Tous",
  capsulasLead:
    "Une maison capsule par paysage — cuivre, verre et bois — gérée par des partenaires locaux. Réservez avec Stripe.",
  book: "Réserver",
  booking: "Réservation…",
  bookThis: "Réserver cette capsule",
  perNight: "par nuit",
  nights: "Nuits",
  guests: "Voyageurs",
  payStripe: "Payer avec Stripe",
  noStripe: "Stripe n’est pas configuré sur ce serveur.",
  bookNeedProfile: "Ajoutez nom et e-mail dans Compte pour réserver.",
  bookFail: "Impossible de lancer le paiement.",
  viajeLead:
    "Choisissez paysage et budget. Mapucoin compose capsule, gastronomie et activités, et Grok répond.",
  paidBanner: "Paiement reçu. Nous écrivons avec le check-in de la capsule.",
  mesaLead:
    "La gastronomie du territoire et ce que l’on y fait : astronomie, surf, dégustation, trekking, kayak, ski.",
  food: "Gastronomie",
  activities: "Activités",
  account: {
    lead: "Votre fiche voyageur. Réservations, contact et rôle sur Mapucoin.",
    name: "Nom",
    email: "E-mail",
    phone: "Téléphone",
    city: "Ville",
    instagram: "Instagram",
    role: "Rôle",
    save: "Enregistrer",
    saving: "Enregistrement…",
    saved: "Profil enregistré.",
    saveError: "Impossible d’enregistrer.",
    logout: "Sortir",
    bookings: "Vos réservations",
    noBookings: "Pas encore de réservation. Choisissez une capsule et payez avec Stripe.",
    partnerCta: "Devenir partenaire",
    partnerLead: "Vous tenez une capsule, de la gastronomie ou un tour. Candidatez ici.",
    roles: {
      traveler: "Voyageur",
      partner: "Partenaire",
    },
    nameError: "Écrivez votre nom.",
    emailError: "E-mail invalide.",
    instagramError: "Instagram invalide.",
    biometricTitle: "Entrer avec le pouce",
    biometricHint:
      "Déverrouillez Mapucoin avec votre empreinte, Face ID ou Windows Hello sur cet appareil.",
    biometricOn: "Activé",
    biometricOff: "Désactivé",
    biometricEnableHint: "Activez l’interrupteur et confirmez avec votre empreinte.",
    biometricEnabled: "Vous pouvez maintenant entrer dans l’app avec votre empreinte.",
    biometricDisabled: "Entrée par empreinte désactivée.",
    biometricNeedLogin: "Connectez-vous d’abord pour activer l’empreinte.",
    biometricUnavailable:
      "Cet appareil n’a pas d’empreinte, Face ID ou Windows Hello disponible.",
    biometricFailed: "Empreinte non vérifiée. Réessayez.",
    biometricPromptTitle: "Entrer avec le pouce ?",
    biometricPromptBody:
      "La prochaine fois, entrez dans Mapucoin avec votre empreinte sur cet appareil.",
    biometricPromptLater: "Pas maintenant",
    biometricPromptEnable: "Activer l’empreinte",
    biometricProcessing: "En attente de votre empreinte…",
  },
  sessionNeeded: "Connectez-vous pour ouvrir l’App Mapucoin.",
  loginTitle: "Connexion",
  signupTitle: "Créer un compte",
  loginCta: "Connexion",
  signupCta: "Créer un compte",
  password: "Mot de passe",
  passwordConfirm: "Confirmer le mot de passe",
  orContinue: "ou continuer avec l’e-mail",
  googleCta: "Continuer avec Google",
  googleUnconfigured: "Google n’est pas configuré sur ce serveur.",
  googleDenied: "Vous avez annulé l’accès Google.",
  googleError: "Impossible de se connecter avec Google.",
  needAccount: "Pas de compte ? En créer un",
  haveAccount: "Déjà un compte ? Connexion",
  loginError: "E-mail ou mot de passe incorrect.",
  signupError: "Impossible de créer le compte.",
  nameRequired: "Écrivez votre nom.",
  passwordShort: "Le mot de passe doit avoir au moins 8 caractères.",
  passwordMismatch: "Les mots de passe ne correspondent pas.",
  sending: "Envoi…",
  biometricEnter: "Entrer avec le pouce",
  biometricProcessing: "En attente de votre empreinte…",
  biometricRetry: "Replacez le pouce sur le capteur",
  biometricFailed: "Empreinte non vérifiée. Réessayez.",
  biometricUnavailable:
    "Cet appareil n’a pas d’empreinte, Face ID ou Windows Hello disponible.",
  biometricExpired: "La session empreinte a expiré. Entrez avec e-mail ou Google.",
  biometricLockTitle: "Mapucoin",
  biometricLockSubtitle: "Placez le pouce sur le capteur",
  biometricUsePassword: "Utiliser le mot de passe",
};

const it: typeof es = {
  appName: "Mapucoin",
  location: "Cile",
  openMarketing: "Sito",
  tabs: {
    explorar: "Esplora",
    capsulas: "Capsule",
    viaje: "Viaggio",
    mesa: "Gastronomia",
    cuenta: "Account",
  },
  explorarLead:
    "Il Cile per paesaggio. Tocca una destinazione o una capsula sulla mappa. Prima il più vicino a te.",
  searchPlaces: "Cerca destinazione o capsula…",
  nearby: "Vicino a te",
  locating: "Cerco la tua posizione…",
  useLocation: "Usa la mia posizione",
  locationDenied: "Attiva la posizione per ordinare per distanza.",
  planThis: "Pianifica questa destinazione",
  seeCapsule: "Vedi capsula",
  from: "da",
  away: "di distanza",
  all: "Tutti",
  capsulasLead:
    "Una casa capsula per paesaggio — rame, vetro e legno — gestita da partner locali. Prenota con Stripe.",
  book: "Prenota",
  booking: "Prenotazione…",
  bookThis: "Prenota questa capsula",
  perNight: "a notte",
  nights: "Notti",
  guests: "Viaggiatori",
  payStripe: "Paga con Stripe",
  noStripe: "Stripe non è configurato su questo server.",
  bookNeedProfile: "Completa nome e email in Account per prenotare.",
  bookFail: "Impossibile avviare il pagamento.",
  viajeLead:
    "Scegli paesaggio e budget. Mapucoin compone capsula, gastronomia e attività, e Grok risponde.",
  paidBanner: "Pagamento ricevuto. Scriviamo con il check-in della capsula.",
  mesaLead:
    "La gastronomia del territorio e cosa si fa lì: astronomia, surf, degustazione, trekking, kayak, sci.",
  food: "Gastronomia",
  activities: "Attività",
  account: {
    lead: "La tua scheda viaggiatore. Prenotazioni, contatti e ruolo su Mapucoin.",
    name: "Nome",
    email: "Email",
    phone: "Telefono",
    city: "Città",
    instagram: "Instagram",
    role: "Ruolo",
    save: "Salva",
    saving: "Salvataggio…",
    saved: "Profilo salvato.",
    saveError: "Impossibile salvare.",
    logout: "Esci",
    bookings: "Le tue prenotazioni",
    noBookings: "Nessuna prenotazione. Scegli una capsula e paga con Stripe.",
    partnerCta: "Entra come partner",
    partnerLead: "Gestisci una capsula, gastronomia o un tour. Candidati da qui.",
    roles: {
      traveler: "Viaggiatore",
      partner: "Partner",
    },
    nameError: "Scrivi il tuo nome.",
    emailError: "Email non valida.",
    instagramError: "Instagram non valido.",
    biometricTitle: "Entra con il pollice",
    biometricHint:
      "Sblocca Mapucoin con l’impronta, Face ID o Windows Hello su questo dispositivo.",
    biometricOn: "Attivo",
    biometricOff: "Disattivo",
    biometricEnableHint: "Attiva l’interruttore e conferma con l’impronta.",
    biometricEnabled: "Ora puoi entrare nell’app con l’impronta.",
    biometricDisabled: "Accesso con impronta disattivato.",
    biometricNeedLogin: "Entra prima per attivare l’impronta.",
    biometricUnavailable:
      "Questo dispositivo non ha impronta, Face ID o Windows Hello disponibile.",
    biometricFailed: "Impronta non verificata. Riprova.",
    biometricPromptTitle: "Entra con il pollice?",
    biometricPromptBody:
      "La prossima volta entra in Mapucoin con l’impronta su questo dispositivo.",
    biometricPromptLater: "Ora no",
    biometricPromptEnable: "Attiva impronta",
    biometricProcessing: "In attesa della tua impronta…",
  },
  sessionNeeded: "Accedi per aprire l’App Mapucoin.",
  loginTitle: "Accedi",
  signupTitle: "Crea account",
  loginCta: "Accedi",
  signupCta: "Crea account",
  password: "Password",
  passwordConfirm: "Conferma password",
  orContinue: "oppure continua con email",
  googleCta: "Continua con Google",
  googleUnconfigured: "Google non è configurato su questo server.",
  googleDenied: "Hai annullato l’accesso con Google.",
  googleError: "Impossibile accedere con Google.",
  needAccount: "Non hai un account? Creane uno",
  haveAccount: "Hai già un account? Accedi",
  loginError: "Email o password errati.",
  signupError: "Impossibile creare l’account.",
  nameRequired: "Scrivi il tuo nome.",
  passwordShort: "La password deve avere almeno 8 caratteri.",
  passwordMismatch: "Le password non coincidono.",
  sending: "Invio…",
  biometricEnter: "Entra con il pollice",
  biometricProcessing: "In attesa della tua impronta…",
  biometricRetry: "Riposiziona il pollice sul sensore",
  biometricFailed: "Impronta non verificata. Riprova.",
  biometricUnavailable:
    "Questo dispositivo non ha impronta, Face ID o Windows Hello disponibile.",
  biometricExpired: "La sessione con impronta è scaduta. Entra con email o Google.",
  biometricLockTitle: "Mapucoin",
  biometricLockSubtitle: "Metti il pollice sul sensore",
  biometricUsePassword: "Usa la password",
};

const de: typeof es = {
  appName: "Mapucoin",
  location: "Chile",
  openMarketing: "Website",
  tabs: {
    explorar: "Entdecken",
    capsulas: "Kapseln",
    viaje: "Reise",
    mesa: "Gastronomie",
    cuenta: "Konto",
  },
  explorarLead:
    "Chile nach Landschaft. Tippe ein Reiseziel oder eine Kapsel auf der Karte. Das Nächste zuerst.",
  searchPlaces: "Reiseziel oder Kapsel suchen…",
  nearby: "In deiner Nähe",
  locating: "Standort wird gesucht…",
  useLocation: "Meinen Standort nutzen",
  locationDenied: "Aktiviere den Standort, um nach Entfernung zu sortieren.",
  planThis: "Dieses Reiseziel planen",
  seeCapsule: "Kapsel ansehen",
  from: "ab",
  away: "entfernt",
  all: "Alle",
  capsulasLead:
    "Ein Kapselhaus pro Landschaft — Kupfer, Glas und Holz — betrieben von lokalen Partnern. Buchen mit Stripe.",
  book: "Buchen",
  booking: "Buchung…",
  bookThis: "Diese Kapsel buchen",
  perNight: "pro Nacht",
  nights: "Nächte",
  guests: "Reisende",
  payStripe: "Mit Stripe zahlen",
  noStripe: "Stripe ist auf diesem Server nicht konfiguriert.",
  bookNeedProfile: "Trag Name und E-Mail im Konto ein, um zu buchen.",
  bookFail: "Die Zahlung konnte nicht gestartet werden.",
  viajeLead:
    "Wähle Landschaft und Budget. Mapucoin stellt Kapsel, Gastronomie und Aktivitäten zusammen, und Grok antwortet.",
  paidBanner: "Zahlung erhalten. Wir schreiben dir zum Check-in der Kapsel.",
  mesaLead:
    "Die Gastronomie des Gebiets und was man dort tut: Astronomie, Surfen, Verkostung, Trekking, Kajak, Ski.",
  food: "Gastronomie",
  activities: "Aktivitäten",
  account: {
    lead: "Dein Reisendenprofil. Buchungen, Kontaktdaten und Rolle bei Mapucoin.",
    name: "Name",
    email: "E-Mail",
    phone: "Telefon",
    city: "Stadt",
    instagram: "Instagram",
    role: "Rolle",
    save: "Speichern",
    saving: "Speichern…",
    saved: "Profil gespeichert.",
    saveError: "Speichern fehlgeschlagen.",
    logout: "Abmelden",
    bookings: "Deine Buchungen",
    noBookings: "Noch keine Buchungen. Wähle eine Kapsel und zahle mit Stripe.",
    partnerCta: "Als Partner beitreten",
    partnerLead: "Du betreibst eine Kapsel, Gastronomie oder eine Tour. Bewirb dich hier.",
    roles: {
      traveler: "Reisende",
      partner: "Partner",
    },
    nameError: "Schreib deinen Namen.",
    emailError: "Ungültige E-Mail.",
    instagramError: "Ungültiges Instagram.",
    biometricTitle: "Mit dem Daumen entsperren",
    biometricHint:
      "Entsperre Mapucoin mit Fingerabdruck, Face ID oder Windows Hello auf diesem Gerät.",
    biometricOn: "An",
    biometricOff: "Aus",
    biometricEnableHint: "Schalte den Schalter um und bestätige mit dem Fingerabdruck.",
    biometricEnabled: "Du kannst die App jetzt mit dem Fingerabdruck öffnen.",
    biometricDisabled: "Entsperren per Fingerabdruck ausgeschaltet.",
    biometricNeedLogin: "Melde dich zuerst an, um den Fingerabdruck zu aktivieren.",
    biometricUnavailable:
      "Dieses Gerät hat keinen Fingerabdruck, Face ID oder Windows Hello.",
    biometricFailed: "Fingerabdruck nicht erkannt. Versuch es erneut.",
    biometricPromptTitle: "Mit dem Daumen entsperren?",
    biometricPromptBody:
      "Beim nächsten Mal öffnest du Mapucoin mit dem Fingerabdruck auf diesem Gerät.",
    biometricPromptLater: "Jetzt nicht",
    biometricPromptEnable: "Fingerabdruck aktivieren",
    biometricProcessing: "Warte auf deinen Fingerabdruck…",
  },
  sessionNeeded: "Melde dich an, um die Mapucoin-App zu öffnen.",
  loginTitle: "Anmelden",
  signupTitle: "Konto erstellen",
  loginCta: "Anmelden",
  signupCta: "Konto erstellen",
  password: "Passwort",
  passwordConfirm: "Passwort bestätigen",
  orContinue: "oder weiter mit E-Mail",
  googleCta: "Weiter mit Google",
  googleUnconfigured: "Google ist auf diesem Server nicht konfiguriert.",
  googleDenied: "Du hast den Google-Zugang abgebrochen.",
  googleError: "Anmeldung mit Google fehlgeschlagen.",
  needAccount: "Noch kein Konto? Eines erstellen",
  haveAccount: "Schon ein Konto? Anmelden",
  loginError: "E-Mail oder Passwort ist falsch.",
  signupError: "Das Konto konnte nicht erstellt werden.",
  nameRequired: "Schreib deinen Namen.",
  passwordShort: "Das Passwort muss mindestens 8 Zeichen haben.",
  passwordMismatch: "Die Passwörter stimmen nicht überein.",
  sending: "Senden…",
  biometricEnter: "Mit dem Daumen anmelden",
  biometricProcessing: "Warte auf deinen Fingerabdruck…",
  biometricRetry: "Leg den Daumen noch einmal auf den Sensor",
  biometricFailed: "Fingerabdruck nicht erkannt. Versuch es erneut.",
  biometricUnavailable:
    "Dieses Gerät hat keinen Fingerabdruck, Face ID oder Windows Hello.",
  biometricExpired:
    "Die Fingerabdruck-Sitzung ist abgelaufen. Melde dich mit E-Mail oder Google an.",
  biometricLockTitle: "Mapucoin",
  biometricLockSubtitle: "Leg den Daumen auf den Sensor",
  biometricUsePassword: "Passwort verwenden",
};

export const appCopy = { es, en, pt, fr, it, de } as const;

export function at(locale: Locale) {
  return appCopy[locale] ?? appCopy.es;
}
