import { nationalParks } from "./parks";

export type Region =
  | "Norte Grande"
  | "Norte Chico"
  | "Centro"
  | "Valle Central"
  | "Araucanía y Lagos"
  | "Patagonia"
  | "Rapa Nui"
  | "Pacífico"
  | "Antártica";

export type Landscape =
  | "volcan"
  | "lago"
  | "desierto"
  | "bosque-nativo"
  | "vinedos"
  | "rios"
  | "nieve"
  | "playa"
  | "parques";

export type PlaceKind = "place" | "capsule" | "food" | "activity";

export type CatalogItem = {
  slug: string;
  kind: PlaceKind;
  name: string;
  region: Region;
  city: string;
  lat: number;
  lng: number;
  image: string;
  gallery?: string[];
  youtube?: string;
  youtubeStart?: number;
  tagline: string;
  description: string;
  highlights: string[];
  priceFromCLP: number;
  nightsHint?: number;
  durationHours?: number;
  capacity?: number;
  tags: string[];
  landscapes?: Landscape[];
  placeSlug?: string;
  /** Activities: landscape group, or "otros" for culture and extras. */
  cluster?: Landscape | "otros";
};

const p = (file: string) => `/images/places/${file}`;
const cap = (file: string) => `/images/${file}`;

/** 4K travel film of Chile with chapters per territory. */
export const CHILE_FILM = "uHcjT4GfPNA";

export const landscapes: { id: Landscape; label: string }[] = [
  { id: "desierto", label: "Desiertos" },
  { id: "playa", label: "Playas" },
  { id: "vinedos", label: "Viñedos" },
  { id: "volcan", label: "Volcanes" },
  { id: "rios", label: "Ríos" },
  { id: "lago", label: "Lagos" },
  { id: "bosque-nativo", label: "Bosques" },
  { id: "nieve", label: "Nieve" },
  { id: "parques", label: "Parques Nacionales" },
];

/** Shared landscape stills. Each capsule card uses its own place photo. */
export const landscapeHero: Record<Landscape, string> = {
  desierto: "/images/capsulas/desierto.jpg",
  playa: "/images/capsulas/playa.jpg",
  vinedos: "/images/capsulas/vinedos.jpg",
  volcan: "/images/capsulas/volcan.jpg",
  rios: "/images/capsulas/rios.jpg",
  lago: "/images/capsulas/lago.jpg",
  "bosque-nativo": "/images/capsulas/bosque.jpg",
  nieve: "/images/capsulas/nieve.jpg",
  parques: "/images/capsulas/parques.jpg",
};

export const landscapePlaceSlug: Record<Landscape, string> = {
  desierto: "san-pedro-de-atacama",
  playa: "bahia-inglesa",
  vinedos: "colchagua",
  volcan: "pucon",
  rios: "futaleufu",
  lago: "puerto-varas",
  "bosque-nativo": "chiloe",
  nieve: "farellones-valle-nevado",
  parques: "torres-del-paine",
};

export const landscapeLabel = (id: Landscape) =>
  landscapes.find((l) => l.id === id)?.label || id;

type Seed = {
  slug: string;
  name: string;
  region: Region;
  city: string;
  lat: number;
  lng: number;
  image: string;
  gallery?: string[];
  youtubeStart?: number;
  tagline: string;
  description: string;
  highlights: string[];
  priceFromCLP: number;
  tags: string[];
  landscapes: Landscape[];
  capsuleSlug?: string;
  capsuleName: string;
  capsuleImage: string;
  capsuleTagline: string;
  capsuleDescription: string;
  capsuleHighlights: string[];
  capsulePrice: number;
  capacity?: number;
};

const seeds: Seed[] = [
  {
    slug: "altiplano",
    name: "Altiplano",
    region: "Norte Grande",
    city: "Putre",
    lat: -18.196,
    lng: -69.559,
    image: p("parinacota.jpg"),
    gallery: [p("parinacota.jpg")],
    tagline: "Parinacota, bofedales y el techo del desierto andino.",
    description:
      "Pueblo de adobe a más de 3.500 m. Lagunas altiplánicas, vicuñas y volcanes gemelos en el parque Lauca.",
    highlights: ["Volcán Parinacota", "Parque Lauca", "Pueblo de Putre"],
    priceFromCLP: 170000,
    tags: ["desierto", "volcán", "altura", "cultura"],
    landscapes: ["desierto", "volcan"],
    capsuleName: "Cápsula Altiplano",
    capsuleImage: cap("capsula-altiplano.jpg"),
    capsuleTagline: "Cúpula de cobre y vidrio frente al Parinacota.",
    capsuleDescription:
      "Módulo climatizado para altura, con oxígeno de apoyo, techo estelar y vista a los bofedales.",
    capsuleHighlights: ["Altura 3.500 m", "Techo estelar", "Vista Parinacota"],
    capsulePrice: 175000,
  },
  {
    slug: "morro-de-arica",
    name: "Morro de Arica",
    region: "Norte Grande",
    city: "Arica",
    lat: -18.481,
    lng: -70.323,
    image: p("arica.jpg"),
    gallery: [p("arica.jpg"), p("arica-morro.jpg")],
    tagline: "El morro, el Pacífico y la ciudad más septentrional.",
    description:
      "Playa, historia del Pacífico y atardeceres sobre el morro. Puerta norte de Chile, con cultura chinchorro.",
    highlights: ["Morro", "Playa El Laucho", "Cultura Chinchorro"],
    priceFromCLP: 130000,
    tags: ["playa", "historia", "mar"],
    landscapes: ["playa"],
    capsuleName: "Cápsula Morro",
    capsuleImage: cap("capsula-playa.jpg"),
    capsuleTagline: "Cobre y vidrio sobre la playa, con el morro al fondo.",
    capsuleDescription:
      "Cápsula frente al Pacífico, deck de madera y climatización para la costa desértica.",
    capsuleHighlights: ["Vista al morro", "Deck oceánico", "Atardecer norte"],
    capsulePrice: 142000,
  },
  {
    slug: "san-pedro-de-atacama",
    name: "San Pedro de Atacama",
    region: "Norte Grande",
    city: "San Pedro de Atacama",
    lat: -22.9087,
    lng: -68.1997,
    image: p("atacama-luna.jpg"),
    gallery: [p("atacama-pueblo.jpg"), p("atacama-dunas.jpg"), p("atacama-luna.jpg")],
    youtubeStart: 263,
    tagline: "El desierto más árido y el cielo más limpio del planeta.",
    description:
      "Pueblo de adobe en el altiplano. Valle de la Luna, géiseres del Tatio, lagunas altiplánicas y astronomía de nivel mundial.",
    highlights: ["Valle de la Luna", "El Tatio", "Lagunas Miscanti y Miñiques"],
    priceFromCLP: 180000,
    tags: ["desierto", "estrellas", "cultura atacameña", "aventura"],
    landscapes: ["desierto"],
    capsuleSlug: "capsula-atacama-star",
    capsuleName: "Cápsula Atacama Star",
    capsuleImage: cap("capsula-atacama.jpg"),
    capsuleTagline: "Techo de vidrio para la Vía Láctea. Climatización y Starlink.",
    capsuleDescription:
      "Cápsula de aluminio y cobre con cúpula acristalada, cama king, ducha de lluvia y climatización de desierto. A 12 minutos de San Pedro.",
    capsuleHighlights: ["Techo estelar", "Aire acondicionado", "Desayuno atacameño"],
    capsulePrice: 165000,
  },
  {
    slug: "iquique-humberstone",
    name: "Iquique y Humberstone",
    region: "Norte Grande",
    city: "Iquique",
    lat: -20.214,
    lng: -70.152,
    image: p("humberstone.jpg"),
    gallery: [p("humberstone.jpg")],
    tagline: "Oficina salitrera UNESCO y el Pacífico de Tarapacá.",
    description:
      "Humberstone y Santa Laura, desierto de pampa y playa de Cavancha. Memoria del salitre y surf del norte.",
    highlights: ["Humberstone", "Playa Cavancha", "Pampa del Tamarugal"],
    priceFromCLP: 135000,
    tags: ["desierto", "patrimonio", "playa"],
    landscapes: ["desierto", "playa"],
    capsuleName: "Cápsula Humberstone",
    capsuleImage: cap("capsula-atacama.jpg"),
    capsuleTagline: "Pampa salitrera de noche, cobre y vidrio bajo las estrellas.",
    capsuleDescription:
      "Módulo junto a la pampa, con aislamiento térmico y traslado a la oficina salitrera.",
    capsuleHighlights: ["Pampa", "Estrellas", "Patrimonio UNESCO"],
    capsulePrice: 138000,
  },
  {
    slug: "bahia-inglesa",
    name: "Bahía Inglesa",
    region: "Norte Grande",
    city: "Caldera",
    lat: -27.105,
    lng: -70.858,
    image: p("bahia-inglesa.jpg"),
    gallery: [p("bahia-inglesa.jpg"), p("la-serena.jpg")],
    youtubeStart: 1550,
    tagline: "Agua turquesa en el desierto costero de Atacama.",
    description:
      "Caleta de arena blanca y mar Caribe en el norte chileno. Kayak, atardeceres y el desierto pegado a la playa.",
    highlights: ["Agua turquesa", "Kayak", "Desierto costero"],
    priceFromCLP: 150000,
    tags: ["playa", "desierto", "descanso"],
    landscapes: ["playa", "desierto"],
    capsuleName: "Cápsula Bahía Inglesa",
    capsuleImage: cap("capsula-playa.jpg"),
    capsuleTagline: "Deck de cobre sobre arena blanca y Pacífico turquesa.",
    capsuleDescription:
      "Cápsula frente a la bahía, vidrio panorámico y ducha de agua desalinizada.",
    capsuleHighlights: ["Frente al mar", "Arena blanca", "Atardecer"],
    capsulePrice: 158000,
  },
  {
    slug: "la-serena",
    name: "La Serena",
    region: "Norte Chico",
    city: "La Serena",
    lat: -29.9027,
    lng: -71.252,
    image: p("la-serena.jpg"),
    gallery: [p("la-serena.jpg")],
    youtubeStart: 1223,
    tagline: "Faro, Avenida del Mar y puerta al Elqui.",
    description:
      "Ciudad colonial, playa larga y observatorios a una hora. Base para el valle y la costa de Coquimbo.",
    highlights: ["Faro Monumental", "Avenida del Mar", "Arquitectura colonial"],
    priceFromCLP: 140000,
    tags: ["playa", "ciudad", "estrellas"],
    landscapes: ["playa"],
    capsuleName: "Cápsula Faro",
    capsuleImage: cap("capsula-playa.jpg"),
    capsuleTagline: "Cobre y vidrio frente a la Avenida del Mar.",
    capsuleDescription:
      "Módulo costero con vista al faro, climatización y desayuno de mar.",
    capsuleHighlights: ["Vista al faro", "Playa", "Base al Elqui"],
    capsulePrice: 145000,
  },
  {
    slug: "valle-del-elqui",
    name: "Valle del Elqui",
    region: "Norte Chico",
    city: "Pisco Elqui",
    lat: -30.1272,
    lng: -70.4931,
    image: p("elqui.jpg"),
    gallery: [p("elqui-agua.jpg"), p("mamalluca.jpg"), p("pisco-elqui.jpg")],
    youtubeStart: 1223,
    tagline: "Viñedos, pisco y observatorios bajo un cielo declarado santuario.",
    description:
      "Terrazas de uva moscatel, destilerías de pisco y observatorios abiertos al público. Ideal para descanso y astronomía.",
    highlights: ["Observatorio Mamalluca", "Pisco artesanal", "Pueblos de montaña"],
    priceFromCLP: 140000,
    tags: ["estrellas", "vino", "descanso", "gastronomía"],
    landscapes: ["vinedos"],
    capsuleSlug: "capsula-elqui-observatorio",
    capsuleName: "Cápsula Elqui Observatorio",
    capsuleImage: cap("capsula-elqui.jpg"),
    capsuleTagline: "Viñedo, telescopio y atardecer violeta sobre el valle.",
    capsuleDescription:
      "Módulo inteligente en terraza de viña. Incluye sesión con telescopio, cata de pisco y deck con hamacas.",
    capsuleHighlights: ["Telescopio", "Cata de pisco", "Viñedo privado"],
    capsulePrice: 148000,
  },
  {
    slug: "valparaiso",
    name: "Valparaíso",
    region: "Centro",
    city: "Valparaíso",
    lat: -33.0472,
    lng: -71.6127,
    image: p("valparaiso.jpg"),
    gallery: [p("valparaiso.jpg")],
    youtubeStart: 1061,
    tagline: "Cerros, ascensores y murales frente al Pacífico.",
    description:
      "Patrimonio de la Humanidad. Cerros pintados, ascensores históricos, marisquerías y vida portuaria.",
    highlights: ["Cerro Alegre", "Caleta Portales", "Street art"],
    priceFromCLP: 120000,
    tags: ["cultura", "ciudad", "mar", "gastronomía"],
    landscapes: ["playa"],
    capsuleName: "Cápsula Cerro Alegre",
    capsuleImage: cap("capsula-valparaiso.jpg"),
    capsuleTagline: "Cobre y vidrio sobre los cerros, con la bahía a los pies.",
    capsuleDescription:
      "Cápsula en terraza de cerro. Vista al puerto, aislamiento acústico y desayuno porteño.",
    capsuleHighlights: ["Vista bahía", "Cerro pintado", "Ascensores"],
    capsulePrice: 155000,
  },
  {
    slug: "vina-del-mar",
    name: "Viña del Mar",
    region: "Centro",
    city: "Viña del Mar",
    lat: -33.0153,
    lng: -71.5505,
    image: p("vina.jpg"),
    gallery: [p("vina.jpg"), p("valparaiso.jpg")],
    youtubeStart: 3379,
    tagline: "Reloj de flores, Reñaca y el balneario del Pacífico.",
    description:
      "Jardín del Pacífico: playa, casino, dunas de Reñaca y caleta de Concón a minutos.",
    highlights: ["Reloj de Flores", "Reñaca", "Caleta Concón"],
    priceFromCLP: 155000,
    tags: ["playa", "ciudad", "descanso"],
    landscapes: ["playa"],
    capsuleName: "Cápsula Reñaca",
    capsuleImage: cap("capsula-playa.jpg"),
    capsuleTagline: "Módulo de cobre sobre las dunas, con el Pacífico abierto.",
    capsuleDescription:
      "Cápsula frente a Reñaca, deck al atardecer y cama king con ventanal al oleaje.",
    capsuleHighlights: ["Dunas", "Vista océano", "Concón a 15 min"],
    capsulePrice: 168000,
  },
  {
    slug: "litoral-de-los-poetas",
    name: "Litoral de los Poetas",
    region: "Centro",
    city: "Isla Negra",
    lat: -33.399,
    lng: -71.694,
    image: p("isla-negra.jpg"),
    gallery: [p("isla-negra.jpg")],
    tagline: "Isla Negra, Neruda y los acantilados de Zapallar a San Antonio.",
    description:
      "Costa de escritores: casa de Neruda, caletas de piedra y bosques que bajan al mar.",
    highlights: ["Casa de Neruda", "Acantilados", "Caletas"],
    priceFromCLP: 140000,
    tags: ["playa", "cultura", "descanso"],
    landscapes: ["playa", "bosque-nativo"],
    capsuleName: "Cápsula Isla Negra",
    capsuleImage: cap("capsula-playa.jpg"),
    capsuleTagline: "Cobre y vidrio sobre el acantilado que miraba Neruda.",
    capsuleDescription:
      "Cápsula frente al oleaje de Isla Negra, madera nativa y biblioteca de bordo.",
    capsuleHighlights: ["Acantilado", "Casa Neruda", "Bosque costero"],
    capsulePrice: 148000,
  },
  {
    slug: "olmue",
    name: "Olmué",
    region: "Centro",
    city: "Olmué",
    lat: -32.995,
    lng: -71.186,
    image: p("olmue.jpg"),
    gallery: [p("olmue.jpg")],
    tagline: "Parque La Campana, palma chilena y el cerro de Darwin.",
    description:
      "Bosque esclerófilo y palma chilena. Trekking al cerro La Campana, el que subió Darwin en 1834.",
    highlights: ["Cerro La Campana", "Palma chilena", "Bosque esclerófilo"],
    priceFromCLP: 125000,
    tags: ["bosque", "trekking", "naturaleza"],
    landscapes: ["bosque-nativo", "parques"],
    capsuleName: "Cápsula La Campana",
    capsuleImage: cap("capsula-chiloe.jpg"),
    capsuleTagline: "Madera y cobre en el bosque de palma chilena.",
    capsuleDescription:
      "Cápsula entre palmares, con sendero privado al parque y tinaja de noche.",
    capsuleHighlights: ["Palma chilena", "Tinaja", "Parque nacional"],
    capsulePrice: 132000,
  },
  {
    slug: "santiago",
    name: "Santiago",
    region: "Centro",
    city: "Santiago",
    lat: -33.4489,
    lng: -70.6693,
    image: p("santiago.jpg"),
    gallery: [p("santiago.jpg"), p("mercado.jpg"), p("cajon.jpg")],
    youtubeStart: 2936,
    tagline: "Capital andina: museos, viñas del Maipo y cordillera a la vista.",
    description:
      "Barrio Lastarria, Mercado Central, cerro San Cristóbal y las viñas del Maipo a media hora.",
    highlights: ["Cerro San Cristóbal", "Lastarria", "Viña Concha y Toro"],
    priceFromCLP: 110000,
    tags: ["ciudad", "vino", "cultura"],
    landscapes: ["vinedos"],
    capsuleName: "Cápsula Maipo",
    capsuleImage: cap("capsula-interior.jpg"),
    capsuleTagline: "Interior de cobre y madera, con los Andes en el ventanal.",
    capsuleDescription:
      "Cápsula en el piedemonte santiaguino. Starlink, cocina smart y traslado a viñas.",
    capsuleHighlights: ["Vista Andes", "Viñas del Maipo", "Starlink"],
    capsulePrice: 162000,
  },
  {
    slug: "cajon-del-maipo",
    name: "Cajón del Maipo",
    region: "Centro",
    city: "San José de Maipo",
    lat: -33.642,
    lng: -70.354,
    image: p("cajon.jpg"),
    gallery: [p("cajon.jpg"), p("santiago.jpg")],
    tagline: "Río Maipo, glaciares y termas a una hora de Santiago.",
    description:
      "Quebrada andina con el Yeso, Embalse El Yeso, trekking y aguas termales. La montaña de la capital.",
    highlights: ["Embalse El Yeso", "Río Maipo", "Termas"],
    priceFromCLP: 145000,
    tags: ["montaña", "ríos", "aventura"],
    landscapes: ["rios", "nieve"],
    capsuleName: "Cápsula Yeso",
    capsuleImage: cap("capsula-interior.jpg"),
    capsuleTagline: "Cobre, madera y el ventanal abierto al Cajón.",
    capsuleDescription:
      "Cápsula de montaña con calefacción de alta cota, tinaja y vista al río.",
    capsuleHighlights: ["Vista Cajón", "Tinaja", "Glaciar cercano"],
    capsulePrice: 155000,
  },
  {
    slug: "farellones-valle-nevado",
    name: "Farellones y Valle Nevado",
    region: "Centro",
    city: "Lo Barnechea",
    lat: -33.354,
    lng: -70.297,
    image: p("valle-nevado.jpg"),
    gallery: [p("valle-nevado.jpg")],
    youtubeStart: 4156,
    tagline: "Nieve andina a 50 minutos de Santiago.",
    description:
      "Tres centros de ski en la misma cordillera: Valle Nevado, La Parva y El Colorado. Temporada de junio a octubre.",
    highlights: ["Valle Nevado", "Farellones", "Andes centrales"],
    priceFromCLP: 210000,
    tags: ["nieve", "ski", "montaña"],
    landscapes: ["nieve"],
    capsuleName: "Cápsula Valle Nevado",
    capsuleImage: cap("capsula-nieve.jpg"),
    capsuleTagline: "Cobre y vidrio sobre la terraza de nieve.",
    capsuleDescription:
      "Cápsula aislada para -15 °C, cama king y vista a las pistas. Ski-in cercano.",
    capsuleHighlights: ["Pistas", "Aislación polar", "Vista Andes"],
    capsulePrice: 225000,
  },
  {
    slug: "colchagua",
    name: "Colchagua",
    region: "Valle Central",
    city: "Santa Cruz",
    lat: -34.639,
    lng: -71.366,
    image: p("colchagua.jpg"),
    gallery: [p("colchagua.jpg")],
    tagline: "Carmenère, haciendas y el valle del vino chileno.",
    description:
      "Ruta del vino de Santa Cruz a Lolol. Viñas boutique, caballos y gastronomía de fundo.",
    highlights: ["Ruta del vino", "Santa Cruz", "Carmenère"],
    priceFromCLP: 145000,
    tags: ["vino", "campo", "gastronomía"],
    landscapes: ["vinedos"],
    capsuleName: "Cápsula VIK",
    capsuleImage: cap("capsula-colchagua.jpg"),
    capsuleTagline: "Cobre junto a Viña VIK, sobre las hileras de Millahue.",
    capsuleDescription:
      "Cápsula en el valle de Colchagua, cata en VIK, deck al atardecer y desayuno de fundo.",
    capsuleHighlights: ["Viña VIK", "Cata", "Atardecer"],
    capsulePrice: 152000,
  },
  {
    slug: "siete-tazas",
    name: "Siete Tazas",
    region: "Valle Central",
    city: "Molina",
    lat: -35.421,
    lng: -70.996,
    image: p("siete-tazas.jpg"),
    gallery: [p("siete-tazas.jpg")],
    tagline: "Pozones de basalto, saltos y bosque de robles.",
    description:
      "Parque Radal Siete Tazas: cascadas escalonadas, Velo de la Novia y senderos de bosque nativo.",
    highlights: ["Siete Tazas", "Velo de la Novia", "Bosque de roble"],
    priceFromCLP: 130000,
    tags: ["ríos", "bosque", "trekking"],
    landscapes: ["rios", "bosque-nativo", "parques"],
    capsuleName: "Cápsula Radal",
    capsuleImage: cap("capsula-rio.jpg"),
    capsuleTagline: "Cobre y madera junto al río de las tazas.",
    capsuleDescription:
      "Cápsula junto al bosque, con acceso a senderos y el sonido del río.",
    capsuleHighlights: ["Río", "Bosque nativo", "Cascadas"],
    capsulePrice: 140000,
  },
  {
    slug: "termas-de-chillan",
    name: "Termas de Chillán",
    region: "Valle Central",
    city: "Pinto",
    lat: -36.908,
    lng: -71.409,
    image: p("chillan.jpg"),
    gallery: [p("chillan.jpg")],
    tagline: "Volcán, nieve y pozones de agua termal.",
    description:
      "Centro de montaña al pie del Chillán: ski, termas y bosque. Invierno de nieve, verano de trekking.",
    highlights: ["Volcán Chillán", "Termas", "Ski"],
    priceFromCLP: 175000,
    tags: ["nieve", "volcán", "termas"],
    landscapes: ["nieve", "volcan"],
    capsuleName: "Cápsula Chillán",
    capsuleImage: cap("capsula-nieve.jpg"),
    capsuleTagline: "Cápsula de cobre en la nieve, con tinaja termal.",
    capsuleDescription:
      "Módulo de alta montaña, tinaja de agua volcánica y vista al cráter.",
    capsuleHighlights: ["Tinaja termal", "Nieve", "Volcán"],
    capsulePrice: 185000,
  },
  {
    slug: "saltos-del-laja",
    name: "Saltos del Laja",
    region: "Valle Central",
    city: "Cabrero",
    lat: -37.217,
    lng: -72.38,
    image: p("laja.jpg"),
    gallery: [p("laja.jpg")],
    tagline: "La cascada clásica del sur, a orilla de carretera.",
    description:
      "Cuatro saltos del río Laja. Parada icónica entre Santiago y el sur, con senderos y miradores.",
    highlights: ["Salto principal", "Río Laja", "Miradores"],
    priceFromCLP: 120000,
    tags: ["ríos", "naturaleza"],
    landscapes: ["rios"],
    capsuleName: "Cápsula Laja",
    capsuleImage: cap("capsula-rio.jpg"),
    capsuleTagline: "El rumor de la cascada desde la cama de cobre y vidrio.",
    capsuleDescription:
      "Cápsula junto al bosque del Laja, con deck hacia los saltos.",
    capsuleHighlights: ["Cascada", "Bosque", "Deck"],
    capsulePrice: 128000,
  },
  {
    slug: "concepcion",
    name: "Concepción",
    region: "Valle Central",
    city: "Concepción",
    lat: -36.827,
    lng: -73.05,
    image: p("concepcion.jpg"),
    gallery: [p("concepcion.jpg")],
    tagline: "Biobío, universidad y la puerta del sur húmedo.",
    description:
      "Capital del Biobío: río, costa de Tomé y Lota, bosque de la cordillera de Nahuelbuta a un rato.",
    highlights: ["Río Biobío", "Barrio universitario", "Costa del golfo"],
    priceFromCLP: 125000,
    tags: ["ciudad", "ríos", "cultura"],
    landscapes: ["rios"],
    capsuleName: "Cápsula Biobío",
    capsuleImage: cap("capsula-rio.jpg"),
    capsuleTagline: "Cobre y vidrio sobre la ribera del Biobío.",
    capsuleDescription:
      "Cápsula urbana-ribereña, con deck al río y acceso a la costa de Tomé.",
    capsuleHighlights: ["Río Biobío", "Ciudad", "Costa"],
    capsulePrice: 135000,
  },
  {
    slug: "pucon",
    name: "Pucón y Villarrica",
    region: "Araucanía y Lagos",
    city: "Pucón",
    lat: -39.2823,
    lng: -71.9545,
    image: p("villarrica.jpg"),
    gallery: [p("pucon.jpg"), p("termas.jpg"), p("villarrica.jpg")],
    youtubeStart: 2309,
    tagline: "Volcán Villarrica, termas y bosque de araucarias.",
    description:
      "Capital de la aventura en el sur: trekking al volcán, hidrospeed, termas geométricas y cultura mapuche.",
    highlights: ["Volcán Villarrica", "Termas Geométricas", "Lago Villarrica"],
    priceFromCLP: 160000,
    tags: ["aventura", "termas", "mapuche", "naturaleza"],
    landscapes: ["volcan", "lago", "bosque-nativo"],
    capsuleSlug: "capsula-araucaria",
    capsuleName: "Cápsula Villarrica",
    capsuleImage: cap("capsula-pucon.jpg"),
    capsuleTagline: "Frente al volcán Villarrica, con tinaja de cedro y araucarias.",
    capsuleDescription:
      "Madera, cobre y ventanal panorámico. Tinaja climatizada, cocina smart y acceso a senderos de araucarias.",
    capsuleHighlights: ["Tinaja", "Vista al volcán", "Bosque nativo"],
    capsulePrice: 172000,
    capacity: 3,
  },
  {
    slug: "puerto-varas",
    name: "Puerto Varas y Lago Llanquihue",
    region: "Araucanía y Lagos",
    city: "Puerto Varas",
    lat: -41.3195,
    lng: -72.9854,
    image: p("puerto-varas.jpg"),
    gallery: [p("puerto-varas.jpg"), p("osorno.jpg")],
    youtubeStart: 733,
    tagline: "Lago Llanquihue y los volcanes Osorno y Calbuco.",
    description:
      "Arquitectura alemana, kuchen, kayak al atardecer y salto Petrohué a los pies del Osorno.",
    highlights: ["Volcán Osorno", "Saltos del Petrohué", "Frutillar"],
    priceFromCLP: 150000,
    tags: ["lagos", "naturaleza", "gastronomía", "descanso"],
    landscapes: ["lago", "volcan"],
    capsuleName: "Cápsula Llanquihue",
    capsuleImage: cap("capsula-pucon.jpg"),
    capsuleTagline: "Cobre sobre el lago, con el Osorno reflejado al amanecer.",
    capsuleDescription:
      "Cápsula en orilla de Llanquihue, kayak incluido y kuchen de bienvenida.",
    capsuleHighlights: ["Orilla del lago", "Osorno", "Kayak"],
    capsulePrice: 168000,
  },
  {
    slug: "osorno",
    name: "Osorno",
    region: "Araucanía y Lagos",
    city: "Osorno",
    lat: -40.574,
    lng: -73.135,
    image: p("osorno.jpg"),
    gallery: [p("osorno.jpg"), p("puerto-varas.jpg")],
    tagline: "Volcanes, campo huaso y puerta a los lagos.",
    description:
      "Ciudad ganadera con vista a volcanes. Base para Puntiagudo, Puyehue y el lago Rupanco.",
    highlights: ["Volcán Puntiagudo", "Campo", "Puyehue"],
    priceFromCLP: 140000,
    tags: ["volcán", "campo", "lagos"],
    landscapes: ["volcan"],
    capsuleName: "Cápsula Puntiagudo",
    capsuleImage: cap("capsula-pucon.jpg"),
    capsuleTagline: "Madera y cobre con el perfil del Puntiagudo.",
    capsuleDescription:
      "Cápsula de campo, tinaja y cabalgata opcional hacia Puyehue.",
    capsuleHighlights: ["Volcán", "Campo", "Tinaja"],
    capsulePrice: 150000,
  },
  {
    slug: "lago-rupanco",
    name: "Lago Rupanco",
    region: "Araucanía y Lagos",
    city: "Puerto Octay",
    lat: -40.822,
    lng: -72.5,
    image: p("rupanco.jpg"),
    gallery: [p("rupanco.jpg")],
    tagline: "El lago quieto, entre volcanes y bosque siempreverde.",
    description:
      "Orilla menos transitada que Llanquihue. Pesca, kayak y termas de Puyehue a un rato.",
    highlights: ["Orilla silvestre", "Pesca", "Bosque"],
    priceFromCLP: 148000,
    tags: ["lagos", "descanso", "naturaleza"],
    landscapes: ["lago", "bosque-nativo"],
    capsuleName: "Cápsula Rupanco",
    capsuleImage: cap("capsula-pucon.jpg"),
    capsuleTagline: "Cápsula sobre el agua quieta del Rupanco.",
    capsuleDescription:
      "Módulo en bahía privada, bosque a la espalda y volcán al frente.",
    capsuleHighlights: ["Bahía privada", "Bosque", "Kayak"],
    capsulePrice: 158000,
  },
  {
    slug: "chiloe",
    name: "Chiloé",
    region: "Araucanía y Lagos",
    city: "Castro",
    lat: -42.4825,
    lng: -73.764,
    image: p("palafitos.jpg"),
    gallery: [p("castro.jpg"), p("iglesia-castro.jpg"), p("palafitos.jpg")],
    youtubeStart: 890,
    tagline: "Iglesias de madera, palafitos y mitología del archipiélago.",
    description:
      "Curanto en hoyo, iglesias UNESCO, pingüinos de Puñihuil y la niebla que cubre los palafitos de Castro.",
    highlights: ["Palafitos de Castro", "Curanto", "Pingüineras de Puñihuil"],
    priceFromCLP: 145000,
    tags: ["cultura", "gastronomía", "isla", "naturaleza"],
    landscapes: ["bosque-nativo", "playa"],
    capsuleSlug: "capsula-palafito",
    capsuleName: "Cápsula Valdiviana",
    capsuleImage: cap("capsula-chiloe.jpg"),
    capsuleTagline: "Inmersa en la selva valdiviana de Chiloé.",
    capsuleDescription:
      "Cápsula entre musgo, nalca y bosque siempreverde. Calefacción por bomba de calor, lana chilota y el silencio del sotobosque.",
    capsuleHighlights: ["Selva valdiviana", "Lana chilota", "Bosque siempreverde"],
    capsulePrice: 138000,
  },
  {
    slug: "capillas-de-marmol",
    name: "Capillas de Mármol",
    region: "Patagonia",
    city: "Puerto Río Tranquilo",
    lat: -46.605,
    lng: -72.641,
    image: p("marmol.jpg"),
    gallery: [p("marmol.jpg")],
    youtubeStart: 1693,
    tagline: "Catedrales de mármol sobre el lago General Carrera.",
    description:
      "Cavernas azules en el lago más grande de Chile. Kayak al amanecer y la Carretera Austral como umbral.",
    highlights: ["Capilla de Mármol", "Lago General Carrera", "Kayak"],
    priceFromCLP: 200000,
    tags: ["lagos", "patagonia", "aventura"],
    landscapes: ["lago"],
    capsuleName: "Cápsula Mármol",
    capsuleImage: cap("capsula-paine.jpg"),
    capsuleTagline: "Cobre y vidrio frente al mármol turquesa.",
    capsuleDescription:
      "Cápsula en orilla del General Carrera, kayak a las capillas al amanecer.",
    capsuleHighlights: ["Lago turquesa", "Kayak", "Mármol"],
    capsulePrice: 210000,
  },
  {
    slug: "futaleufu",
    name: "Futaleufú",
    region: "Patagonia",
    city: "Futaleufú",
    lat: -43.1856,
    lng: -71.8664,
    image: p("futaleufu.jpg"),
    gallery: [p("futaleufu.jpg"), p("coyhaique.jpg")],
    tagline: "El río de aguas blancas más famoso del hemisferio sur.",
    description:
      "Rafting clase V, bosque siempreverde y pueblo de montaña en la frontera. El corazón líquido de la Austral.",
    highlights: ["Río Futaleufú", "Rafting", "Bosque"],
    priceFromCLP: 185000,
    tags: ["ríos", "aventura", "patagonia"],
    landscapes: ["rios", "bosque-nativo"],
    capsuleName: "Cápsula Futaleufú",
    capsuleImage: cap("capsula-rio.jpg"),
    capsuleTagline: "Cobre junto al turquesa del Fu.",
    capsuleDescription:
      "Cápsula sobre el valle, con el sonido del río y salida de rafting al amanecer.",
    capsuleHighlights: ["Río clase V", "Bosque", "Rafting"],
    capsulePrice: 195000,
  },
  {
    slug: "carretera-austral",
    name: "Carretera Austral",
    region: "Patagonia",
    city: "Coyhaique",
    lat: -45.575,
    lng: -72.066,
    image: p("coyhaique.jpg"),
    gallery: [p("coyhaique.jpg"), p("marmol.jpg")],
    youtubeStart: 1693,
    tagline: "La ruta más salvaje de Chile, de bosque a glaciar.",
    description:
      "De Puerto Montt a Villa O'Higgins: hanging glaciers, Queulat, caletas y el sur sin prisa.",
    highlights: ["Parque Queulat", "Coyhaique", "Glaciares colgantes"],
    priceFromCLP: 190000,
    tags: ["ruta", "bosque", "patagonia"],
    landscapes: ["bosque-nativo", "rios"],
    capsuleName: "Cápsula Austral",
    capsuleImage: cap("capsula-rio.jpg"),
    capsuleTagline: "Madera y cobre en un claro de la ruta 7.",
    capsuleDescription:
      "Cápsula de paso largo, con calefacción patagónica y deck al bosque.",
    capsuleHighlights: ["Ruta 7", "Bosque", "Queulat"],
    capsulePrice: 188000,
  },
  {
    slug: "torres-del-paine",
    name: "Torres del Paine",
    region: "Patagonia",
    city: "Puerto Natales",
    lat: -51.2538,
    lng: -72.3445,
    image: p("paine.jpg"),
    gallery: [p("paine-unsplash.jpg"), p("paine.jpg")],
    youtubeStart: 64,
    tagline: "Granito, vientos y el parque más icónico de Sudamérica.",
    description:
      "Torres, Cuernos, Grey y el W. Base en Puerto Natales, glamping de lujo y trekking de clase mundial.",
    highlights: ["Base Torres", "Glaciar Grey", "Laguna Azul"],
    priceFromCLP: 280000,
    tags: ["patagonia", "trekking", "naturaleza", "aventura"],
    landscapes: ["parques", "lago", "nieve"],
    capsuleSlug: "capsula-paine",
    capsuleName: "Cápsula Torres del Paine",
    capsuleImage: cap("capsula-paine.jpg"),
    capsuleTagline: "Granito de las Torres desde la cama, con calefacción de alta cota.",
    capsuleDescription:
      "Cápsula de lujo aislada para viento patagónico. Panorámica a las Torres, ducha de presión y transferencia al parque.",
    capsuleHighlights: ["Vista Torres", "Aislación térmica", "Transfer al parque"],
    capsulePrice: 248000,
  },
  {
    slug: "rapa-nui",
    name: "Rapa Nui",
    region: "Rapa Nui",
    city: "Hanga Roa",
    lat: -27.1127,
    lng: -109.3497,
    image: p("tongariki.jpg"),
    gallery: [p("rano-raraku.jpg"), p("easter.jpg"), p("tongariki.jpg")],
    youtubeStart: 1384,
    tagline: "Moai, cráteres y el ombligo del mundo en el Pacífico.",
    description:
      "Parque Nacional Rapa Nui, ahu Tongariki al amanecer, Rano Kau y cultura ancestral polinésica.",
    highlights: ["Tongariki", "Rano Raraku", "Orongo"],
    priceFromCLP: 320000,
    tags: ["cultura", "isla", "patrimonio", "descanso"],
    landscapes: ["playa"],
    capsuleName: "Cápsula Tongariki",
    capsuleImage: cap("capsula-playa.jpg"),
    capsuleTagline: "Cobre y vidrio en el Pacífico, lejos de todo.",
    capsuleDescription:
      "Cápsula cerca de Hanga Roa, con amanecer en Tongariki y guía rapanui.",
    capsuleHighlights: ["Isla", "Amanecer moai", "Pacífico"],
    capsulePrice: 285000,
  },
  {
    slug: "juan-fernandez",
    name: "Archipiélago de Juan Fernández",
    region: "Pacífico",
    city: "San Juan Bautista",
    lat: -33.636,
    lng: -78.838,
    image: p("juan-fernandez.jpg"),
    gallery: [p("juan-fernandez.jpg")],
    tagline: "Robinson Crusoe, bosque endémico y el Pacífico vacío.",
    description:
      "Isla de endemismo extremo, langosta y bahías verdes. Un archipiélago chileno a 670 km del continente.",
    highlights: ["Robinson Crusoe", "Bosque endémico", "Bahía Cumberland"],
    priceFromCLP: 300000,
    tags: ["isla", "bosque", "playa"],
    landscapes: ["bosque-nativo", "playa", "parques"],
    capsuleName: "Cápsula Robinson",
    capsuleImage: cap("capsula-juan-fernandez.jpg"),
    capsuleTagline: "Palafito de cobre en una caleta del archipiélago.",
    capsuleDescription:
      "Cápsula sobre pilotes, bosque de luma y el Pacífico de Juan Fernández.",
    capsuleHighlights: ["Isla", "Bosque endémico", "Caleta"],
    capsulePrice: 320000,
  },
  {
    slug: "antartica",
    name: "Antártica",
    region: "Antártica",
    city: "Villa Las Estrellas",
    lat: -62.201,
    lng: -58.964,
    image: p("antartica.jpg"),
    gallery: [p("antartica.jpg")],
    tagline: "Hielo, bases chilenas y el fin del mapa.",
    description:
      "Peninsula Antártica e isla Rey Jorge. Villa Las Estrellas, glaciares y la logística más remota de Mapucoin.",
    highlights: ["Villa Las Estrellas", "Glaciares", "Canal de Drake"],
    priceFromCLP: 780000,
    tags: ["nieve", "expedición", "remoto"],
    landscapes: ["nieve"],
    capsuleName: "Cápsula Polar",
    capsuleImage: cap("capsula-antartica.jpg"),
    capsuleTagline: "Cobre y vidrio en la orilla de hielo.",
    capsuleDescription:
      "Cápsula polar con aislación extrema, climatización y vista a glaciares. Operación estacional.",
    capsuleHighlights: ["Hielo", "Aislación polar", "Base chilena"],
    capsulePrice: 890000,
  },
];

export const destinations: CatalogItem[] = [
  ...seeds.map((s) => ({
    slug: s.slug,
    kind: "place" as const,
    name: s.name,
    region: s.region,
    city: s.city,
    lat: s.lat,
    lng: s.lng,
    image: s.image,
    gallery: s.gallery,
    youtube: s.youtubeStart != null ? CHILE_FILM : undefined,
    youtubeStart: s.youtubeStart,
    tagline: s.tagline,
    description: s.description,
    highlights: s.highlights,
    priceFromCLP: s.priceFromCLP,
    tags: s.tags,
    landscapes: s.landscapes,
  })),
  ...nationalParks,
];

export const capsules: CatalogItem[] = seeds.map((s) => ({
  slug: s.capsuleSlug || `capsula-${s.slug}`,
  kind: "capsule",
  name: s.capsuleName,
  region: s.region,
  city: s.city,
  lat: Number((s.lat + 0.018).toFixed(4)),
  lng: Number((s.lng - 0.022).toFixed(4)),
  image: `/images/capsulas/${s.slug}.jpg`,
  tagline: s.capsuleTagline,
  description: s.capsuleDescription,
  highlights: s.capsuleHighlights,
  priceFromCLP: s.capsulePrice,
  nightsHint: 1,
  capacity: s.capacity || 2,
  tags: ["tecnología", "cobre", "vidrio", ...s.landscapes],
  landscapes: s.landscapes,
  placeSlug: s.slug,
}));

export const gastronomy: CatalogItem[] = [
  {
    slug: "curanto-chilote",
    kind: "food",
    name: "Curanto en hoyo",
    region: "Araucanía y Lagos",
    city: "Castro",
    lat: -42.48,
    lng: -73.76,
    image: p("curanto-hoyo.jpg"),
    tagline: "Mariscos, carne y milcao cocidos bajo tierra con nalca.",
    description:
      "Ritual chilote: hoyo, piedras calientes, chapaleles y mariscos del canal. Experiencia con familia local.",
    highlights: ["Cocción ancestral", "Mariscos del canal", "Gastronomía compartida"],
    priceFromCLP: 28000,
    durationHours: 3,
    tags: ["chilote", "mariscos", "ancestral"],
    landscapes: ["bosque-nativo"],
    placeSlug: "chiloe",
  },
  {
    slug: "asado-patagonico",
    kind: "food",
    name: "Asado patagónico al palo",
    region: "Patagonia",
    city: "Puerto Natales",
    lat: -51.73,
    lng: -72.5,
    image: p("asado-patagonico.jpg"),
    tagline: "Cordero magallánico a fuego lento, con calafate.",
    description:
      "Cordero de estancia, chimichurri de merken y vino del Maule. Cena a la luz del atardecer austral.",
    highlights: ["Cordero al palo", "Calafate", "Estancia"],
    priceFromCLP: 42000,
    durationHours: 3,
    tags: ["patagonia", "carne", "vino"],
    landscapes: ["lago"],
    placeSlug: "torres-del-paine",
  },
  {
    slug: "cocina-mapuche",
    kind: "food",
    name: "Cocina mapuche de fogón",
    region: "Araucanía y Lagos",
    city: "Pucón",
    lat: -39.29,
    lng: -71.94,
    image: p("cocina-mapuche.jpg"),
    tagline: "Merkén, catuto, yuyo y muday en ruka.",
    description:
      "Almuerzo en ruka con productoras locales. Relato de territorio, hierbas del volcán y pan de trigo candeal.",
    highlights: ["Ruka", "Merkén", "Productoras locales"],
    priceFromCLP: 24000,
    durationHours: 2,
    tags: ["mapuche", "ancestral", "vegetal"],
    landscapes: ["volcan", "bosque-nativo"],
    placeSlug: "pucon",
  },
  {
    slug: "mariscal-valpo",
    kind: "food",
    name: "Mariscal del puerto",
    region: "Centro",
    city: "Valparaíso",
    lat: -33.036,
    lng: -71.628,
    image: p("mariscal-puerto.jpg"),
    tagline: "Locos, machas y erizos recién desembarcados.",
    description:
      "Caleta con vista a los cerros. Machas a la parmesana, ceviche de reineta y vino del Casablanca.",
    highlights: ["Caleta", "Machas", "Casablanca"],
    priceFromCLP: 22000,
    durationHours: 2,
    tags: ["mariscos", "puerto", "vino"],
    landscapes: ["playa"],
    placeSlug: "valparaiso",
  },
  {
    slug: "pisco-elqui",
    kind: "food",
    name: "Ruta del pisco y el vino",
    region: "Norte Chico",
    city: "Pisco Elqui",
    lat: -30.126,
    lng: -70.495,
    image: p("pisco-sour.jpg"),
    tagline: "Destilerías de moscatel y viñas de altura.",
    description:
      "Tres paradas: destilería familiar, viña de altura y pisco sour con limón de pica.",
    highlights: ["Destilería", "Cata", "Pisco sour"],
    priceFromCLP: 32000,
    durationHours: 4,
    tags: ["pisco", "vino", "cata"],
    landscapes: ["vinedos"],
    placeSlug: "valle-del-elqui",
  },
  {
    slug: "mercado-central",
    kind: "food",
    name: "Mercado Central y Lastarria",
    region: "Centro",
    city: "Santiago",
    lat: -33.437,
    lng: -70.651,
    image: p("paila-marina.jpg"),
    tagline: "Paila marina, empanadas de horno y bar de vinos.",
    description:
      "Recorrido entre pescaderías, pastel de choclo y un cierre en Lastarria con carmenère.",
    highlights: ["Paila marina", "Empanadas", "Carmenère"],
    priceFromCLP: 18000,
    durationHours: 3,
    tags: ["ciudad", "mercado", "vino"],
    landscapes: ["vinedos"],
    placeSlug: "santiago",
  },
  {
    slug: "mote-con-huesillos",
    kind: "food",
    name: "Mote con huesillos",
    region: "Centro",
    city: "Santiago",
    lat: -33.437,
    lng: -70.65,
    image: p("mote-huesillos.jpg"),
    tagline: "Trigo mote, durazno seco y miel de caña, bien frío.",
    description:
      "El vaso del verano santiaguino: huesillos hidratados, mote y un jarabe de chancaca. Se toma en feria, plaza o sombra de tilo.",
    highlights: ["Huesillos", "Mote", "Chancaca"],
    priceFromCLP: 3500,
    durationHours: 1,
    tags: ["dulce", "verano", "tradicional"],
    landscapes: ["vinedos"],
    placeSlug: "santiago",
  },
  {
    slug: "pastelitos-curacavi",
    kind: "food",
    name: "Pastelitos de Curacaví",
    region: "Centro",
    city: "Curacaví",
    lat: -33.401,
    lng: -71.133,
    image: p("pastelitos-curacavi.jpg"),
    tagline: "Hojaldre frito, manjar y azúcar flor de la Ruta 68.",
    description:
      "El clásico de la detención en Curacaví: masa crujiente, relleno de manjar y un polvo de azúcar. Café de olla al lado.",
    highlights: ["Manjar", "Hojaldre", "Ruta 68"],
    priceFromCLP: 4500,
    durationHours: 1,
    tags: ["dulce", "tradicional", "viaje"],
    landscapes: ["vinedos"],
    placeSlug: "santiago",
  },
  {
    slug: "sopaipillas",
    kind: "food",
    name: "Sopaipillas",
    region: "Centro",
    city: "Santiago",
    lat: -33.448,
    lng: -70.669,
    image: p("sopaipillas.jpg"),
    tagline: "Zapallo frito: con pebre cuando sale el sol, con chancaca cuando llueve.",
    description:
      "Disco de zapallo en aceite caliente. En invierno van pasadas, en verano con pebre. La calle chilena en un bocado.",
    highlights: ["Zapallo", "Pebre", "Chancaca"],
    priceFromCLP: 2500,
    durationHours: 1,
    tags: ["calle", "tradicional", "zapallo"],
    landscapes: ["vinedos"],
    placeSlug: "santiago",
  },
  {
    slug: "empanadas-de-pino",
    kind: "food",
    name: "Empanadas de pino",
    region: "Centro",
    city: "Santiago",
    lat: -33.44,
    lng: -70.655,
    image: p("empanadas-pino.jpg"),
    tagline: "Pino de carne, cebolla, huevo, aceituna y un horno de barro.",
    description:
      "La empanada de fiestas patrias y de domingo. Masa de horno, pino jugoso y el ritual de no morder la aceituna de sorpresa.",
    highlights: ["Pino", "Horno", "Aceituna"],
    priceFromCLP: 4000,
    durationHours: 1,
    tags: ["tradicional", "carne", "fiestas"],
    landscapes: ["vinedos"],
    placeSlug: "santiago",
  },
  {
    slug: "pastel-de-choclo",
    kind: "food",
    name: "Pastel de choclo",
    region: "Valle Central",
    city: "Santa Cruz",
    lat: -34.639,
    lng: -71.366,
    image: p("pastel-choclo.jpg"),
    tagline: "Choclo molido, pino, pollo y un azúcar que carameliza al horno.",
    description:
      "Cazuela de greda, pasta de choclo dulce y pino debajo. El almuerzo de fundo del Valle Central, con ensalada chilena.",
    highlights: ["Choclo", "Greda", "Pino"],
    priceFromCLP: 12000,
    durationHours: 2,
    tags: ["choclo", "campo", "tradicional"],
    landscapes: ["vinedos"],
    placeSlug: "colchagua",
  },
  {
    slug: "humitas",
    kind: "food",
    name: "Humitas",
    region: "Valle Central",
    city: "Santa Cruz",
    lat: -34.64,
    lng: -71.37,
    image: p("humitas.jpg"),
    tagline: "Choclo tierno envuelto en su propia hoja, al vapor.",
    description:
      "Temporada de verano: choclo rallado, albahaca y un amarre de paja. Se comen con ensalada de tomate y ají.",
    highlights: ["Choclo", "Hoja", "Verano"],
    priceFromCLP: 8000,
    durationHours: 1,
    tags: ["choclo", "verano", "tradicional"],
    landscapes: ["vinedos"],
    placeSlug: "colchagua",
  },
  {
    slug: "caldillo-de-congrio",
    kind: "food",
    name: "Caldillo de congrio",
    region: "Centro",
    city: "Valparaíso",
    lat: -33.036,
    lng: -71.63,
    image: p("caldillo-congrio.jpg"),
    tagline: "El caldo que Neruda dejó escrito: congrio, papa y cilantro.",
    description:
      "Sopa de congrio dorado, papa, tomate y un fondo de mar. Caleta, mantel de hule y un blanco de Casablanca.",
    highlights: ["Congrio", "Papa", "Cilantro"],
    priceFromCLP: 16000,
    durationHours: 2,
    tags: ["mariscos", "sopa", "puerto"],
    landscapes: ["playa"],
    placeSlug: "valparaiso",
  },
  {
    slug: "pastel-de-centolla",
    kind: "food",
    name: "Pastel de centolla",
    region: "Patagonia",
    city: "Puerto Natales",
    lat: -51.73,
    lng: -72.51,
    image: p("pastel-centolla.jpg"),
    tagline: "Centolla magallánica gratinada, el lujo frío del sur.",
    description:
      "Carne de centolla, crema y un gratinado. Se come en estancia o caleta, con un blanco extremo y viento en la ventana.",
    highlights: ["Centolla", "Gratinado", "Magallanes"],
    priceFromCLP: 28000,
    durationHours: 2,
    tags: ["mariscos", "patagonia", "lujo"],
    landscapes: ["lago"],
    placeSlug: "torres-del-paine",
  },
  {
    slug: "mariscal",
    kind: "food",
    name: "Mariscal",
    region: "Centro",
    city: "Valparaíso",
    lat: -33.038,
    lng: -71.627,
    image: p("mariscal.jpg"),
    tagline: "Mariscos fríos, limón y el golpe del Pacífico.",
    description:
      "Mejillones, almejas, piure, camarón y un hielo que no perdona. El aperitivo de caleta antes del plato caliente.",
    highlights: ["Frío", "Limón", "Caleta"],
    priceFromCLP: 14000,
    durationHours: 1,
    tags: ["mariscos", "caleta", "frío"],
    landscapes: ["playa"],
    placeSlug: "valparaiso",
  },
  {
    slug: "cazuela",
    kind: "food",
    name: "Cazuela de ave",
    region: "Centro",
    city: "Santiago",
    lat: -33.45,
    lng: -70.67,
    image: p("cazuela.jpg"),
    tagline: "Caldo, zapallo, choclo, papa y un presón de gallina.",
    description:
      "El almuerzo de casa chilena. Cada cucharada trae un trozo distinto. Se sirve humeante, con cilantro y ají de color.",
    highlights: ["Zapallo", "Choclo", "Caldo"],
    priceFromCLP: 9000,
    durationHours: 1,
    tags: ["sopa", "casa", "tradicional"],
    landscapes: ["vinedos"],
    placeSlug: "santiago",
  },
  {
    slug: "charquican",
    kind: "food",
    name: "Charquicán",
    region: "Centro",
    city: "Santiago",
    lat: -33.445,
    lng: -70.66,
    image: p("charquican.jpg"),
    tagline: "Zapallo, papa, charqui y un huevo frito encima.",
    description:
      "Guiso espeso de verdura y carne seca. Plato de invierno y de campo, con ají y cilantro.",
    highlights: ["Zapallo", "Charqui", "Huevo frito"],
    priceFromCLP: 8500,
    durationHours: 1,
    tags: ["guiso", "campo", "tradicional"],
    landscapes: ["vinedos"],
    placeSlug: "santiago",
  },
  {
    slug: "porotos-granados",
    kind: "food",
    name: "Porotos granados",
    region: "Valle Central",
    city: "Santa Cruz",
    lat: -34.638,
    lng: -71.365,
    image: p("porotos-granados.jpg"),
    tagline: "Poroto, choclo, zapallo y albahaca de verano.",
    description:
      "El guiso de febrero. Porotos maduros, mazamorra de choclo y un aceite de color. Se come con ensalada chilena.",
    highlights: ["Porotos", "Choclo", "Albahaca"],
    priceFromCLP: 8000,
    durationHours: 1,
    tags: ["verano", "porotos", "campo"],
    landscapes: ["vinedos"],
    placeSlug: "colchagua",
  },
  {
    slug: "chorrillana",
    kind: "food",
    name: "Chorrillana",
    region: "Centro",
    city: "Valparaíso",
    lat: -33.047,
    lng: -71.613,
    image: p("chorrillana.jpg"),
    tagline: "Papas fritas, carne, cebolla y huevos, para el cerro.",
    description:
      "La fuente de Valparaíso. Se comparte con copa de pipeño o una cerveza, después de subir el Alegre a pie.",
    highlights: ["Papas", "Carne", "Cerro"],
    priceFromCLP: 15000,
    durationHours: 2,
    tags: ["puerto", "compartir", "noche"],
    landscapes: ["playa"],
    placeSlug: "valparaiso",
  },
  {
    slug: "completo",
    kind: "food",
    name: "Completo",
    region: "Centro",
    city: "Santiago",
    lat: -33.437,
    lng: -70.648,
    image: p("completo.jpg"),
    tagline: "Vienesa, palta, tomate y mayo: el bocado de la calle chilena.",
    description:
      "El hot dog de Chile. En su versión italiano lleva palta, tomate y mayonesa. Se come de pie, de noche, en el centro.",
    highlights: ["Palta", "Tomate", "Vienesa"],
    priceFromCLP: 4500,
    durationHours: 1,
    tags: ["calle", "tradicional", "noche"],
    landscapes: ["vinedos"],
    placeSlug: "santiago",
  },
  {
    slug: "choripan",
    kind: "food",
    name: "Choripán",
    region: "Centro",
    city: "Santiago",
    lat: -33.452,
    lng: -70.672,
    image: p("choripan.jpg"),
    tagline: "Chorizo a la parrilla, marraqueta y pebre.",
    description:
      "El asado en un pan. Chorizo marcado, marraqueta tostada y pebre o ají. Aparece en fondas, ferias y domingos.",
    highlights: ["Chorizo", "Marraqueta", "Pebre"],
    priceFromCLP: 4000,
    durationHours: 1,
    tags: ["parrilla", "calle", "tradicional"],
    landscapes: ["vinedos"],
    placeSlug: "santiago",
  },
  {
    slug: "pastel-de-jaiba",
    kind: "food",
    name: "Pastel de jaiba",
    region: "Centro",
    city: "Valparaíso",
    lat: -33.039,
    lng: -71.626,
    image: p("pastel-jaiba.jpg"),
    tagline: "Jaiba gratinada, queso y un fondo de mar.",
    description:
      "Carne de jaiba, pan remojado y queso al horno. El plato de caleta cuando el Pacífico está bravo.",
    highlights: ["Jaiba", "Queso", "Horno"],
    priceFromCLP: 16000,
    durationHours: 2,
    tags: ["mariscos", "puerto", "horno"],
    landscapes: ["playa"],
    placeSlug: "valparaiso",
  },
  {
    slug: "cancato",
    kind: "food",
    name: "Cancato",
    region: "Araucanía y Lagos",
    city: "Castro",
    lat: -42.482,
    lng: -73.764,
    image: p("cancato.jpg"),
    tagline: "Salmón o sierra abiertos, longaniza, queso y tomate al horno.",
    description:
      "El horno chilote: un pescado abierto, longaniza, queso y tomate. Se comparte en la mesa, con pan amasado.",
    highlights: ["Salmón", "Longaniza", "Horno"],
    priceFromCLP: 18000,
    durationHours: 2,
    tags: ["chilote", "pescado", "horno"],
    landscapes: ["bosque-nativo"],
    placeSlug: "chiloe",
  },
  {
    slug: "pan-amasado",
    kind: "food",
    name: "Pan amasado con pebre",
    region: "Valle Central",
    city: "Santa Cruz",
    lat: -34.641,
    lng: -71.368,
    image: p("pan-amasado.jpg"),
    tagline: "Pan de campo, recién salido del horno, y pebre de tomate.",
    description:
      "La entrada del fundo. Pan amasado caliente, pebre con cilantro y ají, y un vaso de pipeño si es domingo.",
    highlights: ["Horno de barro", "Pebre", "Campo"],
    priceFromCLP: 4500,
    durationHours: 1,
    tags: ["pan", "campo", "tradicional"],
    landscapes: ["vinedos"],
    placeSlug: "colchagua",
  },
  {
    slug: "porotos-con-riendas",
    kind: "food",
    name: "Porotos con riendas",
    region: "Valle Central",
    city: "Santa Cruz",
    lat: -34.637,
    lng: -71.364,
    image: p("porotos-riendas.jpg"),
    tagline: "Porotos, fideos, zapallo y longaniza.",
    description:
      "El guiso de invierno del Valle Central. Las riendas son los fideos. Se sirve con ají y una ensalada chilena.",
    highlights: ["Porotos", "Fideos", "Longaniza"],
    priceFromCLP: 8500,
    durationHours: 1,
    tags: ["guiso", "invierno", "campo"],
    landscapes: ["vinedos"],
    placeSlug: "colchagua",
  },
  {
    slug: "plateada",
    kind: "food",
    name: "Plateada",
    region: "Valle Central",
    city: "Santa Cruz",
    lat: -34.642,
    lng: -71.37,
    image: p("plateada.jpg"),
    tagline: "Malaya braseada, cebolla, zanahoria y papa.",
    description:
      "Horas de horno o de olla. La carne se deshace y el jugo queda para el puré. Almuerzo de domingo en el campo.",
    highlights: ["Malaya", "Horno", "Puré"],
    priceFromCLP: 14000,
    durationHours: 2,
    tags: ["carne", "domingo", "campo"],
    landscapes: ["vinedos"],
    placeSlug: "colchagua",
  },
  {
    slug: "kuchen-de-frambuesa",
    kind: "food",
    name: "Kuchen de frambuesa",
    region: "Araucanía y Lagos",
    city: "Puerto Varas",
    lat: -41.319,
    lng: -72.985,
    image: p("kuchen-sur.jpg"),
    tagline: "Masa alemana del lago y frambuesa del sur.",
    description:
      "La once de Puerto Varas y Frutillar. Kuchen de frambuesa, murta o manzana, con café de grano.",
    highlights: ["Frambuesa", "Once", "Lago"],
    priceFromCLP: 5500,
    durationHours: 1,
    tags: ["dulce", "sur", "once"],
    landscapes: ["lago"],
    placeSlug: "puerto-varas",
  },
  {
    slug: "milcao",
    kind: "food",
    name: "Milcao",
    region: "Araucanía y Lagos",
    city: "Castro",
    lat: -42.479,
    lng: -73.762,
    image: p("milcao.jpg"),
    tagline: "Papa rallada y papa cocida, frita o al curanto.",
    description:
      "El pan de papa chilote. Crudo y cocido en la misma masa, con chicharrones si la casa los tiene. Sale del curanto o de la sartén.",
    highlights: ["Papa", "Chilote", "Frito"],
    priceFromCLP: 4000,
    durationHours: 1,
    tags: ["chilote", "papa", "tradicional"],
    landscapes: ["bosque-nativo"],
    placeSlug: "chiloe",
  },
  {
    slug: "palta-reina",
    kind: "food",
    name: "Palta reina",
    region: "Centro",
    city: "Santiago",
    lat: -33.442,
    lng: -70.648,
    image: p("palta-reina.jpg"),
    tagline: "Palta rellena de pollo, mayo y un limón.",
    description:
      "Entrada de restaurante chileno desde hace décadas. Media palta, pollo deshilachado y mayonesa.",
    highlights: ["Palta", "Pollo", "Mayonesa"],
    priceFromCLP: 9000,
    durationHours: 1,
    tags: ["entrada", "palta", "ciudad"],
    landscapes: ["vinedos"],
    placeSlug: "santiago",
  },
  {
    slug: "trucha-a-la-mantequilla",
    kind: "food",
    name: "Trucha a la mantequilla",
    region: "Araucanía y Lagos",
    city: "Futaleufú",
    lat: -43.184,
    lng: -71.867,
    image: p("trucha-frita.jpg"),
    tagline: "Trucha del río, mantequilla y limón.",
    description:
      "El almuerzo de los ríos del sur. Trucha recién pescada, mantequilla avellana y papas. Se come mirando el agua.",
    highlights: ["Trucha", "Río", "Mantequilla"],
    priceFromCLP: 15000,
    durationHours: 2,
    tags: ["rio", "pescado", "sur"],
    landscapes: ["rios"],
    placeSlug: "futaleufu",
  },
  {
    slug: "patasca",
    kind: "food",
    name: "Patasca",
    region: "Norte Grande",
    city: "San Pedro de Atacama",
    lat: -22.91,
    lng: -68.2,
    image: p("patasca.jpg"),
    tagline: "Maíz mote, carne y el caldo del altiplano.",
    description:
      "Sopa andina de maíz pelado y carne, comida de altura y de frío. En el norte se toma humeante, con ají.",
    highlights: ["Maíz", "Altura", "Caldo"],
    priceFromCLP: 8000,
    durationHours: 1,
    tags: ["andino", "sopa", "desierto"],
    landscapes: ["desierto"],
    placeSlug: "san-pedro-de-atacama",
  },
  {
    slug: "marraqueta-palta-pebre",
    kind: "food",
    name: "Marraqueta, palta y pebre",
    region: "Patagonia",
    city: "Puerto Natales",
    lat: -51.728,
    lng: -72.506,
    image: p("marraqueta-palta.jpg"),
    tagline: "El almuerzo de sendero: pan, palta y pebre.",
    description:
      "Lo que cabe en la mochila y en el refugio. Marraqueta, palta machacada y pebre. La once chilena cuando no hay cocina.",
    highlights: ["Marraqueta", "Palta", "Pebre"],
    priceFromCLP: 4000,
    durationHours: 1,
    tags: ["sendero", "pan", "once"],
    landscapes: ["parques"],
    placeSlug: "torres-del-paine",
  },
  {
    slug: "pisco-sour",
    kind: "food",
    name: "Pisco sour",
    region: "Norte Chico",
    city: "Pisco Elqui",
    lat: -30.12,
    lng: -70.49,
    image: p("vaso-pisco-sour.jpg"),
    tagline: "Pisco, limón de Pica, azúcar y espuma.",
    description:
      "El trago de Chile. En el Elqui se toma con limón de Pica, al atardecer, después de la destilería.",
    highlights: ["Pisco", "Limón de Pica", "Espuma"],
    priceFromCLP: 6000,
    durationHours: 1,
    tags: ["bebida", "pisco", "clasico"],
    landscapes: ["vinedos", "desierto"],
    placeSlug: "valle-del-elqui",
  },
  {
    slug: "terremoto",
    kind: "food",
    name: "Terremoto",
    region: "Centro",
    city: "Santiago",
    lat: -33.455,
    lng: -70.648,
    image: p("terremoto.jpg"),
    tagline: "Pipeño blanco, helado de piña y un granizado.",
    description:
      "El vaso de la fonda y del 18. Pipeño, helado de piña y, si sigue la noche, una réplica más chica.",
    highlights: ["Pipeño", "Piña", "Fonda"],
    priceFromCLP: 5000,
    durationHours: 1,
    tags: ["bebida", "fiestas", "pipeño"],
    landscapes: ["vinedos"],
    placeSlug: "santiago",
  },
  {
    slug: "borgona",
    kind: "food",
    name: "Borgoña",
    region: "Centro",
    city: "Santiago",
    lat: -33.448,
    lng: -70.64,
    image: p("borgona.jpg"),
    tagline: "Vino tinto, frutilla y hielo. El jarro del verano.",
    description:
      "Se prepara en jarra: tinto, frutillas y hielo. Aparece en el año nuevo, en la playa y en el almuerzo de enero.",
    highlights: ["Vino", "Frutilla", "Verano"],
    priceFromCLP: 5500,
    durationHours: 1,
    tags: ["bebida", "vino", "verano"],
    landscapes: ["vinedos"],
    placeSlug: "santiago",
  },
  {
    slug: "navegado",
    kind: "food",
    name: "Navegado",
    region: "Araucanía y Lagos",
    city: "Puerto Varas",
    lat: -41.317,
    lng: -72.98,
    image: p("navegado.jpg"),
    tagline: "Vino tinto caliente, naranja y canela.",
    description:
      "El trago del sur cuando llueve o cuando hay nieve. Tinto, cáscara de naranja y una rama de canela.",
    highlights: ["Vino caliente", "Naranja", "Canela"],
    priceFromCLP: 4500,
    durationHours: 1,
    tags: ["bebida", "vino", "invierno"],
    landscapes: ["lago", "nieve"],
    placeSlug: "puerto-varas",
  },
  {
    slug: "cola-de-mono",
    kind: "food",
    name: "Cola de mono",
    region: "Centro",
    city: "Santiago",
    lat: -33.44,
    lng: -70.66,
    image: p("cola-de-mono.jpg"),
    tagline: "Leche, café, aguardiente y clavo. La noche de Navidad.",
    description:
      "Se prepara en casa para el 24. Leche, café, azúcar, clavo y aguardiente. Se sirve frío, en copa chica.",
    highlights: ["Café", "Aguardiente", "Navidad"],
    priceFromCLP: 4500,
    durationHours: 1,
    tags: ["bebida", "navidad", "cafe"],
    landscapes: ["vinedos"],
    placeSlug: "santiago",
  },
  {
    slug: "chicha-de-manzana",
    kind: "food",
    name: "Chicha de manzana",
    region: "Araucanía y Lagos",
    city: "Castro",
    lat: -42.48,
    lng: -73.77,
    image: p("chicha-manzana.jpg"),
    tagline: "Manzana chilota fermentada, fresca y algo turbia.",
    description:
      "La sidra del archipiélago. Manzana molida, fermento corto y un vaso en la feria o en la casa de la familia.",
    highlights: ["Manzana", "Chilote", "Fermento"],
    priceFromCLP: 3500,
    durationHours: 1,
    tags: ["bebida", "chilote", "manzana"],
    landscapes: ["bosque-nativo"],
    placeSlug: "chiloe",
  },
  {
    slug: "pipeno",
    kind: "food",
    name: "Pipeño",
    region: "Valle Central",
    city: "Santa Cruz",
    lat: -34.636,
    lng: -71.36,
    image: p("pipeno.jpg"),
    tagline: "Vino joven de garrafa, el del campo y la fonda.",
    description:
      "Tinto o blanco, sin crianza, en garrafa o en vaso. Acompaña el asado, la empanada y el domingo en el valle.",
    highlights: ["Vino joven", "Garrafa", "Campo"],
    priceFromCLP: 4000,
    durationHours: 1,
    tags: ["bebida", "vino", "campo"],
    landscapes: ["vinedos"],
    placeSlug: "colchagua",
  },
  {
    slug: "papaya-sour",
    kind: "food",
    name: "Papaya sour",
    region: "Norte Chico",
    city: "La Serena",
    lat: -29.91,
    lng: -71.25,
    image: p("papaya-sour.jpg"),
    tagline: "Pisco y papaya de La Serena, en copa corta.",
    description:
      "El sour de la costa de Coquimbo. Papaya en almíbar, pisco y limón. Se pide en la Avenida del Mar.",
    highlights: ["Papaya", "Pisco", "Costa"],
    priceFromCLP: 5500,
    durationHours: 1,
    tags: ["bebida", "pisco", "papaya"],
    landscapes: ["playa"],
    placeSlug: "la-serena",
  },
  {
    slug: "muday",
    kind: "food",
    name: "Muday",
    region: "Araucanía y Lagos",
    city: "Pucón",
    lat: -39.28,
    lng: -71.97,
    image: p("muday.jpg"),
    tagline: "Trigo o piñón fermentado, la bebida de la ruka.",
    description:
      "Bebida mapuche de trigo, maíz o piñón. Se ofrece en la ruka, con el relato y la comida de fogón.",
    highlights: ["Trigo", "Ruka", "Mapuche"],
    priceFromCLP: 3500,
    durationHours: 1,
    tags: ["bebida", "mapuche", "ancestral"],
    landscapes: ["volcan"],
    placeSlug: "pucon",
  },
  {
    slug: "piscola",
    kind: "food",
    name: "Piscola",
    region: "Centro",
    city: "Santiago",
    lat: -33.446,
    lng: -70.652,
    image: p("piscola.jpg"),
    tagline: "Pisco y bebida de fantasía, el largo de la noche.",
    description:
      "El trago más pedido del país. Pisco, hielo y una cola. Se toma en bar, en casa y después del asado.",
    highlights: ["Pisco", "Hielo", "Noche"],
    priceFromCLP: 5000,
    durationHours: 1,
    tags: ["bebida", "pisco", "noche"],
    landscapes: ["vinedos"],
    placeSlug: "santiago",
  },
  {
    slug: "vaina",
    kind: "food",
    name: "Vaina",
    region: "Centro",
    city: "Valparaíso",
    lat: -33.043,
    lng: -71.62,
    image: p("vaina.jpg"),
    tagline: "Vino dulce, coñac, huevo y canela. El oporto del puerto.",
    description:
      "Cóctel de barra antigua. Vino generoso, coñac, yema y una nube. Se pide de tarde en Valparaíso.",
    highlights: ["Vino dulce", "Yema", "Puerto"],
    priceFromCLP: 5000,
    durationHours: 1,
    tags: ["bebida", "vino", "bar"],
    landscapes: ["playa"],
    placeSlug: "valparaiso",
  },
  {
    slug: "licor-de-oro",
    kind: "food",
    name: "Licor de oro",
    region: "Araucanía y Lagos",
    city: "Castro",
    lat: -42.485,
    lng: -73.758,
    image: p("licor-de-oro.jpg"),
    tagline: "Suero de leche, aguardiente y azafrán. El licor de Chiloé.",
    description:
      "Se hace en la isla: suero, aguardiente y una hebra de azafrán. Dulce, dorado y de copa chica al final de la comida.",
    highlights: ["Suero", "Azafrán", "Chiloé"],
    priceFromCLP: 5000,
    durationHours: 1,
    tags: ["bebida", "chilote", "licor"],
    landscapes: ["bosque-nativo"],
    placeSlug: "chiloe",
  },
];

export const ACTIVITY_SPORTS: Record<Landscape, string> = {
  desierto: "Astronomía y sandboard",
  playa: "Buceo y surf",
  vinedos: "Cata de vinos",
  volcan: "Trekking, ciclismo y termas",
  rios: "Kayak y rafting",
  lago: "Barcos y deportes náuticos",
  "bosque-nativo": "Tours y trekking",
  nieve: "Ski y snowboard",
  parques: "Trekking y naturaleza",
};

export const activities: CatalogItem[] = [
  {
    slug: "astronomia-atacama",
    kind: "activity",
    name: "Astronomía en el desierto",
    region: "Norte Grande",
    city: "San Pedro de Atacama",
    lat: -22.95,
    lng: -68.18,
    image: p("mamalluca.jpg"),
    tagline: "Telescopios, Vía Láctea y relato andino del cielo.",
    description:
      "Observatorio de campo. Saturno, cúmulos y un mate bajo las estrellas.",
    highlights: ["Telescopio", "Vía Láctea", "Relato andino"],
    priceFromCLP: 42000,
    durationHours: 3,
    tags: ["estrellas", "ciencia", "noche"],
    landscapes: ["desierto"],
    placeSlug: "san-pedro-de-atacama",
  },
  {
    slug: "sandboard-atacama",
    kind: "activity",
    name: "Sandboard en Valle de la Muerte",
    region: "Norte Grande",
    city: "San Pedro de Atacama",
    lat: -22.906,
    lng: -68.243,
    image: p("atacama-dunas.jpg"),
    tagline: "Dunas de yeso, tabla y el Licancabur al fondo.",
    description:
      "Descensos en duna con tabla, instrucción y traslado desde el pueblo. Atardecer incluido.",
    highlights: ["Dunas", "Tabla incluida", "Atardecer"],
    priceFromCLP: 28000,
    durationHours: 3,
    tags: ["sandboard", "desierto", "aventura"],
    landscapes: ["desierto"],
    placeSlug: "san-pedro-de-atacama",
  },
  {
    slug: "buceo-punta-choros",
    kind: "activity",
    name: "Buceo en Punta de Choros",
    region: "Norte Chico",
    city: "La Serena",
    lat: -29.25,
    lng: -71.46,
    image: p("bahia-inglesa.jpg"),
    tagline: "Agua clara, lobos marinos y la Reserva Pingüino de Humboldt.",
    description:
      "Inmersión costera con guía PADI, equipo completo y navegación a Isla Damas.",
    highlights: ["Isla Damas", "Equipo incluido", "Reserva Humboldt"],
    priceFromCLP: 85000,
    durationHours: 6,
    tags: ["buceo", "playa", "fauna"],
    landscapes: ["playa"],
    placeSlug: "la-serena",
  },
  {
    slug: "surf-pichilemu",
    kind: "activity",
    name: "Surf en Punta de Lobos",
    region: "Valle Central",
    city: "Pichilemu",
    lat: -34.423,
    lng: -72.049,
    image: p("isla-negra.jpg"),
    tagline: "El swell del Pacífico en la capital del surf chileno.",
    description:
      "Clase o sesión libre en Punta de Lobos. Tabla, traje y lectura de oleaje con instructor local.",
    highlights: ["Punta de Lobos", "Tabla y traje", "Instructor"],
    priceFromCLP: 35000,
    durationHours: 3,
    tags: ["surf", "playa", "ola"],
    landscapes: ["playa"],
    placeSlug: "litoral-de-los-poetas",
  },
  {
    slug: "cata-colchagua",
    kind: "activity",
    name: "Cata de vinos en Colchagua",
    region: "Valle Central",
    city: "Santa Cruz",
    lat: -34.639,
    lng: -71.366,
    image: p("colchagua.jpg"),
    tagline: "Carmenère, cabernet y el valle en copa.",
    description:
      "Recorrido por viña boutique, cata guiada de cuatro cepas y picoteo de fundo.",
    highlights: ["Cuatro cepas", "Viña boutique", "Picoteo"],
    priceFromCLP: 45000,
    durationHours: 4,
    tags: ["vino", "cata", "campo"],
    landscapes: ["vinedos"],
    placeSlug: "colchagua",
  },
  {
    slug: "volcan-villarrica",
    kind: "activity",
    name: "Trekking al volcán Villarrica",
    region: "Araucanía y Lagos",
    city: "Pucón",
    lat: -39.4208,
    lng: -71.9397,
    image: p("villarrica.jpg"),
    tagline: "Cráter activo, crampones y vista a los lagos.",
    description:
      "Salida de madrugada con guía UIAGM, equipo técnico y descenso en nieve.",
    highlights: ["Cráter", "Guía certificado", "Equipo incluido"],
    priceFromCLP: 145000,
    durationHours: 10,
    tags: ["aventura", "volcán", "trekking"],
    landscapes: ["volcan"],
    placeSlug: "pucon",
  },
  {
    slug: "ciclismo-pucon",
    kind: "activity",
    name: "Ciclismo alrededor del Villarrica",
    region: "Araucanía y Lagos",
    city: "Pucón",
    lat: -39.272,
    lng: -71.974,
    image: p("pucon.jpg"),
    tagline: "Ruta lacustre, bosque de araucaria y el cono siempre a la vista.",
    description:
      "Salida en bicicleta por la cuenca del Villarrica. Bici, casco y picnic de camino.",
    highlights: ["Bici incluida", "Cuenca lacustre", "Picnic"],
    priceFromCLP: 38000,
    durationHours: 5,
    tags: ["ciclismo", "volcán", "lago"],
    landscapes: ["volcan"],
    placeSlug: "pucon",
  },
  {
    slug: "termas-geometricas",
    kind: "activity",
    name: "Termas Geométricas",
    region: "Araucanía y Lagos",
    city: "Coñaripe",
    lat: -39.507,
    lng: -71.888,
    image: p("termas.jpg"),
    tagline: "Pasarelas rojas, pozones de agua volcánica y bosque.",
    description:
      "Día de termas en quebrada nativa. Traslado desde Pucón y almuerzo ligero.",
    highlights: ["Pozones", "Bosque", "Arquitectura"],
    priceFromCLP: 48000,
    durationHours: 7,
    tags: ["termas", "descanso", "volcán"],
    landscapes: ["volcan"],
    placeSlug: "pucon",
  },
  {
    slug: "kayak-siete-tazas",
    kind: "activity",
    name: "Kayak en Siete Tazas",
    region: "Valle Central",
    city: "Molina",
    lat: -35.42,
    lng: -71.0,
    image: p("siete-tazas.jpg"),
    tagline: "Pozones de basalto, cascadas y el río Claro en kayak.",
    description:
      "Descenso suave con guía, chaleco y entrada al parque. Ideal para quienes empiezan.",
    highlights: ["Río Claro", "Cascadas", "Kayak"],
    priceFromCLP: 42000,
    durationHours: 5,
    tags: ["kayak", "ríos", "parque"],
    landscapes: ["rios"],
    placeSlug: "siete-tazas",
  },
  {
    slug: "rafting-futaleufu",
    kind: "activity",
    name: "Rafting en el Futaleufú",
    region: "Patagonia",
    city: "Futaleufú",
    lat: -43.1856,
    lng: -71.8664,
    image: p("futaleufu.jpg"),
    tagline: "Aguas blancas clase IV–V en el río más famoso del sur.",
    description:
      "Descenso guiado, equipo de seguridad y almuerzo de río. Condición media-alta.",
    highlights: ["Clase IV–V", "Guía", "Equipo incluido"],
    priceFromCLP: 89000,
    durationHours: 6,
    tags: ["rafting", "ríos", "aventura"],
    landscapes: ["rios"],
    placeSlug: "futaleufu",
  },
  {
    slug: "barco-peulla",
    kind: "activity",
    name: "Navegación a Peulla",
    region: "Araucanía y Lagos",
    city: "Puerto Varas",
    lat: -41.13,
    lng: -72.4,
    image: p("puerto-varas.jpg"),
    tagline: "Cruce de lagos, volcanes y el pueblo al fondo del Todos los Santos.",
    description:
      "Barco por el lago Todos los Santos hasta Peulla. Almuerzo a bordo y vista al Osorno y Puntiagudo.",
    highlights: ["Todos los Santos", "Peulla", "Volcanes"],
    priceFromCLP: 72000,
    durationHours: 8,
    tags: ["barcos", "lagos", "cruce"],
    landscapes: ["lago"],
    placeSlug: "puerto-varas",
  },
  {
    slug: "nautico-llanquihue",
    kind: "activity",
    name: "Deportes náuticos en Llanquihue",
    region: "Araucanía y Lagos",
    city: "Puerto Varas",
    lat: -41.31,
    lng: -72.98,
    image: p("osorno.jpg"),
    tagline: "Kayak, velero o paddle con el Osorno reflejado en el lago.",
    description:
      "Sesión de dos horas en el lago. Equipo, chaleco, guía y chocolate caliente al volver.",
    highlights: ["Osorno", "Kayak o velero", "Atardecer"],
    priceFromCLP: 36000,
    durationHours: 2,
    tags: ["náutico", "lagos", "kayak"],
    landscapes: ["lago"],
    placeSlug: "puerto-varas",
  },
  {
    slug: "tour-bosque-chiloe",
    kind: "activity",
    name: "Tour por los bosques de Chiloé",
    region: "Araucanía y Lagos",
    city: "Castro",
    lat: -42.4825,
    lng: -73.764,
    image: p("palafitos.jpg"),
    tagline: "Tepú, alerce joven, palafitos y mitología del archipiélago.",
    description:
      "Recorrido guiado por bosque siempreverde, iglesia de madera y caleta. Almuerzo chilote.",
    highlights: ["Bosque chilote", "Iglesia UNESCO", "Guía local"],
    priceFromCLP: 39000,
    durationHours: 6,
    tags: ["tour", "bosque", "cultura"],
    landscapes: ["bosque-nativo"],
    placeSlug: "chiloe",
  },
  {
    slug: "trekking-la-campana",
    kind: "activity",
    name: "Trekking en La Campana",
    region: "Centro",
    city: "Olmué",
    lat: -32.953,
    lng: -71.119,
    image: p("olmue.jpg"),
    tagline: "Palma chilena, bosque esclerófilo y el cerro que subió Darwin.",
    description:
      "Sendero al cumbre o al palmar. Guía, picnic y entrada al parque nacional.",
    highlights: ["Palma chilena", "Mirador", "Guía"],
    priceFromCLP: 32000,
    durationHours: 7,
    tags: ["trekking", "bosque", "parque"],
    landscapes: ["bosque-nativo"],
    placeSlug: "olmue",
  },
  {
    slug: "ski-valle-nevado",
    kind: "activity",
    name: "Ski en Valle Nevado",
    region: "Centro",
    city: "Lo Barnechea",
    lat: -33.354,
    lng: -70.249,
    image: p("ski-valle-nevado.jpg"),
    tagline: "Pistas andinas a una hora de Santiago.",
    description:
      "Día de ski con ticket, equipo y traslado desde la ciudad. Temporada de junio a octubre.",
    highlights: ["Ticket de pistas", "Equipo", "Traslado"],
    priceFromCLP: 89000,
    durationHours: 9,
    tags: ["ski", "nieve", "andina"],
    landscapes: ["nieve"],
    placeSlug: "farellones-valle-nevado",
  },
  {
    slug: "snowboard-chillan",
    kind: "activity",
    name: "Snowboard en Chillán",
    region: "Valle Central",
    city: "Chillán",
    lat: -36.91,
    lng: -71.41,
    image: p("chillan.jpg"),
    tagline: "Nieve volcánica, bosque y pistas del Nevados de Chillán.",
    description:
      "Día de snowboard con ticket, tabla y botas. Termas al cierre, si el cuerpo pide agua caliente.",
    highlights: ["Tabla y botas", "Nevados de Chillán", "Termas"],
    priceFromCLP: 78000,
    durationHours: 8,
    tags: ["snowboard", "nieve", "volcán"],
    landscapes: ["nieve"],
    placeSlug: "termas-de-chillan",
  },
  {
    slug: "geiseres-el-tatio",
    kind: "activity",
    name: "Géiseres del Tatio",
    region: "Norte Grande",
    city: "San Pedro de Atacama",
    lat: -22.332,
    lng: -68.011,
    image: p("parinacota.jpg"),
    tagline: "Amanecer a 4.300 m, columnas de vapor y altiplano.",
    description:
      "Salida de madrugada al campo geotérmico. Desayuno a orilla de las fumarolas y vuelta por lagunas altoandinas.",
    highlights: ["Amanecer", "Altiplano", "Traslado"],
    priceFromCLP: 45000,
    durationHours: 8,
    tags: ["desierto", "amanecer", "altiplano"],
    landscapes: ["desierto"],
    placeSlug: "san-pedro-de-atacama",
  },
  {
    slug: "kayak-bahia-inglesa",
    kind: "activity",
    name: "Kayak en Bahía Inglesa",
    region: "Norte Grande",
    city: "Caldera",
    lat: -27.108,
    lng: -70.858,
    image: p("bahia-inglesa.jpg"),
    tagline: "Agua turquesa, desierto costero y caleta de arena blanca.",
    description:
      "Sesión de kayak en la bahía. Equipo, chaleco y guía. Ideal al amanecer, cuando el mar está plano.",
    highlights: ["Agua turquesa", "Kayak", "Guía"],
    priceFromCLP: 32000,
    durationHours: 2,
    tags: ["kayak", "playa", "desierto"],
    landscapes: ["playa"],
    placeSlug: "bahia-inglesa",
  },
  {
    slug: "cata-maipo",
    kind: "activity",
    name: "Cata de vinos en el Maipo",
    region: "Centro",
    city: "Santiago",
    lat: -33.67,
    lng: -70.58,
    image: p("vina.jpg"),
    tagline: "Carmenère y cabernet a media hora de la capital.",
    description:
      "Viña del piedemonte, cata de tres cepas y vista a los Andes. Traslado desde Santiago.",
    highlights: ["Tres cepas", "Andes", "Traslado"],
    priceFromCLP: 42000,
    durationHours: 4,
    tags: ["vino", "cata", "maipo"],
    landscapes: ["vinedos"],
    placeSlug: "santiago",
  },
  {
    slug: "cata-elqui",
    kind: "activity",
    name: "Pisco y viñedos en Elqui",
    region: "Norte Chico",
    city: "Pisco Elqui",
    lat: -30.127,
    lng: -70.493,
    image: p("pisco-elqui.jpg"),
    tagline: "Moscatel, destilería familiar y el valle en copa.",
    description:
      "Visita a destilería, cata de piscos y un viñedo de altura. Atardecer sobre las terrazas.",
    highlights: ["Destilería", "Cata de pisco", "Viñedo"],
    priceFromCLP: 38000,
    durationHours: 4,
    tags: ["pisco", "cata", "valle"],
    landscapes: ["vinedos"],
    placeSlug: "valle-del-elqui",
  },
  {
    slug: "kayak-laja",
    kind: "activity",
    name: "Kayak en el Laja",
    region: "Valle Central",
    city: "Cabrero",
    lat: -37.217,
    lng: -72.38,
    image: p("laja.jpg"),
    tagline: "Aguas del Laja, bosque y la cascada clásica del sur.",
    description:
      "Descenso suave en kayak por el río Laja, con guía, chaleco y parada en mirador de los saltos.",
    highlights: ["Río Laja", "Kayak", "Cascada"],
    priceFromCLP: 36000,
    durationHours: 4,
    tags: ["kayak", "ríos", "cascada"],
    landscapes: ["rios"],
    placeSlug: "saltos-del-laja",
  },
  {
    slug: "navegacion-marmol",
    kind: "activity",
    name: "Navegación a las Capillas de Mármol",
    region: "Patagonia",
    city: "Puerto Río Tranquilo",
    lat: -46.605,
    lng: -72.641,
    image: p("marmol.jpg"),
    tagline: "Cavernas azules en el lago General Carrera.",
    description:
      "Lancha o kayak al amanecer hacia la capilla, catedral y cavernas. Guía local y chaleco.",
    highlights: ["Capilla de Mármol", "Lago turquesa", "Amanecer"],
    priceFromCLP: 55000,
    durationHours: 3,
    tags: ["barcos", "lagos", "patagonia"],
    landscapes: ["lago"],
    placeSlug: "capillas-de-marmol",
  },
  {
    slug: "sendero-alerce-chiloe",
    kind: "activity",
    name: "Sendero de alerces en Chiloé",
    region: "Araucanía y Lagos",
    city: "Castro",
    lat: -42.54,
    lng: -73.92,
    image: p("castro.jpg"),
    tagline: "Alerce, tepú y el bosque siempreverde del archipiélago.",
    description:
      "Caminata guiada por bosque valdiviano, alerces jóvenes y humedal. Picnic chilote al cierre.",
    highlights: ["Alerce", "Bosque valdiviano", "Guía local"],
    priceFromCLP: 34000,
    durationHours: 5,
    tags: ["trekking", "bosque", "chiloé"],
    landscapes: ["bosque-nativo"],
    placeSlug: "chiloe",
  },
  {
    slug: "ski-la-parva",
    kind: "activity",
    name: "Ski en La Parva",
    region: "Centro",
    city: "Lo Barnechea",
    lat: -33.332,
    lng: -70.29,
    image: p("ski-la-parva.jpg"),
    tagline: "Pistas familiares y fuera de pista a un paso de Farellones.",
    description:
      "Día de ski en La Parva con ticket, equipo y traslado desde Santiago. Temporada de junio a octubre.",
    highlights: ["Ticket de pistas", "Equipo", "Traslado"],
    priceFromCLP: 82000,
    durationHours: 9,
    tags: ["ski", "nieve", "andina"],
    landscapes: ["nieve"],
    placeSlug: "farellones-valle-nevado",
  },
  {
    slug: "sendero-conguillio",
    kind: "activity",
    name: "Trekking en Conguillío",
    region: "Araucanía y Lagos",
    city: "Melipeuco",
    lat: -38.65,
    lng: -71.63,
    image: p("pn-conguillio.jpg"),
    tagline: "Araucarias, lava del Llaima y la laguna verde.",
    description:
      "Sendero Sierra Nevada o Los Lagos. Guía, picnic y entrada al parque. Pase digital en pasesparques.cl.",
    highlights: ["Araucarias", "Laguna", "Llaima"],
    priceFromCLP: 38000,
    durationHours: 7,
    tags: ["trekking", "parque", "araucaria"],
    landscapes: ["parques"],
    placeSlug: "pn-conguillio",
  },
  {
    slug: "sendero-huerquehue",
    kind: "activity",
    name: "Sendero Los Lagos en Huerquehue",
    region: "Araucanía y Lagos",
    city: "Pucón",
    lat: -39.13,
    lng: -71.73,
    image: p("pn-huerquehue.jpg"),
    tagline: "Tres lagunas de altura y bosque de araucaria.",
    description:
      "Trekking clásico de Pucón. Guía, picnic y entrada. Pase digital en pasesparques.cl.",
    highlights: ["Los Lagos", "Araucarias", "Tinquilco"],
    priceFromCLP: 36000,
    durationHours: 6,
    tags: ["trekking", "parque", "lagunas"],
    landscapes: ["parques"],
    placeSlug: "pn-huerquehue",
  },
  {
    slug: "cueva-del-milodon",
    kind: "activity",
    name: "Cueva del Milodón",
    region: "Patagonia",
    city: "Puerto Natales",
    lat: -51.57,
    lng: -72.62,
    image: p("mn-cueva-del-milodon.jpg"),
    tagline: "La caverna paleontológica a un paso de Natales.",
    description:
      "Visita guiada a la cueva, relato del milodón y vista al seno. Pase digital en pasesparques.cl.",
    highlights: ["Cueva", "Milodón", "Natales"],
    priceFromCLP: 18000,
    durationHours: 3,
    tags: ["parque", "cultura", "patagonia"],
    landscapes: ["parques"],
    placeSlug: "mn-cueva-del-milodon",
  },
  {
    slug: "valle-de-la-luna",
    kind: "activity",
    name: "Atardecer en Valle de la Luna",
    region: "Norte Grande",
    city: "San Pedro de Atacama",
    lat: -22.9147,
    lng: -68.2874,
    image: p("atacama-luna.jpg"),
    tagline: "Dunas, salar y el sol cayendo sobre el Licancabur.",
    description:
      "Caminata guiada por formaciones de sal y yeso. Cupo reducido, hidratación y traslado.",
    highlights: ["Licancabur", "Dunas", "Guía local"],
    priceFromCLP: 35000,
    durationHours: 4,
    tags: ["desierto", "atardecer", "fotografía"],
    landscapes: ["desierto"],
    placeSlug: "san-pedro-de-atacama",
    cluster: "otros",
  },
  {
    slug: "w-paine",
    kind: "activity",
    name: "Día en Base Torres",
    region: "Patagonia",
    city: "Puerto Natales",
    lat: -50.942,
    lng: -72.959,
    image: p("paine.jpg"),
    tagline: "El trekking clásico hasta las tres torres de granito.",
    description:
      "Sendero de 22 km con guía, picnic y entrada al parque. Condición media-alta.",
    highlights: ["Mirador Torres", "Guía", "Picnic"],
    priceFromCLP: 98000,
    durationHours: 11,
    tags: ["trekking", "patagonia", "aventura"],
    landscapes: ["lago", "nieve"],
    placeSlug: "torres-del-paine",
    cluster: "otros",
  },
  {
    slug: "cerros-valpo",
    kind: "activity",
    name: "Cerros, murales y ascensores",
    region: "Centro",
    city: "Valparaíso",
    lat: -33.045,
    lng: -71.622,
    image: p("valparaiso.jpg"),
    tagline: "Alegre, Concepción y el puerto con guía local.",
    description:
      "Caminata urbana de 3 horas: street art, miradores y una copa en café de cerro.",
    highlights: ["Street art", "Ascensores", "Miradores"],
    priceFromCLP: 18000,
    durationHours: 3,
    tags: ["cultura", "ciudad", "arte"],
    landscapes: ["playa"],
    placeSlug: "valparaiso",
    cluster: "otros",
  },
  {
    slug: "tongariki-amanecer",
    kind: "activity",
    name: "Amanecer en Tongariki",
    region: "Rapa Nui",
    city: "Hanga Roa",
    lat: -27.125,
    lng: -109.277,
    image: p("tongariki.jpg"),
    tagline: "Quince moai contra el sol del Pacífico.",
    description:
      "Salida de madrugada con guía rapanui, desayuno y visita a Rano Raraku.",
    highlights: ["Moai", "Amanecer", "Guía rapanui"],
    priceFromCLP: 65000,
    durationHours: 5,
    tags: ["cultura", "amanecer", "patrimonio"],
    landscapes: ["playa"],
    placeSlug: "rapa-nui",
    cluster: "otros",
  },
];

export function groupedActivities() {
  const groups = landscapes.map((l) => ({
    id: l.id as Landscape | "otros",
    label: l.label,
    sports: ACTIVITY_SPORTS[l.id],
    items: activities.filter((a) => (a.cluster ?? a.landscapes?.[0]) === l.id),
  }));
  const otros = activities.filter((a) => a.cluster === "otros");
  if (otros.length) {
    groups.push({
      id: "otros",
      label: "Otros",
      sports: "Cultura, amaneceres y miradores",
      items: otros,
    });
  }
  return groups;
}

export const allItems: CatalogItem[] = [
  ...destinations,
  ...capsules,
  ...gastronomy,
  ...activities,
];

export const regions: Region[] = [
  "Norte Grande",
  "Norte Chico",
  "Centro",
  "Valle Central",
  "Araucanía y Lagos",
  "Patagonia",
  "Rapa Nui",
  "Pacífico",
  "Antártica",
];

export const interests = [
  { id: "naturaleza", label: "Naturaleza" },
  { id: "gastronomia", label: "Gastronomía" },
  { id: "cultura", label: "Cultura" },
  { id: "aventura", label: "Aventura" },
  { id: "descanso", label: "Descanso" },
  { id: "estrellas", label: "Astronomía" },
] as const;

export const destinationAliases: Record<string, string> = {
  "santiago-and-maipo": "santiago",
};

export function formatCLP(n: number) {
  return new Intl.NumberFormat("es-CL", {
    style: "currency",
    currency: "CLP",
    maximumFractionDigits: 0,
  }).format(Math.round(n));
}

export function getBySlug(slug: string) {
  const resolved = destinationAliases[slug] || slug;
  return allItems.find((i) => i.slug === resolved);
}

export function itemsForPlace(placeSlug: string) {
  const resolved = destinationAliases[placeSlug] || placeSlug;
  return allItems.filter(
    (i) => i.slug === resolved || i.placeSlug === resolved,
  );
}

export function capsulesForPlace(placeSlug: string) {
  const resolved = destinationAliases[placeSlug] || placeSlug;
  return capsules.filter((c) => c.placeSlug === resolved);
}

export function planCatalog(placeSlug: string) {
  const resolved = destinationAliases[placeSlug] || placeSlug;
  const place =
    destinations.find((d) => d.slug === resolved) ||
    destinations.find((d) => d.slug === "san-pedro-de-atacama") ||
    destinations[0];
  const land = place.landscapes?.[0];
  const featured = land ? landscapePlaceSlug[land] : place.slug;
  const stay =
    capsules.find((c) => c.placeSlug === place.slug) ||
    capsules.find((c) => c.placeSlug === featured) ||
    capsules[0];
  const seen = new Set<string>();
  const uniq = (items: CatalogItem[]) =>
    items.filter((i) => {
      if (seen.has(i.slug)) return false;
      seen.add(i.slug);
      return true;
    });
  const food = uniq([
    ...gastronomy.filter((g) => g.placeSlug === place.slug),
    ...gastronomy.filter((g) => land && g.landscapes?.includes(land)),
  ]);
  seen.clear();
  const acts = uniq([
    ...activities.filter((a) => a.placeSlug === place.slug),
    ...activities.filter(
      (a) => land && (a.cluster ?? a.landscapes?.[0]) === land,
    ),
  ]);
  const table =
    food.length > 0
      ? food
      : gastronomy.filter((g) =>
          ["empanadas-de-pino", "sopaipillas", "cazuela"].includes(g.slug),
        );
  return { place, stay, food: table, acts, land };
}

export function mapPoints() {
  return [
    ...destinations.map((d) => ({
      ...d,
      group: "place" as const,
    })),
    ...capsules.map((c) => ({
      ...c,
      group: "capsule" as const,
    })),
  ];
}

export function featuredCapsules() {
  return landscapes
    .map((l) => {
      const item = capsules.find((c) => c.placeSlug === landscapePlaceSlug[l.id]);
      return item ? { item, land: l.id } : null;
    })
    .filter((x): x is { item: CatalogItem; land: Landscape } => Boolean(x));
}

export function destinationsByLandscape(id: Landscape | "all") {
  if (id === "all") return destinations;
  return destinations.filter((d) => d.landscapes?.includes(id));
}
