import type { Landscape } from "./catalog";
import type { Locale } from "./locale";

const es = {
  skip: "Saltar al contenido",
  language: "Idioma",
  nav: {
    why: "Por qué Chile",
    map: "Mapa",
    capsules: "Cápsulas",
    food: "Gastronomía",
    activities: "Actividades",
    partners: "Partners",
    awards: "Premios",
    plan: "Planificar",
    app: "App",
    login: "Entrar",
    signup: "Crear cuenta",
    logout: "Salir",
    menu: "Menú",
    prev: "Anterior",
    next: "Siguiente",
  },
  hero: {
    title: "Chile, de norte a sur.",
    lead: "Cápsulas de cobre y vidrio en desiertos, playas, viñedos, volcanes, ríos, lagos, bosques, nieve y parques nacionales. Mesa local y presupuesto en CLP.",
    planCta: "Planificar",
    appCta: "Abrir App",
  },
  whyChile: {
    kicker: "Viaje infinito",
    title: "¿Por qué Chile?",
    lead: "Treinta segundos para recorrer el país de norte a sur.",
    video: "Por qué Chile, versión en español",
  },
  map: {
    kicker: "Mapa",
    title: "Chile clasificado por paisaje",
    lead: "Filtra desiertos, playas, viñedos, volcanes, ríos, lagos, bosques, nieve y los 48 parques nacionales con pase digital. Cada pin es un territorio con su cápsula.",
    all: "Todos",
    places: "Lugares",
    capsules: "Cápsulas",
    partners: "Partners",
    both: "Todos",
    legend: "Isologo Mapucoin",
    loading: "Cargando mapa de Chile…",
    viewSheet: "Ver ficha →",
    destination: "Destino",
    capsule: "Cápsula",
    partner: "Partner",
    search: "Buscar destino, cápsula o partner",
    searchEmpty: "Sin coincidencias",
    searchClear: "Limpiar búsqueda",
    emptyPartners: "Aún no hay partners aprobados en el mapa.",
    emptyPartnersHint:
      "Cuando un partner local se apruebe, su pin aparece aquí.",
  },
  capsules: {
    kicker: "Cápsulas",
    title: "Cada paisaje, una casa cápsula",
    lead: "Cobre, vidrio y madera. Off-grid opcional, aislación de −40 °C a 40 °C. Una cápsula por paisaje — también en parques nacionales — operada por partners locales.",
    alt: "Casa cápsula Mapucoin",
    fromNight: "desde {price} / noche",
    perNight: "Por noche",
    upTo: "Hasta {n} viajeros · {region}",
    book: "Reservar",
    canceled: "Pago cancelado. Puedes reservar de nuevo cuando quieras.",
    explore: "Explorar {name} →",
    location: "Ubicación",
    interiorAlt: "Interior de cobre, madera y vidrio",
  },
  food: {
    kicker: "Gastronomía",
    title: "La mesa del territorio",
    lead: "Curanto, empanadas de pino, pastel de choclo, caldillo de congrio, mote con huesillos y la mesa de cada territorio. Con partners locales.",
    hours: "{price} · {hours} h",
  },
  activities: {
    kicker: "Actividades",
    title: "Lo que se hace en el territorio",
    lead: "Clasificadas por paisaje: astronomía y sandboard en el desierto, buceo y surf en la playa, cata en los viñedos, trekking y termas en los volcanes, kayak y rafting en los ríos, barcos en los lagos, tours en el bosque, ski en la nieve.",
    other: "Otros",
    otherSports: "Cultura, amaneceres y miradores",
  },
  plan: {
    kicker: "Planificar",
    title: "Tu viaje, a tu presupuesto",
    lead: "Elige el paisaje, el presupuesto en CLP y Mapucoin arma noches en cápsula, mesa y actividades de ese territorio.",
    formKicker: "Planificador",
    formTitle: "¿Cuánto y a dónde?",
    formLead:
      "Elige el paisaje y el presupuesto en pesos chilenos. Mapucoin arma cápsula, mesa y actividades de ese territorio.",
    landscape: "Paisaje",
    place: "Lugar a conocer",
    previewTitle: "En este territorio",
    previewLead:
      "Cápsula, mesa y lo que se hace en el paisaje. Arma el viaje para ver el itinerario día a día.",
    previewStay: "Dormir",
    previewTable: "Mesa",
    previewActs: "Hacer",
    previewPass: "Pase",
    more: "+{n}",
    loadingHint: "Cápsula, mesa y actividades según tu presupuesto.",
    budget: "Presupuesto total · {price}",
    budgetMin: "250 mil",
    budgetMax: "3,5 millones",
    nights: "Noches",
    guests: "Viajeros",
    interests: "Intereses",
    fromDay: "Desde {price} por día de experiencia en {city}.",
    submit: "Armar viaje",
    ask: "Preguntar",
    askHint: "Ej: ¿conviene más Pucón o Puerto Varas con 600 mil?",
    askPlaceholder: "Escribe tu consulta…",
    send: "Enviar",
    you: "Tú",
    loadingPlan: "Armando el itinerario con tu presupuesto…",
    loadPlanner: "Cargando planificador…",
    errorPlan: "No se pudo armar el itinerario.",
    errorNet: "Error de red al armar el itinerario.",
    empty:
      "Elige un paisaje y arma el viaje. El itinerario aparece aquí, con cápsula, mesa y actividades.",
    chatFail: "no pude responder ahora.",
  },
  itinerary: {
    kicker: "Itinerario",
    budget: "Presupuesto",
    estimated: "Total estimado",
    remaining: "Queda",
    nightsGuests: "Noches · viajeros",
    stay: "Cápsula",
    table: "Mesa",
    acts: "Actividades",
    day: "Día {n}",
    included: "incluido",
    bookStay: "Reservar cápsula",
    seeMap: "Ver en el mapa",
    passes: "Pases",
    buyPass: "Comprar pase oficial",
    passRates:
      "Adulto nacional {adult} × {guests}. Joven {youth}. Niño, adulto mayor y discapacidad nacional: sin costo. Extranjero adulto {foreign}.",
    passStay: "Pase de más de 1 día. Un día: {day} por adulto nacional.",
    passZero: "La ficha oficial publica $0. Confirma el valor al comprar.",
    passCampana:
      "Sector Granizo. Ocoa y Cajón Grande se compran aparte, a la misma tarifa.",
    passPatagonia:
      "Sector Chacabuco. Jeinimeni y Tamango se compran aparte, a la misma tarifa.",
    passSource:
      "Tarifa de pasesparques.cl. Mapucoin no cobra el pase: la compra es en el sitio oficial.",
  },
  partners: {
    kicker: "Partners",
    title: "Ingresa como partner",
    lead: "Operas una cápsula, una ruka, una caleta, un tour o una viña. Mapucoin te muestra en el mapa, entra al itinerario y cobra con Stripe.",
    name: "Nombre",
    email: "Correo",
    phone: "Teléfono",
    role: "Tipo de partner",
    business: "Nombre del negocio",
    city: "Ciudad / territorio",
    notes: "Cuéntanos tu oferta",
    submit: "Postular",
    sending: "Enviando…",
    incomplete: "Completa nombre, correo y negocio.",
    error: "No se pudo enviar. Inténtalo de nuevo.",
    ok: "Recibimos tu postulación",
    okLead:
      "Revisamos tu oferta y te escribimos para activar la ficha y Stripe. No publicamos tus datos hasta aprobarte.",
    invalidEmail: "Ingresa un correo válido.",
    privacy:
      "Tus datos no se muestran a otros postulantes ni en el mapa público.",
    another: "Enviar otra postulación",
    okNoDb:
      "Recibimos tu postulación. Conecta Supabase para guardar partners en producción.",
    onboardTitle: "Activar Stripe Connect",
    onboardLead:
      "Usa el mismo correo de tu postulación. Stripe abre una cuenta Express en Chile (CL).",
    onboardSubmit: "Continuar a Stripe",
    onboardBlocked:
      "Stripe no pudo crear la cuenta Connect en Chile. El cobro sigue en la plataforma Mapucoin; el 12% queda contabilizado para payout manual.",
    onboardNeedEmail: "Ingresa el correo de la postulación.",
    returnTitle: "Onboarding enviado",
    returnLead:
      "Cuando Stripe active charges y payouts, el checkout comparte el pago (12% plataforma).",
  },
  partnerRoles: {
    capsula: "Cápsula / alojamiento",
    gastronomia: "Gastronomía",
    actividad: "Actividad / tour",
    guia: "Guía",
    transporte: "Transporte",
    vina: "Viña / destilería",
  },
  awards: {
    kicker: "Premios",
    title: "Premios y reconocimientos internacionales",
    lead: "Chile, Atacama, Santiago, Rapa Nui y Torres del Paine, distinguidos por World Travel Awards, TIME, Forbes, Tripadvisor y UNESCO.",
    prev: "Premio anterior",
    next: "Premio siguiente",
    goTo: "Ir al premio {n}",
    of: "{n} de {total}: {title}",
  },
  kinds: {
    place: "Destino",
    capsule: "Cápsula",
    food: "Mesa",
    activity: "Actividad",
  },
  landscapes: {
    desierto: "Desiertos",
    playa: "Playas",
    vinedos: "Viñedos",
    volcan: "Volcanes",
    rios: "Ríos",
    lago: "Lagos",
    "bosque-nativo": "Bosques",
    nieve: "Nieve",
    parques: "Parques Nacionales",
  } satisfies Record<Landscape, string>,
  activitySports: {
    desierto: "Astronomía y sandboard",
    playa: "Buceo y surf",
    vinedos: "Cata de vinos",
    volcan: "Trekking, ciclismo y termas",
    rios: "Kayak y rafting",
    lago: "Barcos y deportes náuticos",
    "bosque-nativo": "Tours y trekking",
    nieve: "Ski y snowboard",
    parques: "Trekking y naturaleza",
  } satisfies Record<Landscape, string>,
  interests: {
    naturaleza: "Naturaleza",
    gastronomia: "Gastronomía",
    cultura: "Cultura",
    aventura: "Aventura",
    descanso: "Descanso",
    estrellas: "Astronomía",
  },
  from: "desde",
  operator: "Operado por",
  sound: "Sonido",
  mute: "Silencio",
  footer: { terms: "Terms", privacy: "Privacy" },
  notFound: {
    title: "Territorio no encontrado",
    lead: "Esa ruta no está en el mapa Mapucoin.",
    back: "Volver al inicio",
  },
  destino: {
    videoKicker: "Video del territorio",
    videoTitle: "{name} en movimiento",
    videoAlt: "Video de {name}",
    gallery: "Galería",
    onMap: "En el mapa",
    from: "Experiencias desde",
    passFrom: "Entrada adulto nacional",
    passKicker: "Pase oficial",
    passAdult: "Nacional {national} · extranjero {foreign}",
    passYouth: "Joven nacional {youth} · joven extranjero {foreignYouth}",
    passFree:
      "Niño, adulto mayor y persona con discapacidad nacional entran sin costo.",
    passMulti:
      "Más de 1 día: nacional {national} · extranjero {foreign}. Un día: {day}.",
    buyPass: "Comprar en pasesparques.cl",
    passSource: "Tarifa publicada en pasesparques.cl.",
    planThis: "Planificar este destino",
    seeCapsule: "Ver cápsula {name}",
    related: "Dormir, comer y hacer",
  },
  reserva: {
    kicker: "Reserva",
    title: "Confirmar reserva",
    canceled: "Pago cancelado. Puedes reintentar.",
    summary: "{name} · {city}. {nights} · {guests}. Total {total}.",
    night: "noche",
    nights: "noches",
    guest: "viajero",
    guests: "viajeros",
    capsule: "Cápsula",
    name: "Nombre",
    email: "Correo",
    phone: "Teléfono",
    pay: "Reservar / Pagar",
    included: "Incluye",
    perNight: "por noche",
    totalLabel: "Total",
    backMap: "Volver al mapa",
    backCapsule: "Volver a la cápsula",
    invalidName: "Escribe tu nombre (mínimo 2 letras).",
    invalidEmail: "Ingresa un correo válido.",
    rateLimited: "Demasiados intentos. Espera un momento e inténtalo de nuevo.",
    secure: "Pago seguro con Stripe",
    platformNote:
      "Cobro en CLP sobre Mapucoin. Si el partner aún no tiene Stripe Connect, el pago queda en la plataforma.",
    fromPrice: "Desde {price} / noche",
    paying: "Redirigiendo a Stripe…",
    creating: "Creando sesión de Stripe…",
    noStripe: "Stripe no está configurado. Añade STRIPE_SECRET_KEY en Vercel.",
    fail: "No se pudo iniciar el pago. Revisa los datos.",
    okKicker: "Listo",
    okTitle: "Reserva confirmada",
    okLead:
      "Stripe registró el pago. Te escribimos con el check-in de la cápsula y el resto del itinerario.",
    okCta: "Volver al mapa",
    okAmount: "Monto",
    okCapsule: "Cápsula",
    okNights: "Noches",
    okGuests: "Viajeros",
    okEmail: "Correo",
    okPending: "Confirmando el pago…",
    okMissing:
      "No encontramos la sesión. Si el cargo se hizo, el comprobante llega a tu correo.",
    okPaid: "Pagado",
  },
  catalogEmpty: "No hay fichas en este paisaje.",
  awardTitles: {
    "Mejor Destino de Turismo Aventura del Mundo":
      "Mejor Destino de Turismo Aventura del Mundo",
    "Mejor Destino Romántico": "Mejor Destino Romántico",
    "Mejor Destino de Sudamérica": "Mejor Destino de Sudamérica",
    "Mejor Destino Verde": "Mejor Destino Verde",
    "Mejor Destino de Naturaleza": "Mejor Destino de Naturaleza",
    "Mejor Ciudad": "Mejor Ciudad",
    "Mejor Destino de Cruceros": "Mejor Destino de Cruceros",
    "Mejor Destino Internacional": "Mejor Destino Internacional",
    "Solo Travel — 4° mundial": "Solo Travel — 4° mundial",
    "Top South American Destination": "Top South American Destination",
    "Reserva de la Biósfera": "Reserva de la Biósfera",
    "Mejor Viñedo del Mundo": "Mejor Viñedo del Mundo",
    "World's Greatest Places": "World's Greatest Places",
    "Patrimonio de la Humanidad": "Patrimonio de la Humanidad",
    "Mejor lugar del mundo para observación de estrellas":
      "Mejor lugar del mundo para observación de estrellas",
    "El radiotelescopio más grande del mundo":
      "El radiotelescopio más grande del mundo",
  },
  awardNotes: {
    "7ª vez": "7ª vez",
    "Octava Maravilla del Mundo": "Octava Maravilla del Mundo",
    "Postulación a premio de gobernanza": "Postulación a premio de gobernanza",
    "Estancia Mercedes (Magallanes), Pared Sur Camp (Aysén) y Ephedra Restaurant (Antofagasta)":
      "Estancia Mercedes (Magallanes), Pared Sur Camp (Aysén) y Ephedra Restaurant (Antofagasta)",
    Astroturismo: "Astroturismo",
  },
  legalTermsTitle: "Términos y Condiciones",
  legalPrivacyTitle: "Política de Privacidad",
};

const en: typeof es = {
  skip: "Skip to content",
  language: "Language",
  nav: {
    why: "Why Chile",
    map: "Map",
    capsules: "Capsules",
    food: "Gastronomy",
    activities: "Activities",
    partners: "Partners",
    awards: "Awards",
    plan: "Plan",
    app: "App",
    login: "Log in",
    signup: "Sign up",
    logout: "Log out",
    menu: "Menu",
    prev: "Previous",
    next: "Next",
  },
  hero: {
    title: "Chile, north to south.",
    lead: "Copper and glass capsules in deserts, beaches, vineyards, volcanoes, rivers, lakes, forests, snow and national parks. Local table and budget in CLP.",
    planCta: "Plan",
    appCta: "Open App",
  },
  whyChile: {
    kicker: "Infinite journey",
    title: "Why Chile?",
    lead: "Thirty seconds across the country, north to south.",
    video: "Why Chile, English version",
  },
  map: {
    kicker: "Map",
    title: "Chile classified by landscape",
    lead: "Filter deserts, beaches, vineyards, volcanoes, rivers, lakes, forests, snow and the 48 national parks with a digital pass. Each pin is a territory with its capsule.",
    all: "All",
    places: "Places",
    capsules: "Capsules",
    partners: "Partners",
    both: "All",
    legend: "Mapucoin isologo",
    loading: "Loading the map of Chile…",
    viewSheet: "View sheet →",
    destination: "Destination",
    capsule: "Capsule",
    partner: "Partner",
    search: "Search destination, capsule or partner",
    searchEmpty: "No matches",
    searchClear: "Clear search",
    emptyPartners: "No approved partners on the map yet.",
    emptyPartnersHint: "When a local partner is approved, their pin appears here.",
  },
  capsules: {
    kicker: "Capsules",
    title: "Each landscape, one capsule home",
    lead: "Copper, glass and wood. Optional off-grid, insulation from −40 °C to 40 °C. One capsule per landscape — also in national parks — run by local partners.",
    alt: "Mapucoin capsule house",
    fromNight: "from {price} / night",
    perNight: "Per night",
    upTo: "Up to {n} guests · {region}",
    book: "Book",
    canceled: "Payment canceled. You can book again whenever you like.",
    explore: "Explore {name} →",
    location: "Location",
    interiorAlt: "Copper, wood and glass interior",
  },
  food: {
    kicker: "Gastronomy",
    title: "The table of the territory",
    lead: "Curanto, empanadas de pino, pastel de choclo, caldillo de congrio, mote con huesillos and the table of each territory. With local partners.",
    hours: "{price} · {hours} h",
  },
  activities: {
    kicker: "Activities",
    title: "What you do in the territory",
    lead: "Classified by landscape: astronomy and sandboarding in the desert, diving and surf on the beach, wine tasting in the vineyards, trekking and hot springs on the volcanoes, kayak and rafting on the rivers, boats on the lakes, forest tours, ski in the snow.",
    other: "Other",
    otherSports: "Culture, sunrises and lookouts",
  },
  plan: {
    kicker: "Plan",
    title: "Your trip, at your budget",
    lead: "Choose the landscape and a budget in CLP. Mapucoin builds capsule nights, table and activities of that territory.",
    formKicker: "Planner",
    formTitle: "How much and where?",
    formLead:
      "Choose the landscape and a budget in Chilean pesos. Mapucoin builds capsule, table and activities of that territory.",
    landscape: "Landscape",
    place: "Place to visit",
    previewTitle: "In this territory",
    previewLead:
      "Capsule, table and what you do in the landscape. Build the trip to see the day-by-day itinerary.",
    previewStay: "Stay",
    previewTable: "Table",
    previewActs: "Do",
    previewPass: "Pass",
    more: "+{n}",
    loadingHint: "Capsule, table and activities for your budget.",
    budget: "Total budget · {price}",
    budgetMin: "250 thousand",
    budgetMax: "3.5 million",
    nights: "Nights",
    guests: "Travelers",
    interests: "Interests",
    fromDay: "From {price} per day of experience in {city}.",
    submit: "Build trip",
    ask: "Ask",
    askHint: "Ex: is Pucón or Puerto Varas better with 600 thousand?",
    askPlaceholder: "Write your question…",
    send: "Send",
    you: "You",
    loadingPlan: "Building the itinerary with your budget…",
    loadPlanner: "Loading planner…",
    errorPlan: "Could not build the itinerary.",
    errorNet: "Network error while building the itinerary.",
    empty:
      "Choose a landscape and build the trip. The itinerary appears here, with capsule, table and activities.",
    chatFail: "I could not reply right now.",
  },
  itinerary: {
    kicker: "Itinerary",
    budget: "Budget",
    estimated: "Estimated total",
    remaining: "Left",
    nightsGuests: "Nights · travelers",
    stay: "Capsule",
    table: "Table",
    acts: "Activities",
    day: "Day {n}",
    included: "included",
    bookStay: "Book capsule",
    seeMap: "See on the map",
    passes: "Passes",
    buyPass: "Buy official pass",
    passRates:
      "Chilean adult {adult} × {guests}. Youth {youth}. Chilean child, senior and disabled visitor: free. Foreign adult {foreign}.",
    passStay: "Pass for more than 1 day. One day: {day} per Chilean adult.",
    passZero: "The official listing shows $0. Confirm the price when you buy.",
    passCampana:
      "Granizo sector. Ocoa and Cajón Grande are separate passes at the same fare.",
    passPatagonia:
      "Chacabuco sector. Jeinimeni and Tamango are separate passes at the same fare.",
    passSource:
      "Fare from pasesparques.cl. Mapucoin does not charge the pass: you buy it on the official site.",
  },
  partners: {
    kicker: "Partners",
    title: "Join as a partner",
    lead: "You run a capsule, a ruka, a caleta, a tour or a vineyard. Mapucoin shows you on the map, puts you in the itinerary and charges with Stripe.",
    name: "Name",
    email: "Email",
    phone: "Phone",
    role: "Partner type",
    business: "Business name",
    city: "City / territory",
    notes: "Tell us what you offer",
    submit: "Apply",
    sending: "Sending…",
    incomplete: "Fill in name, email and business.",
    error: "Could not send. Try again.",
    ok: "We received your application",
    okLead:
      "We review your offer and write to activate your listing and Stripe. We do not publish your details until you are approved.",
    invalidEmail: "Enter a valid email.",
    privacy:
      "Your details are not shown to other applicants or on the public map.",
    another: "Send another application",
    okNoDb:
      "We received your application. Connect Supabase to store partners in production.",
    onboardTitle: "Activate Stripe Connect",
    onboardLead:
      "Use the same email from your application. Stripe opens an Express account in Chile (CL).",
    onboardSubmit: "Continue to Stripe",
    onboardBlocked:
      "Stripe could not create a Connect account in Chile. Checkout stays on the Mapucoin platform; the 12% fee is stored for a manual payout.",
    onboardNeedEmail: "Enter the application email.",
    returnTitle: "Onboarding sent",
    returnLead:
      "When Stripe enables charges and payouts, checkout splits the payment (12% platform).",
  },
  partnerRoles: {
    capsula: "Capsule / lodging",
    gastronomia: "Gastronomy",
    actividad: "Activity / tour",
    guia: "Guide",
    transporte: "Transport",
    vina: "Vineyard / distillery",
  },
  awards: {
    kicker: "Awards",
    title: "International awards and recognitions",
    lead: "Chile, Atacama, Santiago, Rapa Nui and Torres del Paine, recognized by World Travel Awards, TIME, Forbes, Tripadvisor and UNESCO.",
    prev: "Previous award",
    next: "Next award",
    goTo: "Go to award {n}",
    of: "{n} of {total}: {title}",
  },
  kinds: {
    place: "Destination",
    capsule: "Capsule",
    food: "Table",
    activity: "Activity",
  },
  landscapes: {
    desierto: "Deserts",
    playa: "Beaches",
    vinedos: "Vineyards",
    volcan: "Volcanoes",
    rios: "Rivers",
    lago: "Lakes",
    "bosque-nativo": "Forests",
    nieve: "Snow",
    parques: "National Parks",
  },
  activitySports: {
    desierto: "Astronomy and sandboarding",
    playa: "Diving and surf",
    vinedos: "Wine tasting",
    volcan: "Trekking, cycling and hot springs",
    rios: "Kayak and rafting",
    lago: "Boats and water sports",
    "bosque-nativo": "Tours and trekking",
    nieve: "Ski and snowboard",
    parques: "Trekking and nature",
  },
  interests: {
    naturaleza: "Nature",
    gastronomia: "Gastronomy",
    cultura: "Culture",
    aventura: "Adventure",
    descanso: "Rest",
    estrellas: "Astronomy",
  },
  from: "from",
  operator: "Run by",
  sound: "Sound",
  mute: "Mute",
  footer: { terms: "Terms", privacy: "Privacy" },
  notFound: {
    title: "Territory not found",
    lead: "That route is not on the Mapucoin map.",
    back: "Back to home",
  },
  destino: {
    videoKicker: "Territory video",
    videoTitle: "{name} in motion",
    videoAlt: "Video of {name}",
    gallery: "Gallery",
    onMap: "On the map",
    from: "Experiences from",
    passFrom: "Chilean adult entry",
    passKicker: "Official pass",
    passAdult: "Chilean {national} · foreign {foreign}",
    passYouth: "Chilean youth {youth} · foreign youth {foreignYouth}",
    passFree: "Chilean children, seniors and disabled visitors enter free.",
    passMulti:
      "More than 1 day: Chilean {national} · foreign {foreign}. One day: {day}.",
    buyPass: "Buy on pasesparques.cl",
    passSource: "Fare published on pasesparques.cl.",
    planThis: "Plan this destination",
    seeCapsule: "See capsule {name}",
    related: "Stay, eat and do",
  },
  reserva: {
    kicker: "Booking",
    title: "Confirm booking",
    canceled: "Payment canceled. You can try again.",
    summary: "{name} · {city}. {nights} · {guests}. Total {total}.",
    night: "night",
    nights: "nights",
    guest: "traveler",
    guests: "travelers",
    capsule: "Capsule",
    name: "Name",
    email: "Email",
    phone: "Phone",
    pay: "Book / Pay",
    included: "Includes",
    perNight: "per night",
    totalLabel: "Total",
    backMap: "Back to the map",
    backCapsule: "Back to the capsule",
    invalidName: "Enter your name (at least 2 letters).",
    invalidEmail: "Enter a valid email.",
    rateLimited: "Too many attempts. Wait a moment and try again.",
    secure: "Secure payment with Stripe",
    platformNote:
      "Charged in CLP on Mapucoin. If the partner is not Connect-ready yet, payment stays on the platform.",
    fromPrice: "From {price} / night",
    paying: "Redirecting to Stripe…",
    creating: "Creating Stripe session…",
    noStripe: "Stripe is not configured. Add STRIPE_SECRET_KEY in Vercel.",
    fail: "Could not start payment. Check the details.",
    okKicker: "Done",
    okTitle: "Booking confirmed",
    okLead:
      "Stripe recorded the payment. We will write with capsule check-in and the rest of the itinerary.",
    okCta: "Back to the map",
    okAmount: "Amount",
    okCapsule: "Capsule",
    okNights: "Nights",
    okGuests: "Travelers",
    okEmail: "Email",
    okPending: "Confirming the payment…",
    okMissing:
      "We could not find the session. If you were charged, the receipt arrives by email.",
    okPaid: "Paid",
  },
  catalogEmpty: "No listings in this landscape.",
  awardTitles: {
    "Mejor Destino de Turismo Aventura del Mundo":
      "World's Leading Adventure Tourism Destination",
    "Mejor Destino Romántico": "Leading Romantic Destination",
    "Mejor Destino de Sudamérica": "Leading Destination in South America",
    "Mejor Destino Verde": "Leading Green Destination",
    "Mejor Destino de Naturaleza": "Leading Nature Destination",
    "Mejor Ciudad": "Leading City",
    "Mejor Destino de Cruceros": "Leading Cruise Destination",
    "Mejor Destino Internacional": "Leading International Destination",
    "Solo Travel — 4° mundial": "Solo Travel — 4th worldwide",
    "Top South American Destination": "Top South American Destination",
    "Reserva de la Biósfera": "Biosphere Reserve",
    "Mejor Viñedo del Mundo": "World's Best Vineyard",
    "World's Greatest Places": "World's Greatest Places",
    "Patrimonio de la Humanidad": "World Heritage",
    "Mejor lugar del mundo para observación de estrellas":
      "Best place in the world for stargazing",
    "El radiotelescopio más grande del mundo":
      "The world's largest radio telescope",
  },
  awardNotes: {
    "7ª vez": "7th time",
    "Octava Maravilla del Mundo": "Eighth Wonder of the World",
    "Postulación a premio de gobernanza": "Nomination for a governance award",
    "Estancia Mercedes (Magallanes), Pared Sur Camp (Aysén) y Ephedra Restaurant (Antofagasta)":
      "Estancia Mercedes (Magallanes), Pared Sur Camp (Aysén) and Ephedra Restaurant (Antofagasta)",
    Astroturismo: "Astrotourism",
  },
  legalTermsTitle: "Terms and Conditions",
  legalPrivacyTitle: "Privacy Policy",
};

const pt: typeof es = {
  skip: "Saltar para o conteúdo",
  language: "Idioma",
  nav: {
    why: "Por que o Chile",
    map: "Mapa",
    capsules: "Cápsulas",
    food: "Gastronomia",
    activities: "Atividades",
    partners: "Partners",
    awards: "Prêmios",
    plan: "Planejar",
    app: "App",
    login: "Entrar",
    signup: "Criar conta",
    logout: "Sair",
    menu: "Menu",
    prev: "Anterior",
    next: "Seguinte",
  },
  hero: {
    title: "Chile, do norte ao sul.",
    lead: "Cápsulas de cobre e vidro em desertos, praias, vinhedos, vulcões, rios, lagos, florestas, neve e parques nacionais. Mesa local e orçamento em CLP.",
    planCta: "Planejar",
    appCta: "Abrir App",
  },
  whyChile: {
    kicker: "Viagem infinita",
    title: "Por que o Chile?",
    lead: "Trinta segundos pelo país, do norte ao sul.",
    video: "Por que o Chile, versão em português",
  },
  map: {
    kicker: "Mapa",
    title: "Chile classificado por paisagem",
    lead: "Filtre desertos, praias, vinhedos, vulcões, rios, lagos, florestas, neve e os 48 parques nacionais com passe digital. Cada pin é um território com a sua cápsula.",
    all: "Todos",
    places: "Lugares",
    capsules: "Cápsulas",
    partners: "Partners",
    both: "Todos",
    legend: "Isologo Mapucoin",
    loading: "Carregando o mapa do Chile…",
    viewSheet: "Ver ficha →",
    destination: "Destino",
    capsule: "Cápsula",
    partner: "Partner",
    search: "Buscar destino, cápsula ou partner",
    searchEmpty: "Sem resultados",
    searchClear: "Limpar busca",
    emptyPartners: "Ainda não há partners aprovados no mapa.",
    emptyPartnersHint:
      "Quando um partner local for aprovado, o pin aparece aqui.",
  },
  capsules: {
    kicker: "Cápsulas",
    title: "Cada paisagem, uma casa cápsula",
    lead: "Cobre, vidro e madeira. Off-grid opcional, isolamento de −40 °C a 40 °C. Uma cápsula por paisagem — também em parques nacionais — operada por partners locais.",
    alt: "Casa cápsula Mapucoin",
    fromNight: "a partir de {price} / noite",
    perNight: "Por noite",
    upTo: "Até {n} viajantes · {region}",
    book: "Reservar",
    canceled: "Pagamento cancelado. Você pode reservar de novo quando quiser.",
    explore: "Explorar {name} →",
    location: "Localização",
    interiorAlt: "Interior de cobre, madeira e vidro",
  },
  food: {
    kicker: "Gastronomia",
    title: "A mesa do território",
    lead: "Curanto, empanadas de pino, pastel de choclo, caldillo de congrio, mote con huesillos e a mesa de cada território. Com partners locais.",
    hours: "{price} · {hours} h",
  },
  activities: {
    kicker: "Atividades",
    title: "O que se faz no território",
    lead: "Classificadas por paisagem: astronomia e sandboard no deserto, mergulho e surf na praia, degustação nos vinhedos, trekking e termas nos vulcões, caiaque e rafting nos rios, barcos nos lagos, tours na floresta, ski na neve.",
    other: "Outros",
    otherSports: "Cultura, amaheceres e mirantes",
  },
  plan: {
    kicker: "Planejar",
    title: "Sua viagem, no seu orçamento",
    lead: "Escolha a paisagem e o orçamento em CLP. A Mapucoin arma noites em cápsula, mesa e atividades desse território.",
    formKicker: "Planejador",
    formTitle: "Quanto e para onde?",
    formLead:
      "Escolha a paisagem e o orçamento em pesos chilenos. A Mapucoin arma cápsula, mesa e atividades desse território.",
    landscape: "Paisagem",
    place: "Lugar a conhecer",
    previewTitle: "Neste território",
    previewLead:
      "Cápsula, mesa e o que se faz na paisagem. Arme a viagem para ver o itinerário dia a dia.",
    previewStay: "Dormir",
    previewTable: "Mesa",
    previewActs: "Fazer",
    previewPass: "Passe",
    more: "+{n}",
    loadingHint: "Cápsula, mesa e atividades segundo o seu orçamento.",
    budget: "Orçamento total · {price}",
    budgetMin: "250 mil",
    budgetMax: "3,5 milhões",
    nights: "Noites",
    guests: "Viajantes",
    interests: "Interesses",
    fromDay: "A partir de {price} por dia de experiência em {city}.",
    submit: "Armar viagem",
    ask: "Perguntar",
    askHint: "Ex: vale mais Pucón ou Puerto Varas com 600 mil?",
    askPlaceholder: "Escreva sua consulta…",
    send: "Enviar",
    you: "Você",
    loadingPlan: "Armando o itinerário com o seu orçamento…",
    loadPlanner: "Carregando o planejador…",
    errorPlan: "Não foi possível armar o itinerário.",
    errorNet: "Erro de rede ao armar o itinerário.",
    empty:
      "Escolha uma paisagem e arme a viagem. O itinerário aparece aqui, com cápsula, mesa e atividades.",
    chatFail: "não pude responder agora.",
  },
  itinerary: {
    kicker: "Itinerário",
    budget: "Orçamento",
    estimated: "Total estimado",
    remaining: "Sobra",
    nightsGuests: "Noites · viajantes",
    stay: "Cápsula",
    table: "Mesa",
    acts: "Atividades",
    day: "Dia {n}",
    included: "incluído",
    bookStay: "Reservar cápsula",
    seeMap: "Ver no mapa",
    passes: "Passes",
    buyPass: "Comprar passe oficial",
    passRates:
      "Adulto nacional {adult} × {guests}. Jovem {youth}. Criança, idoso e pessoa com deficiência nacional: sem custo. Estrangeiro adulto {foreign}.",
    passStay: "Passe de mais de 1 dia. Um dia: {day} por adulto nacional.",
    passZero: "A ficha oficial publica $0. Confirme o valor ao comprar.",
    passCampana:
      "Setor Granizo. Ocoa e Cajón Grande compram-se à parte, na mesma tarifa.",
    passPatagonia:
      "Setor Chacabuco. Jeinimeni e Tamango compram-se à parte, na mesma tarifa.",
    passSource:
      "Tarifa de pasesparques.cl. A Mapucoin não cobra o passe: a compra é no site oficial.",
  },
  partners: {
    kicker: "Partners",
    title: "Entre como partner",
    lead: "Você opera uma cápsula, uma ruka, uma caleta, um tour ou uma vinícola. A Mapucoin mostra no mapa, entra no itinerário e cobra com Stripe.",
    name: "Nome",
    email: "E-mail",
    phone: "Telefone",
    role: "Tipo de partner",
    business: "Nome do negócio",
    city: "Cidade / território",
    notes: "Conte sua oferta",
    submit: "Candidatar",
    sending: "Enviando…",
    incomplete: "Preencha nome, e-mail e negócio.",
    error: "Não foi possível enviar. Tente de novo.",
    ok: "Recebemos a sua candidatura",
    okLead:
      "Revisamos a oferta e escrevemos para ativar a ficha e o Stripe. Não publicamos os seus dados até aprovar.",
    invalidEmail: "Informe um e-mail válido.",
    privacy:
      "Os seus dados não aparecem para outros candidatos nem no mapa público.",
    another: "Enviar outra candidatura",
    okNoDb:
      "Recebemos a sua candidatura. Conecte o Supabase para guardar partners em produção.",
    onboardTitle: "Ativar Stripe Connect",
    onboardLead:
      "Use o mesmo e-mail da candidatura. A Stripe abre uma conta Express no Chile (CL).",
    onboardSubmit: "Continuar na Stripe",
    onboardBlocked:
      "A Stripe não pôde criar a conta Connect no Chile. O cobro segue na plataforma Mapucoin; os 12% ficam contabilizados para payout manual.",
    onboardNeedEmail: "Informe o e-mail da candidatura.",
    returnTitle: "Onboarding enviado",
    returnLead:
      "Quando a Stripe ativar charges e payouts, o checkout reparte o pagamento (12% plataforma).",
  },
  partnerRoles: {
    capsula: "Cápsula / hospedagem",
    gastronomia: "Gastronomia",
    actividad: "Atividade / tour",
    guia: "Guia",
    transporte: "Transporte",
    vina: "Vinícola / destilaria",
  },
  awards: {
    kicker: "Prêmios",
    title: "Prêmios e reconhecimentos internacionais",
    lead: "Chile, Atacama, Santiago, Rapa Nui e Torres del Paine, distinguidos por World Travel Awards, TIME, Forbes, Tripadvisor e UNESCO.",
    prev: "Prêmio anterior",
    next: "Prêmio seguinte",
    goTo: "Ir ao prêmio {n}",
    of: "{n} de {total}: {title}",
  },
  kinds: {
    place: "Destino",
    capsule: "Cápsula",
    food: "Mesa",
    activity: "Atividade",
  },
  landscapes: {
    desierto: "Desertos",
    playa: "Praias",
    vinedos: "Vinhedos",
    volcan: "Vulcões",
    rios: "Rios",
    lago: "Lagos",
    "bosque-nativo": "Florestas",
    nieve: "Neve",
    parques: "Parques Nacionais",
  },
  activitySports: {
    desierto: "Astronomia e sandboard",
    playa: "Mergulho e surf",
    vinedos: "Degustação de vinhos",
    volcan: "Trekking, ciclismo e termas",
    rios: "Caiaque e rafting",
    lago: "Barcos e esportes náuticos",
    "bosque-nativo": "Tours e trekking",
    nieve: "Ski e snowboard",
    parques: "Trekking e natureza",
  },
  interests: {
    naturaleza: "Natureza",
    gastronomia: "Gastronomia",
    cultura: "Cultura",
    aventura: "Aventura",
    descanso: "Descanso",
    estrellas: "Astronomia",
  },
  from: "a partir de",
  operator: "Operado por",
  sound: "Som",
  mute: "Mudo",
  footer: { terms: "Terms", privacy: "Privacy" },
  notFound: {
    title: "Território não encontrado",
    lead: "Essa rota não está no mapa Mapucoin.",
    back: "Voltar ao início",
  },
  destino: {
    videoKicker: "Vídeo do território",
    videoTitle: "{name} em movimento",
    videoAlt: "Vídeo de {name}",
    gallery: "Galeria",
    onMap: "No mapa",
    from: "Experiências a partir de",
    passFrom: "Entrada adulto nacional",
    passKicker: "Passe oficial",
    passAdult: "Nacional {national} · estrangeiro {foreign}",
    passYouth: "Jovem nacional {youth} · jovem estrangeiro {foreignYouth}",
    passFree:
      "Criança, idoso e pessoa com deficiência nacional entram sem custo.",
    passMulti:
      "Mais de 1 dia: nacional {national} · estrangeiro {foreign}. Um dia: {day}.",
    buyPass: "Comprar em pasesparques.cl",
    passSource: "Tarifa publicada em pasesparques.cl.",
    planThis: "Planejar este destino",
    seeCapsule: "Ver cápsula {name}",
    related: "Dormir, comer e fazer",
  },
  reserva: {
    kicker: "Reserva",
    title: "Confirmar reserva",
    canceled: "Pagamento cancelado. Você pode tentar de novo.",
    summary: "{name} · {city}. {nights} · {guests}. Total {total}.",
    night: "noite",
    nights: "noites",
    guest: "viajante",
    guests: "viajantes",
    capsule: "Cápsula",
    name: "Nome",
    email: "E-mail",
    phone: "Telefone",
    pay: "Reservar / Pagar",
    included: "Inclui",
    perNight: "por noite",
    totalLabel: "Total",
    backMap: "Voltar ao mapa",
    backCapsule: "Voltar à cápsula",
    invalidName: "Escreva o seu nome (mínimo 2 letras).",
    invalidEmail: "Informe um e-mail válido.",
    rateLimited: "Demasiadas tentativas. Espere um momento e tente de novo.",
    secure: "Pagamento seguro com Stripe",
    platformNote:
      "Cobrança em CLP na Mapucoin. Se o partner ainda não tem Stripe Connect, o pagamento fica na plataforma.",
    fromPrice: "A partir de {price} / noite",
    paying: "A redirecionar para o Stripe…",
    creating: "Criando sessão Stripe…",
    noStripe: "O Stripe não está configurado. Adicione STRIPE_SECRET_KEY na Vercel.",
    fail: "Não foi possível iniciar o pagamento. Revise os dados.",
    okKicker: "Pronto",
    okTitle: "Reserva confirmada",
    okLead:
      "O Stripe registrou o pagamento. Escrevemos com o check-in da cápsula e o resto do itinerário.",
    okCta: "Voltar ao mapa",
    okAmount: "Montante",
    okCapsule: "Cápsula",
    okNights: "Noites",
    okGuests: "Viajantes",
    okEmail: "E-mail",
    okPending: "A confirmar o pagamento…",
    okMissing:
      "Não encontramos a sessão. Se o cargo foi feito, o comprovante chega ao e-mail.",
    okPaid: "Pago",
  },
  catalogEmpty: "Não há fichas nesta paisagem.",
  awardTitles: {
    "Mejor Destino de Turismo Aventura del Mundo":
      "Melhor Destino de Turismo de Aventura do Mundo",
    "Mejor Destino Romántico": "Melhor Destino Romântico",
    "Mejor Destino de Sudamérica": "Melhor Destino da América do Sul",
    "Mejor Destino Verde": "Melhor Destino Verde",
    "Mejor Destino de Naturaleza": "Melhor Destino de Natureza",
    "Mejor Ciudad": "Melhor Cidade",
    "Mejor Destino de Cruceros": "Melhor Destino de Cruzeiros",
    "Mejor Destino Internacional": "Melhor Destino Internacional",
    "Solo Travel — 4° mundial": "Solo Travel — 4º mundial",
    "Top South American Destination": "Top South American Destination",
    "Reserva de la Biósfera": "Reserva da Biosfera",
    "Mejor Viñedo del Mundo": "Melhor Vinhedo do Mundo",
    "World's Greatest Places": "World's Greatest Places",
    "Patrimonio de la Humanidad": "Patrimônio da Humanidade",
    "Mejor lugar del mundo para observación de estrellas":
      "Melhor lugar do mundo para observação de estrelas",
    "El radiotelescopio más grande del mundo":
      "O radiotelescópio mais grande do mundo",
  },
  awardNotes: {
    "7ª vez": "7ª vez",
    "Octava Maravilla del Mundo": "Oitava Maravilha do Mundo",
    "Postulación a premio de gobernanza": "Indicação a prêmio de governança",
    "Estancia Mercedes (Magallanes), Pared Sur Camp (Aysén) y Ephedra Restaurant (Antofagasta)":
      "Estancia Mercedes (Magallanes), Pared Sur Camp (Aysén) e Ephedra Restaurant (Antofagasta)",
    Astroturismo: "Astroturismo",
  },
  legalTermsTitle: "Termos e Condições",
  legalPrivacyTitle: "Política de Privacidade",
};

const fr: typeof es = {
  skip: "Aller au contenu",
  language: "Langue",
  nav: {
    why: "Pourquoi le Chili",
    map: "Carte",
    capsules: "Capsules",
    food: "Gastronomie",
    activities: "Activités",
    partners: "Partenaires",
    awards: "Prix",
    plan: "Planifier",
    app: "App",
    login: "Connexion",
    signup: "Créer un compte",
    logout: "Sortir",
    menu: "Menu",
    prev: "Précédent",
    next: "Suivant",
  },
  hero: {
    title: "Le Chili, du nord au sud.",
    lead: "Capsules de cuivre et de verre dans les déserts, plages, vignobles, volcans, rivières, lacs, forêts, neige et parcs nationaux. Table locale et budget en CLP.",
    planCta: "Planifier",
    appCta: "Ouvrir l’App",
  },
  whyChile: {
    kicker: "Voyage infini",
    title: "Pourquoi le Chili ?",
    lead: "Trente secondes à travers le pays, du nord au sud.",
    video: "Pourquoi le Chili, version française",
  },
  map: {
    kicker: "Carte",
    title: "Le Chili classé par paysage",
    lead: "Filtrez déserts, plages, vignobles, volcans, rivières, lacs, forêts, neige et les 48 parcs nationaux avec un pass numérique. Chaque pin est un territoire avec sa capsule.",
    all: "Tous",
    places: "Lieux",
    capsules: "Capsules",
    partners: "Partenaires",
    both: "Tous",
    legend: "Isologo Mapucoin",
    loading: "Chargement de la carte du Chili…",
    viewSheet: "Voir la fiche →",
    destination: "Destination",
    capsule: "Capsule",
    partner: "Partenaire",
    search: "Rechercher une destination, une capsule ou un partenaire",
    searchEmpty: "Aucun résultat",
    searchClear: "Effacer la recherche",
    emptyPartners: "Aucun partenaire approuvé sur la carte pour l’instant.",
    emptyPartnersHint:
      "Lorsqu’un partenaire local est approuvé, son pin apparaît ici.",
  },
  capsules: {
    kicker: "Capsules",
    title: "Chaque paysage, une maison capsule",
    lead: "Cuivre, verre et bois. Hors réseau en option, isolation de −40 °C à 40 °C. Une capsule par paysage — aussi dans les parcs nationaux — gérée par des partenaires locaux.",
    alt: "Maison capsule Mapucoin",
    fromNight: "à partir de {price} / nuit",
    perNight: "Par nuit",
    upTo: "Jusqu'à {n} voyageurs · {region}",
    book: "Réserver",
    canceled: "Paiement annulé. Vous pouvez réserver à nouveau quand vous voulez.",
    explore: "Explorer {name} →",
    location: "Emplacement",
    interiorAlt: "Intérieur cuivre, bois et verre",
  },
  food: {
    kicker: "Gastronomie",
    title: "La table du territoire",
    lead: "Curanto, empanadas de pino, pastel de choclo, caldillo de congrio, mote con huesillos et la table de chaque territoire. Avec des partenaires locaux.",
    hours: "{price} · {hours} h",
  },
  activities: {
    kicker: "Activités",
    title: "Ce que l'on fait sur le territoire",
    lead: "Classées par paysage : astronomie et sandboard dans le désert, plongée et surf à la plage, dégustation dans les vignobles, trekking et thermes sur les volcans, kayak et rafting sur les rivières, bateaux sur les lacs, tours en forêt, ski dans la neige.",
    other: "Autres",
    otherSports: "Culture, aubes et belvédères",
  },
  plan: {
    kicker: "Planifier",
    title: "Votre voyage, à votre budget",
    lead: "Choisissez le paysage et un budget en CLP. Mapucoin compose nuits en capsule, table et activités de ce territoire.",
    formKicker: "Planificateur",
    formTitle: "Combien et où ?",
    formLead:
      "Choisissez le paysage et un budget en pesos chiliens. Mapucoin compose capsule, table et activités de ce territoire.",
    landscape: "Paysage",
    place: "Lieu à découvrir",
    previewTitle: "Sur ce territoire",
    previewLead:
      "Capsule, table et ce que l'on fait dans le paysage. Composez le voyage pour voir l'itinéraire jour par jour.",
    previewStay: "Dormir",
    previewTable: "Table",
    previewActs: "Faire",
    previewPass: "Pass",
    more: "+{n}",
    loadingHint: "Capsule, table et activités selon votre budget.",
    budget: "Budget total · {price}",
    budgetMin: "250 mille",
    budgetMax: "3,5 millions",
    nights: "Nuits",
    guests: "Voyageurs",
    interests: "Intérêts",
    fromDay: "À partir de {price} par jour d'expérience à {city}.",
    submit: "Composer le voyage",
    ask: "Demander",
    askHint: "Ex. : Pucón ou Puerto Varas convient mieux avec 600 mille ?",
    askPlaceholder: "Écrivez votre question…",
    send: "Envoyer",
    you: "Vous",
    loadingPlan: "Composition de l'itinéraire avec votre budget…",
    loadPlanner: "Chargement du planificateur…",
    errorPlan: "Impossible de composer l'itinéraire.",
    errorNet: "Erreur réseau lors de la composition de l'itinéraire.",
    empty:
      "Choisissez un paysage et composez le voyage. L'itinéraire apparaît ici, avec capsule, table et activités.",
    chatFail: "je n'ai pas pu répondre pour le moment.",
  },
  itinerary: {
    kicker: "Itinéraire",
    budget: "Budget",
    estimated: "Total estimé",
    remaining: "Reste",
    nightsGuests: "Nuits · voyageurs",
    stay: "Capsule",
    table: "Table",
    acts: "Activités",
    day: "Jour {n}",
    included: "inclus",
    bookStay: "Réserver la capsule",
    seeMap: "Voir sur la carte",
    passes: "Pass",
    buyPass: "Acheter le pass officiel",
    passRates:
      "Adulte chilien {adult} × {guests}. Jeune {youth}. Enfant, senior et handicap chilien : gratuit. Adulte étranger {foreign}.",
    passStay: "Pass de plus d'un jour. Un jour : {day} par adulte chilien.",
    passZero: "La fiche officielle affiche 0 $. Confirmez le prix à l'achat.",
    passCampana:
      "Secteur Granizo. Ocoa et Cajón Grande s'achètent à part, au même tarif.",
    passPatagonia:
      "Secteur Chacabuco. Jeinimeni et Tamango s'achètent à part, au même tarif.",
    passSource:
      "Tarif de pasesparques.cl. Mapucoin n'encaisse pas le pass : l'achat se fait sur le site officiel.",
  },
  partners: {
    kicker: "Partenaires",
    title: "Devenir partenaire",
    lead: "Vous exploitez une capsule, une ruka, une caleta, un tour ou un vignoble. Mapucoin vous montre sur la carte, vous entre dans l'itinéraire et encaisse avec Stripe.",
    name: "Nom",
    email: "E-mail",
    phone: "Téléphone",
    role: "Type de partenaire",
    business: "Nom de l'activité",
    city: "Ville / territoire",
    notes: "Parlez-nous de votre offre",
    submit: "Postuler",
    sending: "Envoi…",
    incomplete: "Complétez nom, e-mail et activité.",
    error: "Envoi impossible. Réessayez.",
    ok: "Nous avons reçu votre candidature",
    okLead:
      "Nous examinons l’offre et vous écrivons pour activer la fiche et Stripe. Vos données ne sont pas publiées avant l’approbation.",
    invalidEmail: "Saisissez un e-mail valide.",
    privacy:
      "Vos données ne sont pas montrées aux autres candidats ni sur la carte publique.",
    another: "Envoyer une autre candidature",
    okNoDb:
      "Nous avons reçu votre candidature. Connectez Supabase pour enregistrer les partenaires en production.",
    onboardTitle: "Activer Stripe Connect",
    onboardLead:
      "Utilisez le même e-mail que votre candidature. Stripe ouvre un compte Express au Chili (CL).",
    onboardSubmit: "Continuer vers Stripe",
    onboardBlocked:
      "Stripe n’a pas pu créer le compte Connect au Chili. Le paiement reste sur la plateforme Mapucoin ; les 12 % sont comptabilisés pour un payout manuel.",
    onboardNeedEmail: "Saisissez l’e-mail de la candidature.",
    returnTitle: "Onboarding envoyé",
    returnLead:
      "Lorsque Stripe active charges et payouts, le checkout partage le paiement (12 % plateforme).",
  },
  partnerRoles: {
    capsula: "Capsule / hébergement",
    gastronomia: "Gastronomie",
    actividad: "Activité / tour",
    guia: "Guide",
    transporte: "Transport",
    vina: "Vignoble / distillerie",
  },
  awards: {
    kicker: "Prix",
    title: "Prix et reconnaissances internationales",
    lead: "Le Chili, Atacama, Santiago, Rapa Nui et Torres del Paine, distingués par World Travel Awards, TIME, Forbes, Tripadvisor et l'UNESCO.",
    prev: "Prix précédent",
    next: "Prix suivant",
    goTo: "Aller au prix {n}",
    of: "{n} sur {total} : {title}",
  },
  kinds: {
    place: "Destination",
    capsule: "Capsule",
    food: "Table",
    activity: "Activité",
  },
  landscapes: {
    desierto: "Déserts",
    playa: "Plages",
    vinedos: "Vignobles",
    volcan: "Volcans",
    rios: "Rivières",
    lago: "Lacs",
    "bosque-nativo": "Forêts",
    nieve: "Neige",
    parques: "Parcs nationaux",
  },
  activitySports: {
    desierto: "Astronomie et sandboard",
    playa: "Plongée et surf",
    vinedos: "Dégustation de vins",
    volcan: "Trekking, cyclisme et thermes",
    rios: "Kayak et rafting",
    lago: "Bateaux et sports nautiques",
    "bosque-nativo": "Tours et trekking",
    nieve: "Ski et snowboard",
    parques: "Trekking et nature",
  },
  interests: {
    naturaleza: "Nature",
    gastronomia: "Gastronomie",
    cultura: "Culture",
    aventura: "Aventure",
    descanso: "Repos",
    estrellas: "Astronomie",
  },
  from: "à partir de",
  operator: "Assuré par",
  sound: "Son",
  mute: "Muet",
  footer: { terms: "Terms", privacy: "Privacy" },
  notFound: {
    title: "Territoire introuvable",
    lead: "Cet itinéraire n'est pas sur la carte Mapucoin.",
    back: "Retour à l'accueil",
  },
  destino: {
    videoKicker: "Vidéo du territoire",
    videoTitle: "{name} en mouvement",
    videoAlt: "Vidéo de {name}",
    gallery: "Galerie",
    onMap: "Sur la carte",
    from: "Expériences à partir de",
    passFrom: "Entrée adulte chilien",
    passKicker: "Pass officiel",
    passAdult: "Chilien {national} · étranger {foreign}",
    passYouth: "Jeune chilien {youth} · jeune étranger {foreignYouth}",
    passFree:
      "Enfant, senior et personne handicapée chiliens entrent sans frais.",
    passMulti:
      "Plus d'un jour : chilien {national} · étranger {foreign}. Un jour : {day}.",
    buyPass: "Acheter sur pasesparques.cl",
    passSource: "Tarif publié sur pasesparques.cl.",
    planThis: "Planifier cette destination",
    seeCapsule: "Voir la capsule {name}",
    related: "Dormir, manger et faire",
  },
  reserva: {
    kicker: "Réservation",
    title: "Confirmer la réservation",
    canceled: "Paiement annulé. Vous pouvez réessayer.",
    summary: "{name} · {city}. {nights} · {guests}. Total {total}.",
    night: "nuit",
    nights: "nuits",
    guest: "voyageur",
    guests: "voyageurs",
    capsule: "Capsule",
    name: "Nom",
    email: "E-mail",
    phone: "Téléphone",
    pay: "Réserver / Payer",
    included: "Inclus",
    perNight: "par nuit",
    totalLabel: "Total",
    backMap: "Retour à la carte",
    backCapsule: "Retour à la capsule",
    invalidName: "Indiquez votre nom (2 lettres minimum).",
    invalidEmail: "Saisissez un e-mail valide.",
    rateLimited: "Trop de tentatives. Patientez un moment et réessayez.",
    secure: "Paiement sécurisé avec Stripe",
    platformNote:
      "Paiement en CLP sur Mapucoin. Si le partenaire n’a pas encore Stripe Connect, le paiement reste sur la plateforme.",
    fromPrice: "À partir de {price} / nuit",
    paying: "Redirection vers Stripe…",
    creating: "Création de la session Stripe…",
    noStripe: "Stripe n'est pas configuré. Ajoutez STRIPE_SECRET_KEY dans Vercel.",
    fail: "Impossible de lancer le paiement. Vérifiez les données.",
    okKicker: "C'est fait",
    okTitle: "Réservation confirmée",
    okLead:
      "Stripe a enregistré le paiement. Nous écrivons avec le check-in de la capsule et le reste de l'itinéraire.",
    okCta: "Retour à la carte",
    okAmount: "Montant",
    okCapsule: "Capsule",
    okNights: "Nuits",
    okGuests: "Voyageurs",
    okEmail: "E-mail",
    okPending: "Confirmation du paiement…",
    okMissing:
      "Session introuvable. Si le paiement a été débité, le reçu arrive par e-mail.",
    okPaid: "Payé",
  },
  catalogEmpty: "Aucune fiche dans ce paysage.",
  awardTitles: {
    "Mejor Destino de Turismo Aventura del Mundo":
      "Meilleure destination d'aventure au monde",
    "Mejor Destino Romántico": "Meilleure destination romantique",
    "Mejor Destino de Sudamérica": "Meilleure destination d'Amérique du Sud",
    "Mejor Destino Verde": "Meilleure destination verte",
    "Mejor Destino de Naturaleza": "Meilleure destination nature",
    "Mejor Ciudad": "Meilleure ville",
    "Mejor Destino de Cruceros": "Meilleure destination de croisière",
    "Mejor Destino Internacional": "Meilleure destination internationale",
    "Solo Travel — 4° mundial": "Solo Travel — 4e mondial",
    "Top South American Destination": "Top South American Destination",
    "Reserva de la Biósfera": "Réserve de biosphère",
    "Mejor Viñedo del Mundo": "Meilleur vignoble du monde",
    "World's Greatest Places": "World's Greatest Places",
    "Patrimonio de la Humanidad": "Patrimoine mondial",
    "Mejor lugar del mundo para observación de estrellas":
      "Meilleur lieu au monde pour observer les étoiles",
    "El radiotelescopio más grande del mundo":
      "Le plus grand radiotélescope du monde",
  },
  awardNotes: {
    "7ª vez": "7e fois",
    "Octava Maravilla del Mundo": "Huitième merveille du monde",
    "Postulación a premio de gobernanza": "Candidature à un prix de gouvernance",
    "Estancia Mercedes (Magallanes), Pared Sur Camp (Aysén) y Ephedra Restaurant (Antofagasta)":
      "Estancia Mercedes (Magallanes), Pared Sur Camp (Aysén) et Ephedra Restaurant (Antofagasta)",
    Astroturismo: "Astrotourisme",
  },
  legalTermsTitle: "Conditions générales",
  legalPrivacyTitle: "Politique de confidentialité",
};

const it: typeof es = {
  skip: "Salta al contenuto",
  language: "Lingua",
  nav: {
    why: "Perché il Cile",
    map: "Mappa",
    capsules: "Capsule",
    food: "Gastronomia",
    activities: "Attività",
    partners: "Partner",
    awards: "Premi",
    plan: "Pianifica",
    app: "App",
    login: "Accedi",
    signup: "Crea account",
    logout: "Esci",
    menu: "Menu",
    prev: "Precedente",
    next: "Successivo",
  },
  hero: {
    title: "Il Cile, da nord a sud.",
    lead: "Capsule di rame e vetro in deserti, spiagge, vigneti, vulcani, fiumi, laghi, boschi, neve e parchi nazionali. Tavola locale e budget in CLP.",
    planCta: "Pianifica",
    appCta: "Apri App",
  },
  whyChile: {
    kicker: "Viaggio infinito",
    title: "Perché il Cile?",
    lead: "Trenta secondi attraverso il paese, da nord a sud.",
    video: "Perché il Cile, versione in inglese",
  },
  map: {
    kicker: "Mappa",
    title: "Il Cile classificato per paesaggio",
    lead: "Filtra deserti, spiagge, vigneti, vulcani, fiumi, laghi, boschi, neve e i 48 parchi nazionali con pass digitale. Ogni pin è un territorio con la sua capsula.",
    all: "Tutti",
    places: "Luoghi",
    capsules: "Capsule",
    partners: "Partner",
    both: "Tutti",
    legend: "Isologo Mapucoin",
    loading: "Caricamento della mappa del Cile…",
    viewSheet: "Vedi scheda →",
    destination: "Destinazione",
    capsule: "Capsula",
    partner: "Partner",
    search: "Cerca destinazione, capsula o partner",
    searchEmpty: "Nessun risultato",
    searchClear: "Cancella ricerca",
    emptyPartners: "Non ci sono ancora partner approvati sulla mappa.",
    emptyPartnersHint:
      "Quando un partner locale viene approvato, il pin appare qui.",
  },
  capsules: {
    kicker: "Capsule",
    title: "Ogni paesaggio, una casa capsula",
    lead: "Rame, vetro e legno. Off-grid opzionale, isolamento da −40 °C a 40 °C. Una capsula per paesaggio — anche nei parchi nazionali — gestita da partner locali.",
    alt: "Casa capsula Mapucoin",
    fromNight: "da {price} / notte",
    perNight: "A notte",
    upTo: "Fino a {n} viaggiatori · {region}",
    book: "Prenota",
    canceled: "Pagamento annullato. Puoi prenotare di nuovo quando vuoi.",
    explore: "Esplora {name} →",
    location: "Posizione",
    interiorAlt: "Interno in rame, legno e vetro",
  },
  food: {
    kicker: "Gastronomia",
    title: "La tavola del territorio",
    lead: "Curanto, empanadas de pino, pastel de choclo, caldillo de congrio, mote con huesillos e la tavola di ogni territorio. Con partner locali.",
    hours: "{price} · {hours} h",
  },
  activities: {
    kicker: "Attività",
    title: "Cosa si fa nel territorio",
    lead: "Classificate per paesaggio: astronomia e sandboard nel deserto, immersioni e surf in spiaggia, degustazione nei vigneti, trekking e terme sui vulcani, kayak e rafting sui fiumi, barche sui laghi, tour nel bosco, sci sulla neve.",
    other: "Altri",
    otherSports: "Cultura, albe e belvedere",
  },
  plan: {
    kicker: "Pianifica",
    title: "Il tuo viaggio, al tuo budget",
    lead: "Scegli il paesaggio e il budget in CLP. Mapucoin compone notti in capsula, tavola e attività di quel territorio.",
    formKicker: "Pianificatore",
    formTitle: "Quanto e dove?",
    formLead:
      "Scegli il paesaggio e il budget in pesos cileni. Mapucoin compone capsula, tavola e attività di quel territorio.",
    landscape: "Paesaggio",
    place: "Luogo da conoscere",
    previewTitle: "In questo territorio",
    previewLead:
      "Capsula, tavola e ciò che si fa nel paesaggio. Componi il viaggio per vedere l'itinerario giorno per giorno.",
    previewStay: "Dormire",
    previewTable: "Tavola",
    previewActs: "Fare",
    previewPass: "Pass",
    more: "+{n}",
    loadingHint: "Capsula, tavola e attività secondo il tuo budget.",
    budget: "Budget totale · {price}",
    budgetMin: "250 mila",
    budgetMax: "3,5 milioni",
    nights: "Notti",
    guests: "Viaggiatori",
    interests: "Interessi",
    fromDay: "Da {price} al giorno di esperienza a {city}.",
    submit: "Comporre il viaggio",
    ask: "Chiedi",
    askHint: "Es: conviene di più Pucón o Puerto Varas con 600 mila?",
    askPlaceholder: "Scrivi la tua domanda…",
    send: "Invia",
    you: "Tu",
    loadingPlan: "Composizione dell'itinerario con il tuo budget…",
    loadPlanner: "Caricamento del pianificatore…",
    errorPlan: "Impossibile comporre l'itinerario.",
    errorNet: "Errore di rete nella composizione dell'itinerario.",
    empty:
      "Scegli un paesaggio e componi il viaggio. L'itinerario appare qui, con capsula, tavola e attività.",
    chatFail: "non ho potuto rispondere ora.",
  },
  itinerary: {
    kicker: "Itinerario",
    budget: "Budget",
    estimated: "Totale stimato",
    remaining: "Resta",
    nightsGuests: "Notti · viaggiatori",
    stay: "Capsula",
    table: "Tavola",
    acts: "Attività",
    day: "Giorno {n}",
    included: "incluso",
    bookStay: "Prenota la capsula",
    seeMap: "Vedi sulla mappa",
    passes: "Pass",
    buyPass: "Compra il pass ufficiale",
    passRates:
      "Adulto nazionale {adult} × {guests}. Giovane {youth}. Bambino, over 60 e disabilità nazionale: gratis. Adulto straniero {foreign}.",
    passStay: "Pass per più di 1 giorno. Un giorno: {day} per adulto nazionale.",
    passZero: "La scheda ufficiale indica $0. Conferma il prezzo all'acquisto.",
    passCampana:
      "Settore Granizo. Ocoa e Cajón Grande si comprano a parte, alla stessa tariffa.",
    passPatagonia:
      "Settore Chacabuco. Jeinimeni e Tamango si comprano a parte, alla stessa tariffa.",
    passSource:
      "Tariffa di pasesparques.cl. Mapucoin non incassa il pass: l'acquisto è sul sito ufficiale.",
  },
  partners: {
    kicker: "Partner",
    title: "Entra come partner",
    lead: "Gestisci una capsula, una ruka, una caleta, un tour o una vigna. Mapucoin ti mostra sulla mappa, ti mette nell'itinerario e incassa con Stripe.",
    name: "Nome",
    email: "Email",
    phone: "Telefono",
    role: "Tipo di partner",
    business: "Nome dell'attività",
    city: "Città / territorio",
    notes: "Raccontaci la tua offerta",
    submit: "Candidati",
    sending: "Invio…",
    incomplete: "Compila nome, email e attività.",
    error: "Invio non riuscito. Riprova.",
    ok: "Abbiamo ricevuto la tua candidatura",
    okLead:
      "Esaminiamo l’offerta e ti scriviamo per attivare la scheda e Stripe. I tuoi dati non sono pubblici fino all’approvazione.",
    invalidEmail: "Inserisci un’email valida.",
    privacy:
      "I tuoi dati non sono mostrati ad altri candidati né sulla mappa pubblica.",
    another: "Invia un’altra candidatura",
    okNoDb:
      "Abbiamo ricevuto la tua candidatura. Collega Supabase per salvare i partner in produzione.",
    onboardTitle: "Attiva Stripe Connect",
    onboardLead:
      "Usa la stessa email della candidatura. Stripe apre un account Express in Cile (CL).",
    onboardSubmit: "Continua su Stripe",
    onboardBlocked:
      "Stripe non ha potuto creare l’account Connect in Cile. Il pagamento resta sulla piattaforma Mapucoin; il 12% è contabilizzato per un payout manuale.",
    onboardNeedEmail: "Inserisci l’email della candidatura.",
    returnTitle: "Onboarding inviato",
    returnLead:
      "Quando Stripe attiva charges e payouts, il checkout divide il pagamento (12% piattaforma).",
  },
  partnerRoles: {
    capsula: "Capsula / alloggio",
    gastronomia: "Gastronomia",
    actividad: "Attività / tour",
    guia: "Guida",
    transporte: "Trasporto",
    vina: "Vigna / distilleria",
  },
  awards: {
    kicker: "Premi",
    title: "Premi e riconoscimenti internazionali",
    lead: "Cile, Atacama, Santiago, Rapa Nui e Torres del Paine, distinti da World Travel Awards, TIME, Forbes, Tripadvisor e UNESCO.",
    prev: "Premio precedente",
    next: "Premio successivo",
    goTo: "Vai al premio {n}",
    of: "{n} di {total}: {title}",
  },
  kinds: {
    place: "Destinazione",
    capsule: "Capsula",
    food: "Tavola",
    activity: "Attività",
  },
  landscapes: {
    desierto: "Deserti",
    playa: "Spiagge",
    vinedos: "Vigneti",
    volcan: "Vulcani",
    rios: "Fiumi",
    lago: "Laghi",
    "bosque-nativo": "Boschi",
    nieve: "Neve",
    parques: "Parchi nazionali",
  },
  activitySports: {
    desierto: "Astronomia e sandboard",
    playa: "Immersioni e surf",
    vinedos: "Degustazione di vini",
    volcan: "Trekking, ciclismo e terme",
    rios: "Kayak e rafting",
    lago: "Barche e sport nautici",
    "bosque-nativo": "Tour e trekking",
    nieve: "Sci e snowboard",
    parques: "Trekking e natura",
  },
  interests: {
    naturaleza: "Natura",
    gastronomia: "Gastronomia",
    cultura: "Cultura",
    aventura: "Avventura",
    descanso: "Riposo",
    estrellas: "Astronomia",
  },
  from: "da",
  operator: "Gestito da",
  sound: "Suono",
  mute: "Muto",
  footer: { terms: "Terms", privacy: "Privacy" },
  notFound: {
    title: "Territorio non trovato",
    lead: "Quel percorso non è sulla mappa Mapucoin.",
    back: "Torna all'inizio",
  },
  destino: {
    videoKicker: "Video del territorio",
    videoTitle: "{name} in movimento",
    videoAlt: "Video di {name}",
    gallery: "Galleria",
    onMap: "Sulla mappa",
    from: "Esperienze da",
    passFrom: "Ingresso adulto nazionale",
    passKicker: "Pass ufficiale",
    passAdult: "Nazionale {national} · straniero {foreign}",
    passYouth: "Giovane nazionale {youth} · giovane straniero {foreignYouth}",
    passFree:
      "Bambino, over 60 e persona con disabilità nazionale entrano gratis.",
    passMulti:
      "Più di 1 giorno: nazionale {national} · straniero {foreign}. Un giorno: {day}.",
    buyPass: "Compra su pasesparques.cl",
    passSource: "Tariffa pubblicata su pasesparques.cl.",
    planThis: "Pianifica questa destinazione",
    seeCapsule: "Vedi capsula {name}",
    related: "Dormire, mangiare e fare",
  },
  reserva: {
    kicker: "Prenotazione",
    title: "Conferma la prenotazione",
    canceled: "Pagamento annullato. Puoi riprovare.",
    summary: "{name} · {city}. {nights} · {guests}. Totale {total}.",
    night: "notte",
    nights: "notti",
    guest: "viaggiatore",
    guests: "viaggiatori",
    capsule: "Capsula",
    name: "Nome",
    email: "Email",
    phone: "Telefono",
    pay: "Prenota / Paga",
    included: "Include",
    perNight: "a notte",
    totalLabel: "Totale",
    backMap: "Torna alla mappa",
    backCapsule: "Torna alla capsula",
    invalidName: "Scrivi il tuo nome (minimo 2 lettere).",
    invalidEmail: "Inserisci un’email valida.",
    rateLimited: "Troppi tentativi. Attendi un momento e riprova.",
    secure: "Pagamento sicuro con Stripe",
    platformNote:
      "Addebito in CLP su Mapucoin. Se il partner non ha ancora Stripe Connect, il pagamento resta sulla piattaforma.",
    fromPrice: "Da {price} / notte",
    paying: "Reindirizzamento a Stripe…",
    creating: "Creazione della sessione Stripe…",
    noStripe: "Stripe non è configurato. Aggiungi STRIPE_SECRET_KEY in Vercel.",
    fail: "Impossibile avviare il pagamento. Controlla i dati.",
    okKicker: "Fatto",
    okTitle: "Prenotazione confermata",
    okLead:
      "Stripe ha registrato il pagamento. Scriviamo con il check-in della capsula e il resto dell'itinerario.",
    okCta: "Torna alla mappa",
    okAmount: "Importo",
    okCapsule: "Capsula",
    okNights: "Notti",
    okGuests: "Viaggiatori",
    okEmail: "Email",
    okPending: "Conferma del pagamento…",
    okMissing:
      "Sessione non trovata. Se l’addebito è andato a buon fine, la ricevuta arriva via email.",
    okPaid: "Pagato",
  },
  catalogEmpty: "Nessuna scheda in questo paesaggio.",
  awardTitles: {
    "Mejor Destino de Turismo Aventura del Mundo":
      "Migliore destinazione di turismo d'avventura al mondo",
    "Mejor Destino Romántico": "Migliore destinazione romantica",
    "Mejor Destino de Sudamérica": "Migliore destinazione del Sudamerica",
    "Mejor Destino Verde": "Migliore destinazione verde",
    "Mejor Destino de Naturaleza": "Migliore destinazione natura",
    "Mejor Ciudad": "Migliore città",
    "Mejor Destino de Cruceros": "Migliore destinazione crocieristica",
    "Mejor Destino Internacional": "Migliore destinazione internazionale",
    "Solo Travel — 4° mundial": "Solo Travel — 4° mondiale",
    "Top South American Destination": "Top South American Destination",
    "Reserva de la Biósfera": "Riserva della biosfera",
    "Mejor Viñedo del Mundo": "Miglior vigneto del mondo",
    "World's Greatest Places": "World's Greatest Places",
    "Patrimonio de la Humanidad": "Patrimonio dell'umanità",
    "Mejor lugar del mundo para observación de estrellas":
      "Miglior luogo al mondo per osservare le stelle",
    "El radiotelescopio más grande del mundo":
      "Il radiotelescopio più grande del mondo",
  },
  awardNotes: {
    "7ª vez": "7ª volta",
    "Octava Maravilla del Mundo": "Ottava meraviglia del mondo",
    "Postulación a premio de gobernanza": "Candidatura a premio di governance",
    "Estancia Mercedes (Magallanes), Pared Sur Camp (Aysén) y Ephedra Restaurant (Antofagasta)":
      "Estancia Mercedes (Magallanes), Pared Sur Camp (Aysén) ed Ephedra Restaurant (Antofagasta)",
    Astroturismo: "Astroturismo",
  },
  legalTermsTitle: "Termini e condizioni",
  legalPrivacyTitle: "Informativa sulla privacy",
};

const de: typeof es = {
  skip: "Zum Inhalt springen",
  language: "Sprache",
  nav: {
    why: "Warum Chile",
    map: "Karte",
    capsules: "Kapseln",
    food: "Gastronomie",
    activities: "Aktivitäten",
    partners: "Partner",
    awards: "Auszeichnungen",
    plan: "Planen",
    app: "App",
    login: "Anmelden",
    signup: "Konto erstellen",
    logout: "Abmelden",
    menu: "Menü",
    prev: "Zurück",
    next: "Weiter",
  },
  hero: {
    title: "Chile, von Nord nach Süd.",
    lead: "Kapseln aus Kupfer und Glas in Wüsten, an Stränden, in Weinbergen, an Vulkanen, Flüssen, Seen, in Wäldern, im Schnee und in Nationalparks. Lokale Tafel und Budget in CLP.",
    planCta: "Planen",
    appCta: "App öffnen",
  },
  whyChile: {
    kicker: "Unendliche Reise",
    title: "Warum Chile?",
    lead: "Dreißig Sekunden durch das Land, von Nord nach Süd.",
    video: "Warum Chile, deutsche Fassung",
  },
  map: {
    kicker: "Karte",
    title: "Chile nach Landschaft geordnet",
    lead: "Filtere Wüsten, Strände, Weinberge, Vulkane, Flüsse, Seen, Wälder, Schnee und die 48 Nationalparks mit digitalem Pass. Jeder Pin ist ein Gebiet mit seiner Kapsel.",
    all: "Alle",
    places: "Orte",
    capsules: "Kapseln",
    partners: "Partner",
    both: "Alle",
    legend: "Mapucoin-Isologo",
    loading: "Karte von Chile wird geladen…",
    viewSheet: "Steckbrief ansehen →",
    destination: "Reiseziel",
    capsule: "Kapsel",
    partner: "Partner",
    search: "Reiseziel, Kapsel oder Partner suchen",
    searchEmpty: "Keine Treffer",
    searchClear: "Suche löschen",
    emptyPartners: "Noch keine freigegebenen Partner auf der Karte.",
    emptyPartnersHint:
      "Wenn ein lokaler Partner freigegeben wird, erscheint der Pin hier.",
  },
  capsules: {
    kicker: "Kapseln",
    title: "Jede Landschaft, ein Kapselhaus",
    lead: "Kupfer, Glas und Holz. Optional netzunabhängig, Dämmung von −40 °C bis 40 °C. Eine Kapsel pro Landschaft — auch in Nationalparks — betrieben von lokalen Partnern.",
    alt: "Mapucoin-Kapselhaus",
    fromNight: "ab {price} / Nacht",
    perNight: "Pro Nacht",
    upTo: "Bis zu {n} Reisende · {region}",
    book: "Buchen",
    canceled: "Zahlung abgebrochen. Du kannst jederzeit neu buchen.",
    explore: "{name} entdecken →",
    location: "Lage",
    interiorAlt: "Innenraum aus Kupfer, Holz und Glas",
  },
  food: {
    kicker: "Gastronomie",
    title: "Die Tafel des Gebiets",
    lead: "Curanto, Empanadas de pino, Pastel de choclo, Caldillo de congrio, Mote con huesillos und die Tafel jedes Gebiets. Mit lokalen Partnern.",
    hours: "{price} · {hours} Std.",
  },
  activities: {
    kicker: "Aktivitäten",
    title: "Was man im Gebiet unternimmt",
    lead: "Nach Landschaft geordnet: Astronomie und Sandboard in der Wüste, Tauchen und Surfen am Strand, Weinprobe in den Weinbergen, Trekking und Thermen an den Vulkanen, Kajak und Rafting auf den Flüssen, Boote auf den Seen, Touren im Wald, Ski im Schnee.",
    other: "Weiteres",
    otherSports: "Kultur, Sonnenaufgänge und Aussichten",
  },
  plan: {
    kicker: "Planen",
    title: "Deine Reise, dein Budget",
    lead: "Wähle die Landschaft und ein Budget in CLP. Mapucoin stellt Kapselnächte, Tafel und Aktivitäten dieses Gebiets zusammen.",
    formKicker: "Planer",
    formTitle: "Wie viel und wohin?",
    formLead:
      "Wähle die Landschaft und ein Budget in chilenischen Pesos. Mapucoin stellt Kapsel, Tafel und Aktivitäten dieses Gebiets zusammen.",
    landscape: "Landschaft",
    place: "Ort",
    previewTitle: "In diesem Gebiet",
    previewLead:
      "Kapsel, Tafel und was man in der Landschaft unternimmt. Stell die Reise zusammen, um den Tagesplan zu sehen.",
    previewStay: "Schlafen",
    previewTable: "Tafel",
    previewActs: "Tun",
    previewPass: "Pass",
    more: "+{n}",
    loadingHint: "Kapsel, Tafel und Aktivitäten für dein Budget.",
    budget: "Gesamtbudget · {price}",
    budgetMin: "250 Tausend",
    budgetMax: "3,5 Millionen",
    nights: "Nächte",
    guests: "Reisende",
    interests: "Interessen",
    fromDay: "Ab {price} pro Erlebnistag in {city}.",
    submit: "Reise zusammenstellen",
    ask: "Fragen",
    askHint: "Z. B.: Pucón oder Puerto Varas mit 600 Tausend?",
    askPlaceholder: "Schreib deine Frage…",
    send: "Senden",
    you: "Du",
    loadingPlan: "Der Reiseplan wird mit deinem Budget erstellt…",
    loadPlanner: "Planer wird geladen…",
    errorPlan: "Der Reiseplan konnte nicht erstellt werden.",
    errorNet: "Netzwerkfehler beim Erstellen des Reiseplans.",
    empty:
      "Wähle eine Landschaft und stell die Reise zusammen. Der Plan erscheint hier, mit Kapsel, Tafel und Aktivitäten.",
    chatFail: "ich konnte gerade nicht antworten.",
  },
  itinerary: {
    kicker: "Reiseplan",
    budget: "Budget",
    estimated: "Geschätzte Summe",
    remaining: "Übrig",
    nightsGuests: "Nächte · Reisende",
    stay: "Kapsel",
    table: "Tafel",
    acts: "Aktivitäten",
    day: "Tag {n}",
    included: "inklusive",
    bookStay: "Kapsel buchen",
    seeMap: "Auf der Karte ansehen",
    passes: "Pässe",
    buyPass: "Offiziellen Pass kaufen",
    passRates:
      "Chilenischer Erwachsener {adult} × {guests}. Jugendliche {youth}. Chilenische Kinder, Senioren und Menschen mit Behinderung: kostenlos. Ausländischer Erwachsener {foreign}.",
    passStay:
      "Pass für mehr als 1 Tag. Ein Tag: {day} pro chilenischem Erwachsenen.",
    passZero:
      "Die offizielle Seite zeigt 0 $. Bestätige den Preis beim Kauf.",
    passCampana:
      "Sektor Granizo. Ocoa und Cajón Grande werden getrennt zum selben Tarif gekauft.",
    passPatagonia:
      "Sektor Chacabuco. Jeinimeni und Tamango werden getrennt zum selben Tarif gekauft.",
    passSource:
      "Tarif von pasesparques.cl. Mapucoin kassiert den Pass nicht: der Kauf erfolgt auf der offiziellen Seite.",
  },
  partners: {
    kicker: "Partner",
    title: "Als Partner beitreten",
    lead: "Du betreibst eine Kapsel, eine Ruka, eine Caleta, eine Tour oder ein Weingut. Mapucoin zeigt dich auf der Karte, nimmt dich in den Reiseplan und kassiert mit Stripe.",
    name: "Name",
    email: "E-Mail",
    phone: "Telefon",
    role: "Partnerart",
    business: "Name des Betriebs",
    city: "Stadt / Gebiet",
    notes: "Erzähl uns dein Angebot",
    submit: "Bewerben",
    sending: "Senden…",
    incomplete: "Füll Name, E-Mail und Betrieb aus.",
    error: "Senden fehlgeschlagen. Versuch es erneut.",
    ok: "Wir haben deine Bewerbung erhalten",
    okLead:
      "Wir prüfen dein Angebot und schreiben dir, um den Eintrag und Stripe zu aktivieren. Deine Daten veröffentlichen wir erst nach der Freigabe.",
    invalidEmail: "Gib eine gültige E-Mail ein.",
    privacy:
      "Deine Daten werden anderen Bewerbern und auf der öffentlichen Karte nicht gezeigt.",
    another: "Weitere Bewerbung senden",
    okNoDb:
      "Wir haben deine Bewerbung erhalten. Verbinde Supabase, um Partner in der Produktion zu speichern.",
    onboardTitle: "Stripe Connect aktivieren",
    onboardLead:
      "Nutze dieselbe E-Mail wie in der Bewerbung. Stripe öffnet ein Express-Konto in Chile (CL).",
    onboardSubmit: "Weiter zu Stripe",
    onboardBlocked:
      "Stripe konnte kein Connect-Konto in Chile anlegen. Die Zahlung bleibt auf der Mapucoin-Plattform; die 12 % werden für eine manuelle Auszahlung verbucht.",
    onboardNeedEmail: "Gib die E-Mail der Bewerbung ein.",
    returnTitle: "Onboarding gesendet",
    returnLead:
      "Wenn Stripe Zahlungen und Auszahlungen aktiviert, teilt der Checkout die Zahlung (12 % Plattform).",
  },
  partnerRoles: {
    capsula: "Kapsel / Unterkunft",
    gastronomia: "Gastronomie",
    actividad: "Aktivität / Tour",
    guia: "Guide",
    transporte: "Transport",
    vina: "Weingut / Destillerie",
  },
  awards: {
    kicker: "Auszeichnungen",
    title: "Internationale Preise und Anerkennungen",
    lead: "Chile, Atacama, Santiago, Rapa Nui und Torres del Paine, ausgezeichnet von World Travel Awards, TIME, Forbes, Tripadvisor und UNESCO.",
    prev: "Vorheriger Preis",
    next: "Nächster Preis",
    goTo: "Zum Preis {n}",
    of: "{n} von {total}: {title}",
  },
  kinds: {
    place: "Reiseziel",
    capsule: "Kapsel",
    food: "Tafel",
    activity: "Aktivität",
  },
  landscapes: {
    desierto: "Wüsten",
    playa: "Strände",
    vinedos: "Weinberge",
    volcan: "Vulkane",
    rios: "Flüsse",
    lago: "Seen",
    "bosque-nativo": "Wälder",
    nieve: "Schnee",
    parques: "Nationalparks",
  },
  activitySports: {
    desierto: "Astronomie und Sandboard",
    playa: "Tauchen und Surfen",
    vinedos: "Weinprobe",
    volcan: "Trekking, Radfahren und Thermen",
    rios: "Kajak und Rafting",
    lago: "Boote und Wassersport",
    "bosque-nativo": "Touren und Trekking",
    nieve: "Ski und Snowboard",
    parques: "Trekking und Natur",
  },
  interests: {
    naturaleza: "Natur",
    gastronomia: "Gastronomie",
    cultura: "Kultur",
    aventura: "Abenteuer",
    descanso: "Ruhe",
    estrellas: "Astronomie",
  },
  from: "ab",
  operator: "Betrieben von",
  sound: "Ton",
  mute: "Stumm",
  footer: { terms: "Terms", privacy: "Privacy" },
  notFound: {
    title: "Gebiet nicht gefunden",
    lead: "Diese Route liegt nicht auf der Mapucoin-Karte.",
    back: "Zur Startseite",
  },
  destino: {
    videoKicker: "Video des Gebiets",
    videoTitle: "{name} in Bewegung",
    videoAlt: "Video von {name}",
    gallery: "Galerie",
    onMap: "Auf der Karte",
    from: "Erlebnisse ab",
    passFrom: "Eintritt chilenischer Erwachsener",
    passKicker: "Offizieller Pass",
    passAdult: "Chilenisch {national} · ausländisch {foreign}",
    passYouth: "Chilenische Jugendliche {youth} · ausländische Jugendliche {foreignYouth}",
    passFree:
      "Chilenische Kinder, Senioren und Menschen mit Behinderung haben freien Eintritt.",
    passMulti:
      "Mehr als 1 Tag: chilenisch {national} · ausländisch {foreign}. Ein Tag: {day}.",
    buyPass: "Auf pasesparques.cl kaufen",
    passSource: "Tarif veröffentlicht auf pasesparques.cl.",
    planThis: "Dieses Reiseziel planen",
    seeCapsule: "Kapsel {name} ansehen",
    related: "Schlafen, essen und unternehmen",
  },
  reserva: {
    kicker: "Buchung",
    title: "Buchung bestätigen",
    canceled: "Zahlung abgebrochen. Du kannst es erneut versuchen.",
    summary: "{name} · {city}. {nights} · {guests}. Summe {total}.",
    night: "Nacht",
    nights: "Nächte",
    guest: "Reisende",
    guests: "Reisende",
    capsule: "Kapsel",
    name: "Name",
    email: "E-Mail",
    phone: "Telefon",
    pay: "Buchen / Zahlen",
    included: "Inklusive",
    perNight: "pro Nacht",
    totalLabel: "Summe",
    backMap: "Zurück zur Karte",
    backCapsule: "Zurück zur Kapsel",
    invalidName: "Schreib deinen Namen (mindestens 2 Buchstaben).",
    invalidEmail: "Gib eine gültige E-Mail ein.",
    rateLimited: "Zu viele Versuche. Warte einen Moment und versuch es erneut.",
    secure: "Sichere Zahlung mit Stripe",
    platformNote:
      "Zahlung in CLP über Mapucoin. Wenn der Partner noch kein Stripe Connect hat, bleibt die Zahlung auf der Plattform.",
    fromPrice: "Ab {price} / Nacht",
    paying: "Weiterleitung zu Stripe…",
    creating: "Stripe-Sitzung wird erstellt…",
    noStripe: "Stripe ist nicht konfiguriert. Trag STRIPE_SECRET_KEY in Vercel ein.",
    fail: "Die Zahlung konnte nicht gestartet werden. Prüfe die Angaben.",
    okKicker: "Fertig",
    okTitle: "Buchung bestätigt",
    okLead:
      "Stripe hat die Zahlung erfasst. Wir schreiben dir zum Check-in der Kapsel und zum restlichen Reiseplan.",
    okCta: "Zurück zur Karte",
    okAmount: "Betrag",
    okCapsule: "Kapsel",
    okNights: "Nächte",
    okGuests: "Reisende",
    okEmail: "E-Mail",
    okPending: "Zahlung wird bestätigt…",
    okMissing:
      "Die Sitzung wurde nicht gefunden. Wenn abgebucht wurde, kommt die Quittung per E-Mail.",
    okPaid: "Bezahlt",
  },
  catalogEmpty: "Keine Einträge in dieser Landschaft.",
  awardTitles: {
    "Mejor Destino de Turismo Aventura del Mundo":
      "Weltweit führendes Abenteuerreiseziel",
    "Mejor Destino Romántico": "Führendes romantisches Reiseziel",
    "Mejor Destino de Sudamérica": "Führendes Reiseziel Südamerikas",
    "Mejor Destino Verde": "Führendes grünes Reiseziel",
    "Mejor Destino de Naturaleza": "Führendes Naturreiseziel",
    "Mejor Ciudad": "Führende Stadt",
    "Mejor Destino de Cruceros": "Führendes Kreuzfahrtziel",
    "Mejor Destino Internacional": "Führendes internationales Reiseziel",
    "Solo Travel — 4° mundial": "Solo Travel — 4. weltweit",
    "Top South American Destination": "Top South American Destination",
    "Reserva de la Biósfera": "Biosphärenreservat",
    "Mejor Viñedo del Mundo": "Bestes Weingut der Welt",
    "World's Greatest Places": "World's Greatest Places",
    "Patrimonio de la Humanidad": "Welterbe",
    "Mejor lugar del mundo para observación de estrellas":
      "Bester Ort der Welt zur Sternbeobachtung",
    "El radiotelescopio más grande del mundo":
      "Das größte Radioteleskop der Welt",
  },
  awardNotes: {
    "7ª vez": "zum 7. Mal",
    "Octava Maravilla del Mundo": "Achtes Weltwunder",
    "Postulación a premio de gobernanza": "Nominierung für einen Governance-Preis",
    "Estancia Mercedes (Magallanes), Pared Sur Camp (Aysén) y Ephedra Restaurant (Antofagasta)":
      "Estancia Mercedes (Magallanes), Pared Sur Camp (Aysén) und Ephedra Restaurant (Antofagasta)",
    Astroturismo: "Astrotourismus",
  },
  legalTermsTitle: "Allgemeine Geschäftsbedingungen",
  legalPrivacyTitle: "Datenschutzerklärung",
};

export const copy = { es, en, pt, fr, it, de } as const;

export function t(locale: Locale) {
  return copy[locale] ?? copy.es;
}

export function tr(
  template: string,
  vars: Record<string, string | number>,
) {
  return template.replace(/\{(\w+)\}/g, (_, k) => String(vars[k] ?? ""));
}
