import type { Landscape } from "./catalog";
import type { Locale } from "./locale";

const es = {
  skip: "Saltar al contenido",
  language: "Idioma",
  nav: {
    map: "Mapa",
    capsules: "Cápsulas",
    food: "Gastronomía",
    activities: "Actividades",
    partners: "Partners",
    awards: "Premios",
    plan: "Planificar",
    menu: "Menú",
  },
  hero: {
    title: "Chile, de norte a sur.",
    lead: "Cápsulas de cobre y vidrio en desiertos, playas, viñedos, volcanes, ríos, lagos, bosques y nieve. Mesa local y presupuesto en CLP.",
    mapCta: "Mapa interactivo",
    planCta: "Planificar",
  },
  map: {
    kicker: "Mapa",
    title: "Chile clasificado por paisaje",
    lead: "Filtra desiertos, playas, viñedos, volcanes, ríos, lagos, bosques y nieve. Cada pin es un territorio con su cápsula.",
    all: "Todos",
    places: "Lugares",
    capsules: "Cápsulas",
    both: "Ambos",
    legend: "Terracota: destinos · Oro: cápsulas",
    loading: "Cargando mapa de Chile…",
    viewSheet: "Ver ficha →",
    destination: "Destino",
    capsule: "Cápsula",
  },
  capsules: {
    kicker: "Cápsulas",
    title: "Ocho paisajes, una casa cápsula",
    lead: "Cobre, vidrio y madera. Off-grid opcional, aislación de −40 °C a 40 °C. Una cápsula por paisaje, operada por partners locales.",
    alt: "Casa cápsula Mapucoin",
    fromNight: "desde {price} / noche",
    perNight: "Por noche",
    upTo: "Hasta {n} viajeros · {region}",
    book: "Reservar",
    explore: "Explorar {name} →",
    location: "Ubicación",
    interiorAlt: "Interior de cobre, madera y vidrio",
  },
  food: {
    kicker: "Gastronomía",
    title: "La mesa del territorio",
    lead: "Curanto, empanadas de pino, pastel de choclo, caldillo de congrio, mote con huesillos y la mesa de cada territorio. Con partners locales.",
    hours: "{price} · {hours} h",
  },
  activities: {
    kicker: "Actividades",
    title: "Lo que se hace en el territorio",
    lead: "Clasificadas por paisaje: astronomía y sandboard en el desierto, buceo y surf en la playa, cata en los viñedos, trekking y termas en los volcanes, kayak y rafting en los ríos, barcos en los lagos, tours en el bosque, ski en la nieve.",
    other: "Otros",
    otherSports: "Cultura, amaneceres y miradores",
  },
  plan: {
    kicker: "Planificar",
    title: "Tu viaje, a tu presupuesto",
    lead: "Elige el paisaje, el presupuesto en CLP y Mapucoin arma noches en cápsula, mesa y actividades de ese territorio.",
    formKicker: "Planificador",
    formTitle: "¿Cuánto y a dónde?",
    formLead:
      "Elige el paisaje y el presupuesto en pesos chilenos. Mapucoin arma cápsula, mesa y actividades de ese territorio.",
    landscape: "Paisaje",
    place: "Lugar a conocer",
    previewTitle: "En este territorio",
    previewLead:
      "Cápsula, mesa y lo que se hace en el paisaje. Arma el viaje para ver el itinerario día a día.",
    previewStay: "Dormir",
    previewTable: "Mesa",
    previewActs: "Hacer",
    more: "+{n}",
    loadingHint: "Cápsula, mesa y actividades según tu presupuesto.",
    budget: "Presupuesto total · {price}",
    budgetMin: "250 mil",
    budgetMax: "3,5 millones",
    nights: "Noches",
    guests: "Viajeros",
    interests: "Intereses",
    fromDay: "Desde {price} por día de experiencia en {city}.",
    submit: "Armar viaje",
    ask: "Preguntar",
    askHint: "Ej: ¿conviene más Pucón o Puerto Varas con 600 mil?",
    askPlaceholder: "Escribe tu consulta…",
    send: "Enviar",
    you: "Tú",
    loadingPlan: "Armando el itinerario con tu presupuesto…",
    loadPlanner: "Cargando planificador…",
    errorPlan: "No se pudo armar el itinerario.",
    errorNet: "Error de red al armar el itinerario.",
    empty:
      "Elige un paisaje y arma el viaje. El itinerario aparece aquí, con cápsula, mesa y actividades.",
    chatFail: "no pude responder ahora.",
  },
  itinerary: {
    kicker: "Itinerario",
    budget: "Presupuesto",
    estimated: "Total estimado",
    remaining: "Queda",
    nightsGuests: "Noches · viajeros",
    stay: "Cápsula",
    table: "Mesa",
    acts: "Actividades",
    day: "Día {n}",
    included: "incluido",
    bookStay: "Reservar cápsula",
    seeMap: "Ver en el mapa",
  },
  partners: {
    kicker: "Partners",
    title: "Ingresa como partner",
    lead: "Operas una cápsula, una ruka, una caleta, un tour o una viña. Mapucoin te muestra en el mapa, entra al itinerario y cobra con Stripe.",
    name: "Nombre",
    email: "Correo",
    phone: "Teléfono",
    role: "Tipo de partner",
    business: "Nombre del negocio",
    city: "Ciudad / territorio",
    notes: "Cuéntanos tu oferta",
    submit: "Postular",
    sending: "Enviando…",
    incomplete: "Completa nombre, correo y negocio.",
    error: "No se pudo enviar. Inténtalo de nuevo.",
    ok: "Solicitud recibida. Te contactamos para activar tu ficha y Stripe.",
    okNoDb:
      "Solicitud recibida. Conecta Supabase para guardar partners en producción.",
  },
  partnerRoles: {
    capsula: "Cápsula / alojamiento",
    gastronomia: "Gastronomía",
    actividad: "Actividad / tour",
    guia: "Guía",
    transporte: "Transporte",
    vina: "Viña / destilería",
  },
  awards: {
    kicker: "Premios",
    title: "Premios y reconocimientos internacionales",
    lead: "Chile, Atacama, Santiago, Rapa Nui y Torres del Paine, distinguidos por World Travel Awards, TIME, Forbes, Tripadvisor y UNESCO.",
    prev: "Premio anterior",
    next: "Premio siguiente",
    goTo: "Ir al premio {n}",
    of: "{n} de {total}: {title}",
  },
  kinds: {
    place: "Destino",
    capsule: "Cápsula",
    food: "Mesa",
    activity: "Actividad",
  },
  landscapes: {
    desierto: "Desiertos",
    playa: "Playas",
    vinedos: "Viñedos",
    volcan: "Volcanes",
    rios: "Ríos",
    lago: "Lagos",
    "bosque-nativo": "Bosques",
    nieve: "Nieve",
  } satisfies Record<Landscape, string>,
  activitySports: {
    desierto: "Astronomía y sandboard",
    playa: "Buceo y surf",
    vinedos: "Cata de vinos",
    volcan: "Trekking, ciclismo y termas",
    rios: "Kayak y rafting",
    lago: "Barcos y deportes náuticos",
    "bosque-nativo": "Tours y trekking",
    nieve: "Ski y snowboard",
  } satisfies Record<Landscape, string>,
  interests: {
    naturaleza: "Naturaleza",
    gastronomia: "Gastronomía",
    cultura: "Cultura",
    aventura: "Aventura",
    descanso: "Descanso",
    estrellas: "Astronomía",
  },
  from: "desde",
  sound: "Sonido",
  mute: "Silencio",
  footer: { terms: "Terms", privacy: "Privacy" },
  notFound: {
    title: "Territorio no encontrado",
    lead: "Esa ruta no está en el mapa Mapucoin.",
    back: "Volver al inicio",
  },
  destino: {
    videoKicker: "Video del territorio",
    videoTitle: "{name} en movimiento",
    videoAlt: "Video de {name}",
    gallery: "Galería",
    onMap: "En el mapa",
    from: "Experiencias desde",
    planThis: "Planificar este destino",
    seeCapsule: "Ver cápsula {name}",
    related: "Dormir, comer y hacer",
  },
  reserva: {
    kicker: "Reserva",
    title: "Confirmar reserva",
    canceled: "Pago cancelado. Puedes reintentar.",
    summary: "{name} · {city}. {nights} · {guests}. Total {total}.",
    night: "noche",
    nights: "noches",
    guest: "viajero",
    guests: "viajeros",
    capsule: "Cápsula",
    name: "Nombre",
    email: "Correo",
    phone: "Teléfono",
    pay: "Pagar con Stripe",
    creating: "Creando sesión de Stripe…",
    noStripe: "Stripe no está configurado. Añade STRIPE_SECRET_KEY en Vercel.",
    fail: "No se pudo iniciar el pago. Revisa los datos.",
    okKicker: "Listo",
    okTitle: "Reserva confirmada",
    okLead:
      "Stripe registró el pago. Te escribimos con el check-in de la cápsula y el resto del itinerario.",
    okCta: "Volver al mapa",
  },
  catalogEmpty: "No hay fichas en este paisaje.",
  awardTitles: {
    "Mejor Destino de Turismo Aventura del Mundo":
      "Mejor Destino de Turismo Aventura del Mundo",
    "Mejor Destino Romántico": "Mejor Destino Romántico",
    "Mejor Destino de Sudamérica": "Mejor Destino de Sudamérica",
    "Mejor Destino Verde": "Mejor Destino Verde",
    "Mejor Destino de Naturaleza": "Mejor Destino de Naturaleza",
    "Mejor Ciudad": "Mejor Ciudad",
    "Mejor Destino de Cruceros": "Mejor Destino de Cruceros",
    "Mejor Destino Internacional": "Mejor Destino Internacional",
    "Solo Travel — 4° mundial": "Solo Travel — 4° mundial",
    "Top South American Destination": "Top South American Destination",
    "Reserva de la Biósfera": "Reserva de la Biósfera",
    "Mejor Viñedo del Mundo": "Mejor Viñedo del Mundo",
    "World's Greatest Places": "World's Greatest Places",
    "Patrimonio de la Humanidad": "Patrimonio de la Humanidad",
    "Mejor lugar del mundo para observación de estrellas":
      "Mejor lugar del mundo para observación de estrellas",
    "El radiotelescopio más grande del mundo":
      "El radiotelescopio más grande del mundo",
  },
  awardNotes: {
    "7ª vez": "7ª vez",
    "Octava Maravilla del Mundo": "Octava Maravilla del Mundo",
    "Postulación a premio de gobernanza": "Postulación a premio de gobernanza",
    "Estancia Mercedes (Magallanes), Pared Sur Camp (Aysén) y Ephedra Restaurant (Antofagasta)":
      "Estancia Mercedes (Magallanes), Pared Sur Camp (Aysén) y Ephedra Restaurant (Antofagasta)",
    Astroturismo: "Astroturismo",
  },
  legalTermsTitle: "Términos y Condiciones",
  legalPrivacyTitle: "Política de Privacidad",
};

const en: typeof es = {
  skip: "Skip to content",
  language: "Language",
  nav: {
    map: "Map",
    capsules: "Capsules",
    food: "Gastronomy",
    activities: "Activities",
    partners: "Partners",
    awards: "Awards",
    plan: "Plan",
    menu: "Menu",
  },
  hero: {
    title: "Chile, north to south.",
    lead: "Copper and glass capsules in deserts, beaches, vineyards, volcanoes, rivers, lakes, forests and snow. Local table and budget in CLP.",
    mapCta: "Interactive map",
    planCta: "Plan",
  },
  map: {
    kicker: "Map",
    title: "Chile classified by landscape",
    lead: "Filter deserts, beaches, vineyards, volcanoes, rivers, lakes, forests and snow. Each pin is a territory with its capsule.",
    all: "All",
    places: "Places",
    capsules: "Capsules",
    both: "Both",
    legend: "Terracotta: destinations · Gold: capsules",
    loading: "Loading the map of Chile…",
    viewSheet: "View sheet →",
    destination: "Destination",
    capsule: "Capsule",
  },
  capsules: {
    kicker: "Capsules",
    title: "Eight landscapes, one capsule home",
    lead: "Copper, glass and wood. Optional off-grid, insulation from −40 °C to 40 °C. One capsule per landscape, run by local partners.",
    alt: "Mapucoin capsule house",
    fromNight: "from {price} / night",
    perNight: "Per night",
    upTo: "Up to {n} guests · {region}",
    book: "Book",
    explore: "Explore {name} →",
    location: "Location",
    interiorAlt: "Copper, wood and glass interior",
  },
  food: {
    kicker: "Gastronomy",
    title: "The table of the territory",
    lead: "Curanto, empanadas de pino, pastel de choclo, caldillo de congrio, mote con huesillos and the table of each territory. With local partners.",
    hours: "{price} · {hours} h",
  },
  activities: {
    kicker: "Activities",
    title: "What you do in the territory",
    lead: "Classified by landscape: astronomy and sandboarding in the desert, diving and surf on the beach, wine tasting in the vineyards, trekking and hot springs on the volcanoes, kayak and rafting on the rivers, boats on the lakes, forest tours, ski in the snow.",
    other: "Other",
    otherSports: "Culture, sunrises and lookouts",
  },
  plan: {
    kicker: "Plan",
    title: "Your trip, at your budget",
    lead: "Choose the landscape and a budget in CLP. Mapucoin builds capsule nights, table and activities of that territory.",
    formKicker: "Planner",
    formTitle: "How much and where?",
    formLead:
      "Choose the landscape and a budget in Chilean pesos. Mapucoin builds capsule, table and activities of that territory.",
    landscape: "Landscape",
    place: "Place to visit",
    previewTitle: "In this territory",
    previewLead:
      "Capsule, table and what you do in the landscape. Build the trip to see the day-by-day itinerary.",
    previewStay: "Stay",
    previewTable: "Table",
    previewActs: "Do",
    more: "+{n}",
    loadingHint: "Capsule, table and activities for your budget.",
    budget: "Total budget · {price}",
    budgetMin: "250 thousand",
    budgetMax: "3.5 million",
    nights: "Nights",
    guests: "Travelers",
    interests: "Interests",
    fromDay: "From {price} per day of experience in {city}.",
    submit: "Build trip",
    ask: "Ask",
    askHint: "Ex: is Pucón or Puerto Varas better with 600 thousand?",
    askPlaceholder: "Write your question…",
    send: "Send",
    you: "You",
    loadingPlan: "Building the itinerary with your budget…",
    loadPlanner: "Loading planner…",
    errorPlan: "Could not build the itinerary.",
    errorNet: "Network error while building the itinerary.",
    empty:
      "Choose a landscape and build the trip. The itinerary appears here, with capsule, table and activities.",
    chatFail: "I could not reply right now.",
  },
  itinerary: {
    kicker: "Itinerary",
    budget: "Budget",
    estimated: "Estimated total",
    remaining: "Left",
    nightsGuests: "Nights · travelers",
    stay: "Capsule",
    table: "Table",
    acts: "Activities",
    day: "Day {n}",
    included: "included",
    bookStay: "Book capsule",
    seeMap: "See on the map",
  },
  partners: {
    kicker: "Partners",
    title: "Join as a partner",
    lead: "You run a capsule, a ruka, a caleta, a tour or a vineyard. Mapucoin shows you on the map, puts you in the itinerary and charges with Stripe.",
    name: "Name",
    email: "Email",
    phone: "Phone",
    role: "Partner type",
    business: "Business name",
    city: "City / territory",
    notes: "Tell us what you offer",
    submit: "Apply",
    sending: "Sending…",
    incomplete: "Fill in name, email and business.",
    error: "Could not send. Try again.",
    ok: "Request received. We will contact you to activate your listing and Stripe.",
    okNoDb:
      "Request received. Connect Supabase to store partners in production.",
  },
  partnerRoles: {
    capsula: "Capsule / lodging",
    gastronomia: "Gastronomy",
    actividad: "Activity / tour",
    guia: "Guide",
    transporte: "Transport",
    vina: "Vineyard / distillery",
  },
  awards: {
    kicker: "Awards",
    title: "International awards and recognitions",
    lead: "Chile, Atacama, Santiago, Rapa Nui and Torres del Paine, recognized by World Travel Awards, TIME, Forbes, Tripadvisor and UNESCO.",
    prev: "Previous award",
    next: "Next award",
    goTo: "Go to award {n}",
    of: "{n} of {total}: {title}",
  },
  kinds: {
    place: "Destination",
    capsule: "Capsule",
    food: "Table",
    activity: "Activity",
  },
  landscapes: {
    desierto: "Deserts",
    playa: "Beaches",
    vinedos: "Vineyards",
    volcan: "Volcanoes",
    rios: "Rivers",
    lago: "Lakes",
    "bosque-nativo": "Forests",
    nieve: "Snow",
  },
  activitySports: {
    desierto: "Astronomy and sandboarding",
    playa: "Diving and surf",
    vinedos: "Wine tasting",
    volcan: "Trekking, cycling and hot springs",
    rios: "Kayak and rafting",
    lago: "Boats and water sports",
    "bosque-nativo": "Tours and trekking",
    nieve: "Ski and snowboard",
  },
  interests: {
    naturaleza: "Nature",
    gastronomia: "Gastronomy",
    cultura: "Culture",
    aventura: "Adventure",
    descanso: "Rest",
    estrellas: "Astronomy",
  },
  from: "from",
  sound: "Sound",
  mute: "Mute",
  footer: { terms: "Terms", privacy: "Privacy" },
  notFound: {
    title: "Territory not found",
    lead: "That route is not on the Mapucoin map.",
    back: "Back to home",
  },
  destino: {
    videoKicker: "Territory video",
    videoTitle: "{name} in motion",
    videoAlt: "Video of {name}",
    gallery: "Gallery",
    onMap: "On the map",
    from: "Experiences from",
    planThis: "Plan this destination",
    seeCapsule: "See capsule {name}",
    related: "Stay, eat and do",
  },
  reserva: {
    kicker: "Booking",
    title: "Confirm booking",
    canceled: "Payment canceled. You can try again.",
    summary: "{name} · {city}. {nights} · {guests}. Total {total}.",
    night: "night",
    nights: "nights",
    guest: "traveler",
    guests: "travelers",
    capsule: "Capsule",
    name: "Name",
    email: "Email",
    phone: "Phone",
    pay: "Pay with Stripe",
    creating: "Creating Stripe session…",
    noStripe: "Stripe is not configured. Add STRIPE_SECRET_KEY in Vercel.",
    fail: "Could not start payment. Check the details.",
    okKicker: "Done",
    okTitle: "Booking confirmed",
    okLead:
      "Stripe recorded the payment. We will write with capsule check-in and the rest of the itinerary.",
    okCta: "Back to the map",
  },
  catalogEmpty: "No listings in this landscape.",
  awardTitles: {
    "Mejor Destino de Turismo Aventura del Mundo":
      "World's Leading Adventure Tourism Destination",
    "Mejor Destino Romántico": "Leading Romantic Destination",
    "Mejor Destino de Sudamérica": "Leading Destination in South America",
    "Mejor Destino Verde": "Leading Green Destination",
    "Mejor Destino de Naturaleza": "Leading Nature Destination",
    "Mejor Ciudad": "Leading City",
    "Mejor Destino de Cruceros": "Leading Cruise Destination",
    "Mejor Destino Internacional": "Leading International Destination",
    "Solo Travel — 4° mundial": "Solo Travel — 4th worldwide",
    "Top South American Destination": "Top South American Destination",
    "Reserva de la Biósfera": "Biosphere Reserve",
    "Mejor Viñedo del Mundo": "World's Best Vineyard",
    "World's Greatest Places": "World's Greatest Places",
    "Patrimonio de la Humanidad": "World Heritage",
    "Mejor lugar del mundo para observación de estrellas":
      "Best place in the world for stargazing",
    "El radiotelescopio más grande del mundo":
      "The world's largest radio telescope",
  },
  awardNotes: {
    "7ª vez": "7th time",
    "Octava Maravilla del Mundo": "Eighth Wonder of the World",
    "Postulación a premio de gobernanza": "Nomination for a governance award",
    "Estancia Mercedes (Magallanes), Pared Sur Camp (Aysén) y Ephedra Restaurant (Antofagasta)":
      "Estancia Mercedes (Magallanes), Pared Sur Camp (Aysén) and Ephedra Restaurant (Antofagasta)",
    Astroturismo: "Astrotourism",
  },
  legalTermsTitle: "Terms and Conditions",
  legalPrivacyTitle: "Privacy Policy",
};

const pt: typeof es = {
  skip: "Saltar para o conteúdo",
  language: "Idioma",
  nav: {
    map: "Mapa",
    capsules: "Cápsulas",
    food: "Gastronomia",
    activities: "Atividades",
    partners: "Partners",
    awards: "Prêmios",
    plan: "Planejar",
    menu: "Menu",
  },
  hero: {
    title: "Chile, do norte ao sul.",
    lead: "Cápsulas de cobre e vidro em desertos, praias, vinhedos, vulcões, rios, lagos, florestas e neve. Mesa local e orçamento em CLP.",
    mapCta: "Mapa interativo",
    planCta: "Planejar",
  },
  map: {
    kicker: "Mapa",
    title: "Chile classificado por paisagem",
    lead: "Filtre desertos, praias, vinhedos, vulcões, rios, lagos, florestas e neve. Cada pin é um território com a sua cápsula.",
    all: "Todos",
    places: "Lugares",
    capsules: "Cápsulas",
    both: "Ambos",
    legend: "Terracota: destinos · Ouro: cápsulas",
    loading: "Carregando o mapa do Chile…",
    viewSheet: "Ver ficha →",
    destination: "Destino",
    capsule: "Cápsula",
  },
  capsules: {
    kicker: "Cápsulas",
    title: "Oito paisagens, uma casa cápsula",
    lead: "Cobre, vidro e madeira. Off-grid opcional, isolamento de −40 °C a 40 °C. Uma cápsula por paisagem, operada por partners locais.",
    alt: "Casa cápsula Mapucoin",
    fromNight: "a partir de {price} / noite",
    perNight: "Por noite",
    upTo: "Até {n} viajantes · {region}",
    book: "Reservar",
    explore: "Explorar {name} →",
    location: "Localização",
    interiorAlt: "Interior de cobre, madeira e vidro",
  },
  food: {
    kicker: "Gastronomia",
    title: "A mesa do território",
    lead: "Curanto, empanadas de pino, pastel de choclo, caldillo de congrio, mote con huesillos e a mesa de cada território. Com partners locais.",
    hours: "{price} · {hours} h",
  },
  activities: {
    kicker: "Atividades",
    title: "O que se faz no território",
    lead: "Classificadas por paisagem: astronomia e sandboard no deserto, mergulho e surf na praia, degustação nos vinhedos, trekking e termas nos vulcões, caiaque e rafting nos rios, barcos nos lagos, tours na floresta, ski na neve.",
    other: "Outros",
    otherSports: "Cultura, amaheceres e mirantes",
  },
  plan: {
    kicker: "Planejar",
    title: "Sua viagem, no seu orçamento",
    lead: "Escolha a paisagem e o orçamento em CLP. A Mapucoin arma noites em cápsula, mesa e atividades desse território.",
    formKicker: "Planejador",
    formTitle: "Quanto e para onde?",
    formLead:
      "Escolha a paisagem e o orçamento em pesos chilenos. A Mapucoin arma cápsula, mesa e atividades desse território.",
    landscape: "Paisagem",
    place: "Lugar a conhecer",
    previewTitle: "Neste território",
    previewLead:
      "Cápsula, mesa e o que se faz na paisagem. Arme a viagem para ver o itinerário dia a dia.",
    previewStay: "Dormir",
    previewTable: "Mesa",
    previewActs: "Fazer",
    more: "+{n}",
    loadingHint: "Cápsula, mesa e atividades segundo o seu orçamento.",
    budget: "Orçamento total · {price}",
    budgetMin: "250 mil",
    budgetMax: "3,5 milhões",
    nights: "Noites",
    guests: "Viajantes",
    interests: "Interesses",
    fromDay: "A partir de {price} por dia de experiência em {city}.",
    submit: "Armar viagem",
    ask: "Perguntar",
    askHint: "Ex: vale mais Pucón ou Puerto Varas com 600 mil?",
    askPlaceholder: "Escreva sua consulta…",
    send: "Enviar",
    you: "Você",
    loadingPlan: "Armando o itinerário com o seu orçamento…",
    loadPlanner: "Carregando o planejador…",
    errorPlan: "Não foi possível armar o itinerário.",
    errorNet: "Erro de rede ao armar o itinerário.",
    empty:
      "Escolha uma paisagem e arme a viagem. O itinerário aparece aqui, com cápsula, mesa e atividades.",
    chatFail: "não pude responder agora.",
  },
  itinerary: {
    kicker: "Itinerário",
    budget: "Orçamento",
    estimated: "Total estimado",
    remaining: "Sobra",
    nightsGuests: "Noites · viajantes",
    stay: "Cápsula",
    table: "Mesa",
    acts: "Atividades",
    day: "Dia {n}",
    included: "incluído",
    bookStay: "Reservar cápsula",
    seeMap: "Ver no mapa",
  },
  partners: {
    kicker: "Partners",
    title: "Entre como partner",
    lead: "Você opera uma cápsula, uma ruka, uma caleta, um tour ou uma vinícola. A Mapucoin mostra no mapa, entra no itinerário e cobra com Stripe.",
    name: "Nome",
    email: "E-mail",
    phone: "Telefone",
    role: "Tipo de partner",
    business: "Nome do negócio",
    city: "Cidade / território",
    notes: "Conte sua oferta",
    submit: "Candidatar",
    sending: "Enviando…",
    incomplete: "Preencha nome, e-mail e negócio.",
    error: "Não foi possível enviar. Tente de novo.",
    ok: "Pedido recebido. Entramos em contato para ativar sua ficha e o Stripe.",
    okNoDb:
      "Pedido recebido. Conecte o Supabase para guardar partners em produção.",
  },
  partnerRoles: {
    capsula: "Cápsula / hospedagem",
    gastronomia: "Gastronomia",
    actividad: "Atividade / tour",
    guia: "Guia",
    transporte: "Transporte",
    vina: "Vinícola / destilaria",
  },
  awards: {
    kicker: "Prêmios",
    title: "Prêmios e reconhecimentos internacionais",
    lead: "Chile, Atacama, Santiago, Rapa Nui e Torres del Paine, distinguidos por World Travel Awards, TIME, Forbes, Tripadvisor e UNESCO.",
    prev: "Prêmio anterior",
    next: "Prêmio seguinte",
    goTo: "Ir ao prêmio {n}",
    of: "{n} de {total}: {title}",
  },
  kinds: {
    place: "Destino",
    capsule: "Cápsula",
    food: "Mesa",
    activity: "Atividade",
  },
  landscapes: {
    desierto: "Desertos",
    playa: "Praias",
    vinedos: "Vinhedos",
    volcan: "Vulcões",
    rios: "Rios",
    lago: "Lagos",
    "bosque-nativo": "Florestas",
    nieve: "Neve",
  },
  activitySports: {
    desierto: "Astronomia e sandboard",
    playa: "Mergulho e surf",
    vinedos: "Degustação de vinhos",
    volcan: "Trekking, ciclismo e termas",
    rios: "Caiaque e rafting",
    lago: "Barcos e esportes náuticos",
    "bosque-nativo": "Tours e trekking",
    nieve: "Ski e snowboard",
  },
  interests: {
    naturaleza: "Natureza",
    gastronomia: "Gastronomia",
    cultura: "Cultura",
    aventura: "Aventura",
    descanso: "Descanso",
    estrellas: "Astronomia",
  },
  from: "a partir de",
  sound: "Som",
  mute: "Mudo",
  footer: { terms: "Terms", privacy: "Privacy" },
  notFound: {
    title: "Território não encontrado",
    lead: "Essa rota não está no mapa Mapucoin.",
    back: "Voltar ao início",
  },
  destino: {
    videoKicker: "Vídeo do território",
    videoTitle: "{name} em movimento",
    videoAlt: "Vídeo de {name}",
    gallery: "Galeria",
    onMap: "No mapa",
    from: "Experiências a partir de",
    planThis: "Planejar este destino",
    seeCapsule: "Ver cápsula {name}",
    related: "Dormir, comer e fazer",
  },
  reserva: {
    kicker: "Reserva",
    title: "Confirmar reserva",
    canceled: "Pagamento cancelado. Você pode tentar de novo.",
    summary: "{name} · {city}. {nights} · {guests}. Total {total}.",
    night: "noite",
    nights: "noites",
    guest: "viajante",
    guests: "viajantes",
    capsule: "Cápsula",
    name: "Nome",
    email: "E-mail",
    phone: "Telefone",
    pay: "Pagar com Stripe",
    creating: "Criando sessão Stripe…",
    noStripe: "O Stripe não está configurado. Adicione STRIPE_SECRET_KEY na Vercel.",
    fail: "Não foi possível iniciar o pagamento. Revise os dados.",
    okKicker: "Pronto",
    okTitle: "Reserva confirmada",
    okLead:
      "O Stripe registrou o pagamento. Escrevemos com o check-in da cápsula e o resto do itinerário.",
    okCta: "Voltar ao mapa",
  },
  catalogEmpty: "Não há fichas nesta paisagem.",
  awardTitles: {
    "Mejor Destino de Turismo Aventura del Mundo":
      "Melhor Destino de Turismo de Aventura do Mundo",
    "Mejor Destino Romántico": "Melhor Destino Romântico",
    "Mejor Destino de Sudamérica": "Melhor Destino da América do Sul",
    "Mejor Destino Verde": "Melhor Destino Verde",
    "Mejor Destino de Naturaleza": "Melhor Destino de Natureza",
    "Mejor Ciudad": "Melhor Cidade",
    "Mejor Destino de Cruceros": "Melhor Destino de Cruzeiros",
    "Mejor Destino Internacional": "Melhor Destino Internacional",
    "Solo Travel — 4° mundial": "Solo Travel — 4º mundial",
    "Top South American Destination": "Top South American Destination",
    "Reserva de la Biósfera": "Reserva da Biosfera",
    "Mejor Viñedo del Mundo": "Melhor Vinhedo do Mundo",
    "World's Greatest Places": "World's Greatest Places",
    "Patrimonio de la Humanidad": "Patrimônio da Humanidade",
    "Mejor lugar del mundo para observación de estrellas":
      "Melhor lugar do mundo para observação de estrelas",
    "El radiotelescopio más grande del mundo":
      "O radiotelescópio mais grande do mundo",
  },
  awardNotes: {
    "7ª vez": "7ª vez",
    "Octava Maravilla del Mundo": "Oitava Maravilha do Mundo",
    "Postulación a premio de gobernanza": "Indicação a prêmio de governança",
    "Estancia Mercedes (Magallanes), Pared Sur Camp (Aysén) y Ephedra Restaurant (Antofagasta)":
      "Estancia Mercedes (Magallanes), Pared Sur Camp (Aysén) e Ephedra Restaurant (Antofagasta)",
    Astroturismo: "Astroturismo",
  },
  legalTermsTitle: "Termos e Condições",
  legalPrivacyTitle: "Política de Privacidade",
};

const fr: typeof es = {
  skip: "Aller au contenu",
  language: "Langue",
  nav: {
    map: "Carte",
    capsules: "Capsules",
    food: "Gastronomie",
    activities: "Activités",
    partners: "Partenaires",
    awards: "Prix",
    plan: "Planifier",
    menu: "Menu",
  },
  hero: {
    title: "Le Chili, du nord au sud.",
    lead: "Capsules de cuivre et de verre dans les déserts, plages, vignobles, volcans, rivières, lacs, forêts et neige. Table locale et budget en CLP.",
    mapCta: "Carte interactive",
    planCta: "Planifier",
  },
  map: {
    kicker: "Carte",
    title: "Le Chili classé par paysage",
    lead: "Filtrez déserts, plages, vignobles, volcans, rivières, lacs, forêts et neige. Chaque pin est un territoire avec sa capsule.",
    all: "Tous",
    places: "Lieux",
    capsules: "Capsules",
    both: "Les deux",
    legend: "Terracotta : destinations · Or : capsules",
    loading: "Chargement de la carte du Chili…",
    viewSheet: "Voir la fiche →",
    destination: "Destination",
    capsule: "Capsule",
  },
  capsules: {
    kicker: "Capsules",
    title: "Huit paysages, une maison capsule",
    lead: "Cuivre, verre et bois. Hors réseau en option, isolation de −40 °C à 40 °C. Une capsule par paysage, gérée par des partenaires locaux.",
    alt: "Maison capsule Mapucoin",
    fromNight: "à partir de {price} / nuit",
    perNight: "Par nuit",
    upTo: "Jusqu'à {n} voyageurs · {region}",
    book: "Réserver",
    explore: "Explorer {name} →",
    location: "Emplacement",
    interiorAlt: "Intérieur cuivre, bois et verre",
  },
  food: {
    kicker: "Gastronomie",
    title: "La table du territoire",
    lead: "Curanto, empanadas de pino, pastel de choclo, caldillo de congrio, mote con huesillos et la table de chaque territoire. Avec des partenaires locaux.",
    hours: "{price} · {hours} h",
  },
  activities: {
    kicker: "Activités",
    title: "Ce que l'on fait sur le territoire",
    lead: "Classées par paysage : astronomie et sandboard dans le désert, plongée et surf à la plage, dégustation dans les vignobles, trekking et thermes sur les volcans, kayak et rafting sur les rivières, bateaux sur les lacs, tours en forêt, ski dans la neige.",
    other: "Autres",
    otherSports: "Culture, aubes et belvédères",
  },
  plan: {
    kicker: "Planifier",
    title: "Votre voyage, à votre budget",
    lead: "Choisissez le paysage et un budget en CLP. Mapucoin compose nuits en capsule, table et activités de ce territoire.",
    formKicker: "Planificateur",
    formTitle: "Combien et où ?",
    formLead:
      "Choisissez le paysage et un budget en pesos chiliens. Mapucoin compose capsule, table et activités de ce territoire.",
    landscape: "Paysage",
    place: "Lieu à découvrir",
    previewTitle: "Sur ce territoire",
    previewLead:
      "Capsule, table et ce que l'on fait dans le paysage. Composez le voyage pour voir l'itinéraire jour par jour.",
    previewStay: "Dormir",
    previewTable: "Table",
    previewActs: "Faire",
    more: "+{n}",
    loadingHint: "Capsule, table et activités selon votre budget.",
    budget: "Budget total · {price}",
    budgetMin: "250 mille",
    budgetMax: "3,5 millions",
    nights: "Nuits",
    guests: "Voyageurs",
    interests: "Intérêts",
    fromDay: "À partir de {price} par jour d'expérience à {city}.",
    submit: "Composer le voyage",
    ask: "Demander",
    askHint: "Ex. : Pucón ou Puerto Varas convient mieux avec 600 mille ?",
    askPlaceholder: "Écrivez votre question…",
    send: "Envoyer",
    you: "Vous",
    loadingPlan: "Composition de l'itinéraire avec votre budget…",
    loadPlanner: "Chargement du planificateur…",
    errorPlan: "Impossible de composer l'itinéraire.",
    errorNet: "Erreur réseau lors de la composition de l'itinéraire.",
    empty:
      "Choisissez un paysage et composez le voyage. L'itinéraire apparaît ici, avec capsule, table et activités.",
    chatFail: "je n'ai pas pu répondre pour le moment.",
  },
  itinerary: {
    kicker: "Itinéraire",
    budget: "Budget",
    estimated: "Total estimé",
    remaining: "Reste",
    nightsGuests: "Nuits · voyageurs",
    stay: "Capsule",
    table: "Table",
    acts: "Activités",
    day: "Jour {n}",
    included: "inclus",
    bookStay: "Réserver la capsule",
    seeMap: "Voir sur la carte",
  },
  partners: {
    kicker: "Partenaires",
    title: "Devenir partenaire",
    lead: "Vous exploitez une capsule, une ruka, une caleta, un tour ou un vignoble. Mapucoin vous montre sur la carte, vous entre dans l'itinéraire et encaisse avec Stripe.",
    name: "Nom",
    email: "E-mail",
    phone: "Téléphone",
    role: "Type de partenaire",
    business: "Nom de l'activité",
    city: "Ville / territoire",
    notes: "Parlez-nous de votre offre",
    submit: "Postuler",
    sending: "Envoi…",
    incomplete: "Complétez nom, e-mail et activité.",
    error: "Envoi impossible. Réessayez.",
    ok: "Demande reçue. Nous vous contactons pour activer votre fiche et Stripe.",
    okNoDb:
      "Demande reçue. Connectez Supabase pour enregistrer les partenaires en production.",
  },
  partnerRoles: {
    capsula: "Capsule / hébergement",
    gastronomia: "Gastronomie",
    actividad: "Activité / tour",
    guia: "Guide",
    transporte: "Transport",
    vina: "Vignoble / distillerie",
  },
  awards: {
    kicker: "Prix",
    title: "Prix et reconnaissances internationales",
    lead: "Le Chili, Atacama, Santiago, Rapa Nui et Torres del Paine, distingués par World Travel Awards, TIME, Forbes, Tripadvisor et l'UNESCO.",
    prev: "Prix précédent",
    next: "Prix suivant",
    goTo: "Aller au prix {n}",
    of: "{n} sur {total} : {title}",
  },
  kinds: {
    place: "Destination",
    capsule: "Capsule",
    food: "Table",
    activity: "Activité",
  },
  landscapes: {
    desierto: "Déserts",
    playa: "Plages",
    vinedos: "Vignobles",
    volcan: "Volcans",
    rios: "Rivières",
    lago: "Lacs",
    "bosque-nativo": "Forêts",
    nieve: "Neige",
  },
  activitySports: {
    desierto: "Astronomie et sandboard",
    playa: "Plongée et surf",
    vinedos: "Dégustation de vins",
    volcan: "Trekking, cyclisme et thermes",
    rios: "Kayak et rafting",
    lago: "Bateaux et sports nautiques",
    "bosque-nativo": "Tours et trekking",
    nieve: "Ski et snowboard",
  },
  interests: {
    naturaleza: "Nature",
    gastronomia: "Gastronomie",
    cultura: "Culture",
    aventura: "Aventure",
    descanso: "Repos",
    estrellas: "Astronomie",
  },
  from: "à partir de",
  sound: "Son",
  mute: "Muet",
  footer: { terms: "Terms", privacy: "Privacy" },
  notFound: {
    title: "Territoire introuvable",
    lead: "Cet itinéraire n'est pas sur la carte Mapucoin.",
    back: "Retour à l'accueil",
  },
  destino: {
    videoKicker: "Vidéo du territoire",
    videoTitle: "{name} en mouvement",
    videoAlt: "Vidéo de {name}",
    gallery: "Galerie",
    onMap: "Sur la carte",
    from: "Expériences à partir de",
    planThis: "Planifier cette destination",
    seeCapsule: "Voir la capsule {name}",
    related: "Dormir, manger et faire",
  },
  reserva: {
    kicker: "Réservation",
    title: "Confirmer la réservation",
    canceled: "Paiement annulé. Vous pouvez réessayer.",
    summary: "{name} · {city}. {nights} · {guests}. Total {total}.",
    night: "nuit",
    nights: "nuits",
    guest: "voyageur",
    guests: "voyageurs",
    capsule: "Capsule",
    name: "Nom",
    email: "E-mail",
    phone: "Téléphone",
    pay: "Payer avec Stripe",
    creating: "Création de la session Stripe…",
    noStripe: "Stripe n'est pas configuré. Ajoutez STRIPE_SECRET_KEY dans Vercel.",
    fail: "Impossible de lancer le paiement. Vérifiez les données.",
    okKicker: "C'est fait",
    okTitle: "Réservation confirmée",
    okLead:
      "Stripe a enregistré le paiement. Nous écrivons avec le check-in de la capsule et le reste de l'itinéraire.",
    okCta: "Retour à la carte",
  },
  catalogEmpty: "Aucune fiche dans ce paysage.",
  awardTitles: {
    "Mejor Destino de Turismo Aventura del Mundo":
      "Meilleure destination d'aventure au monde",
    "Mejor Destino Romántico": "Meilleure destination romantique",
    "Mejor Destino de Sudamérica": "Meilleure destination d'Amérique du Sud",
    "Mejor Destino Verde": "Meilleure destination verte",
    "Mejor Destino de Naturaleza": "Meilleure destination nature",
    "Mejor Ciudad": "Meilleure ville",
    "Mejor Destino de Cruceros": "Meilleure destination de croisière",
    "Mejor Destino Internacional": "Meilleure destination internationale",
    "Solo Travel — 4° mundial": "Solo Travel — 4e mondial",
    "Top South American Destination": "Top South American Destination",
    "Reserva de la Biósfera": "Réserve de biosphère",
    "Mejor Viñedo del Mundo": "Meilleur vignoble du monde",
    "World's Greatest Places": "World's Greatest Places",
    "Patrimonio de la Humanidad": "Patrimoine mondial",
    "Mejor lugar del mundo para observación de estrellas":
      "Meilleur lieu au monde pour observer les étoiles",
    "El radiotelescopio más grande del mundo":
      "Le plus grand radiotélescope du monde",
  },
  awardNotes: {
    "7ª vez": "7e fois",
    "Octava Maravilla del Mundo": "Huitième merveille du monde",
    "Postulación a premio de gobernanza": "Candidature à un prix de gouvernance",
    "Estancia Mercedes (Magallanes), Pared Sur Camp (Aysén) y Ephedra Restaurant (Antofagasta)":
      "Estancia Mercedes (Magallanes), Pared Sur Camp (Aysén) et Ephedra Restaurant (Antofagasta)",
    Astroturismo: "Astrotourisme",
  },
  legalTermsTitle: "Conditions générales",
  legalPrivacyTitle: "Politique de confidentialité",
};

const it: typeof es = {
  skip: "Salta al contenuto",
  language: "Lingua",
  nav: {
    map: "Mappa",
    capsules: "Capsule",
    food: "Gastronomia",
    activities: "Attività",
    partners: "Partner",
    awards: "Premi",
    plan: "Pianifica",
    menu: "Menu",
  },
  hero: {
    title: "Il Cile, da nord a sud.",
    lead: "Capsule di rame e vetro in deserti, spiagge, vigneti, vulcani, fiumi, laghi, boschi e neve. Tavola locale e budget in CLP.",
    mapCta: "Mappa interattiva",
    planCta: "Pianifica",
  },
  map: {
    kicker: "Mappa",
    title: "Il Cile classificato per paesaggio",
    lead: "Filtra deserti, spiagge, vigneti, vulcani, fiumi, laghi, boschi e neve. Ogni pin è un territorio con la sua capsula.",
    all: "Tutti",
    places: "Luoghi",
    capsules: "Capsule",
    both: "Entrambi",
    legend: "Terracotta: destinazioni · Oro: capsule",
    loading: "Caricamento della mappa del Cile…",
    viewSheet: "Vedi scheda →",
    destination: "Destinazione",
    capsule: "Capsula",
  },
  capsules: {
    kicker: "Capsule",
    title: "Otto paesaggi, una casa capsula",
    lead: "Rame, vetro e legno. Off-grid opzionale, isolamento da −40 °C a 40 °C. Una capsula per paesaggio, gestita da partner locali.",
    alt: "Casa capsula Mapucoin",
    fromNight: "da {price} / notte",
    perNight: "A notte",
    upTo: "Fino a {n} viaggiatori · {region}",
    book: "Prenota",
    explore: "Esplora {name} →",
    location: "Posizione",
    interiorAlt: "Interno in rame, legno e vetro",
  },
  food: {
    kicker: "Gastronomia",
    title: "La tavola del territorio",
    lead: "Curanto, empanadas de pino, pastel de choclo, caldillo de congrio, mote con huesillos e la tavola di ogni territorio. Con partner locali.",
    hours: "{price} · {hours} h",
  },
  activities: {
    kicker: "Attività",
    title: "Cosa si fa nel territorio",
    lead: "Classificate per paesaggio: astronomia e sandboard nel deserto, immersioni e surf in spiaggia, degustazione nei vigneti, trekking e terme sui vulcani, kayak e rafting sui fiumi, barche sui laghi, tour nel bosco, sci sulla neve.",
    other: "Altri",
    otherSports: "Cultura, albe e belvedere",
  },
  plan: {
    kicker: "Pianifica",
    title: "Il tuo viaggio, al tuo budget",
    lead: "Scegli il paesaggio e il budget in CLP. Mapucoin compone notti in capsula, tavola e attività di quel territorio.",
    formKicker: "Pianificatore",
    formTitle: "Quanto e dove?",
    formLead:
      "Scegli il paesaggio e il budget in pesos cileni. Mapucoin compone capsula, tavola e attività di quel territorio.",
    landscape: "Paesaggio",
    place: "Luogo da conoscere",
    previewTitle: "In questo territorio",
    previewLead:
      "Capsula, tavola e ciò che si fa nel paesaggio. Componi il viaggio per vedere l'itinerario giorno per giorno.",
    previewStay: "Dormire",
    previewTable: "Tavola",
    previewActs: "Fare",
    more: "+{n}",
    loadingHint: "Capsula, tavola e attività secondo il tuo budget.",
    budget: "Budget totale · {price}",
    budgetMin: "250 mila",
    budgetMax: "3,5 milioni",
    nights: "Notti",
    guests: "Viaggiatori",
    interests: "Interessi",
    fromDay: "Da {price} al giorno di esperienza a {city}.",
    submit: "Comporre il viaggio",
    ask: "Chiedi",
    askHint: "Es: conviene di più Pucón o Puerto Varas con 600 mila?",
    askPlaceholder: "Scrivi la tua domanda…",
    send: "Invia",
    you: "Tu",
    loadingPlan: "Composizione dell'itinerario con il tuo budget…",
    loadPlanner: "Caricamento del pianificatore…",
    errorPlan: "Impossibile comporre l'itinerario.",
    errorNet: "Errore di rete nella composizione dell'itinerario.",
    empty:
      "Scegli un paesaggio e componi il viaggio. L'itinerario appare qui, con capsula, tavola e attività.",
    chatFail: "non ho potuto rispondere ora.",
  },
  itinerary: {
    kicker: "Itinerario",
    budget: "Budget",
    estimated: "Totale stimato",
    remaining: "Resta",
    nightsGuests: "Notti · viaggiatori",
    stay: "Capsula",
    table: "Tavola",
    acts: "Attività",
    day: "Giorno {n}",
    included: "incluso",
    bookStay: "Prenota la capsula",
    seeMap: "Vedi sulla mappa",
  },
  partners: {
    kicker: "Partner",
    title: "Entra come partner",
    lead: "Gestisci una capsula, una ruka, una caleta, un tour o una vigna. Mapucoin ti mostra sulla mappa, ti mette nell'itinerario e incassa con Stripe.",
    name: "Nome",
    email: "Email",
    phone: "Telefono",
    role: "Tipo di partner",
    business: "Nome dell'attività",
    city: "Città / territorio",
    notes: "Raccontaci la tua offerta",
    submit: "Candidati",
    sending: "Invio…",
    incomplete: "Compila nome, email e attività.",
    error: "Invio non riuscito. Riprova.",
    ok: "Richiesta ricevuta. Ti contattiamo per attivare la scheda e Stripe.",
    okNoDb:
      "Richiesta ricevuta. Collega Supabase per salvare i partner in produzione.",
  },
  partnerRoles: {
    capsula: "Capsula / alloggio",
    gastronomia: "Gastronomia",
    actividad: "Attività / tour",
    guia: "Guida",
    transporte: "Trasporto",
    vina: "Vigna / distilleria",
  },
  awards: {
    kicker: "Premi",
    title: "Premi e riconoscimenti internazionali",
    lead: "Cile, Atacama, Santiago, Rapa Nui e Torres del Paine, distinti da World Travel Awards, TIME, Forbes, Tripadvisor e UNESCO.",
    prev: "Premio precedente",
    next: "Premio successivo",
    goTo: "Vai al premio {n}",
    of: "{n} di {total}: {title}",
  },
  kinds: {
    place: "Destinazione",
    capsule: "Capsula",
    food: "Tavola",
    activity: "Attività",
  },
  landscapes: {
    desierto: "Deserti",
    playa: "Spiagge",
    vinedos: "Vigneti",
    volcan: "Vulcani",
    rios: "Fiumi",
    lago: "Laghi",
    "bosque-nativo": "Boschi",
    nieve: "Neve",
  },
  activitySports: {
    desierto: "Astronomia e sandboard",
    playa: "Immersioni e surf",
    vinedos: "Degustazione di vini",
    volcan: "Trekking, ciclismo e terme",
    rios: "Kayak e rafting",
    lago: "Barche e sport nautici",
    "bosque-nativo": "Tour e trekking",
    nieve: "Sci e snowboard",
  },
  interests: {
    naturaleza: "Natura",
    gastronomia: "Gastronomia",
    cultura: "Cultura",
    aventura: "Avventura",
    descanso: "Riposo",
    estrellas: "Astronomia",
  },
  from: "da",
  sound: "Suono",
  mute: "Muto",
  footer: { terms: "Terms", privacy: "Privacy" },
  notFound: {
    title: "Territorio non trovato",
    lead: "Quel percorso non è sulla mappa Mapucoin.",
    back: "Torna all'inizio",
  },
  destino: {
    videoKicker: "Video del territorio",
    videoTitle: "{name} in movimento",
    videoAlt: "Video di {name}",
    gallery: "Galleria",
    onMap: "Sulla mappa",
    from: "Esperienze da",
    planThis: "Pianifica questa destinazione",
    seeCapsule: "Vedi capsula {name}",
    related: "Dormire, mangiare e fare",
  },
  reserva: {
    kicker: "Prenotazione",
    title: "Conferma la prenotazione",
    canceled: "Pagamento annullato. Puoi riprovare.",
    summary: "{name} · {city}. {nights} · {guests}. Totale {total}.",
    night: "notte",
    nights: "notti",
    guest: "viaggiatore",
    guests: "viaggiatori",
    capsule: "Capsula",
    name: "Nome",
    email: "Email",
    phone: "Telefono",
    pay: "Paga con Stripe",
    creating: "Creazione della sessione Stripe…",
    noStripe: "Stripe non è configurato. Aggiungi STRIPE_SECRET_KEY in Vercel.",
    fail: "Impossibile avviare il pagamento. Controlla i dati.",
    okKicker: "Fatto",
    okTitle: "Prenotazione confermata",
    okLead:
      "Stripe ha registrato il pagamento. Scriviamo con il check-in della capsula e il resto dell'itinerario.",
    okCta: "Torna alla mappa",
  },
  catalogEmpty: "Nessuna scheda in questo paesaggio.",
  awardTitles: {
    "Mejor Destino de Turismo Aventura del Mundo":
      "Migliore destinazione di turismo d'avventura al mondo",
    "Mejor Destino Romántico": "Migliore destinazione romantica",
    "Mejor Destino de Sudamérica": "Migliore destinazione del Sudamerica",
    "Mejor Destino Verde": "Migliore destinazione verde",
    "Mejor Destino de Naturaleza": "Migliore destinazione natura",
    "Mejor Ciudad": "Migliore città",
    "Mejor Destino de Cruceros": "Migliore destinazione crocieristica",
    "Mejor Destino Internacional": "Migliore destinazione internazionale",
    "Solo Travel — 4° mundial": "Solo Travel — 4° mondiale",
    "Top South American Destination": "Top South American Destination",
    "Reserva de la Biósfera": "Riserva della biosfera",
    "Mejor Viñedo del Mundo": "Miglior vigneto del mondo",
    "World's Greatest Places": "World's Greatest Places",
    "Patrimonio de la Humanidad": "Patrimonio dell'umanità",
    "Mejor lugar del mundo para observación de estrellas":
      "Miglior luogo al mondo per osservare le stelle",
    "El radiotelescopio más grande del mundo":
      "Il radiotelescopio più grande del mondo",
  },
  awardNotes: {
    "7ª vez": "7ª volta",
    "Octava Maravilla del Mundo": "Ottava meraviglia del mondo",
    "Postulación a premio de gobernanza": "Candidatura a premio di governance",
    "Estancia Mercedes (Magallanes), Pared Sur Camp (Aysén) y Ephedra Restaurant (Antofagasta)":
      "Estancia Mercedes (Magallanes), Pared Sur Camp (Aysén) ed Ephedra Restaurant (Antofagasta)",
    Astroturismo: "Astroturismo",
  },
  legalTermsTitle: "Termini e condizioni",
  legalPrivacyTitle: "Informativa sulla privacy",
};

export const copy = { es, en, pt, fr, it } as const;

export function t(locale: Locale) {
  return copy[locale] ?? copy.es;
}

export function tr(
  template: string,
  vars: Record<string, string | number>,
) {
  return template.replace(/\{(\w+)\}/g, (_, k) => String(vars[k] ?? ""));
}
