import type { CatalogItem, Landscape, Region } from "./catalog";

const p = (file: string) => `/images/places/${file}`;

type ParkSeed = {
  slug: string;
  name: string;
  region: Region;
  city: string;
  lat: number;
  lng: number;
  image: string;
  tagline: string;
  description: string;
  highlights: string[];
  priceFromCLP: number;
  extraLandscapes?: Landscape[];
};

/**
 * The 48 SNASPE units with a digital pass on pasesparques.cl.
 * Four already exist as destinations (Paine, Siete Tazas, La Campana, Juan Fernández).
 */
const parkSeeds: ParkSeed[] = [
  {
    slug: "pn-vicente-perez-rosales",
    name: "Parque Nacional Vicente Pérez Rosales",
    region: "Araucanía y Lagos",
    city: "Petrohué",
    lat: -41.16,
    lng: -72.45,
    image: p("osorno.jpg"),
    tagline: "El parque más antiguo de Chile: Osorno, Todos los Santos y Petrohué.",
    description:
      "Volcán Osorno, lago Todos los Santos y los saltos del Petrohué. Pase digital en pasesparques.cl.",
    highlights: ["Petrohué", "Osorno", "Todos los Santos"],
    priceFromCLP: 12000,
    extraLandscapes: ["lago", "volcan"],
  },
  {
    slug: "pn-conguillio",
    name: "Parque Nacional Conguillío",
    region: "Araucanía y Lagos",
    city: "Melipeuco",
    lat: -38.65,
    lng: -71.63,
    image: p("villarrica.jpg"),
    tagline: "Araucarias, lava del Llaima y lagunas de agua verde.",
    description:
      "Bosque de araucaria milenaria, Sierra Nevada y el volcán Llaima. Senderos Sierra Nevada y Los Lagos. Pase digital en pasesparques.cl.",
    highlights: ["Araucarias", "Llaima", "Laguna Conguillío"],
    priceFromCLP: 12000,
    extraLandscapes: ["volcan", "bosque-nativo"],
  },
  {
    slug: "pn-laguna-del-laja",
    name: "Parque Nacional Laguna del Laja",
    region: "Valle Central",
    city: "Antuco",
    lat: -37.39,
    lng: -71.4,
    image: p("laja.jpg"),
    tagline: "Volcán Antuco, laguna de altura y el salto del Laja cerca.",
    description:
      "Laguna andina al pie del Antuco, nieve en invierno y senderos de lava. Pase digital en pasesparques.cl.",
    highlights: ["Antuco", "Laguna", "Senderos de lava"],
    priceFromCLP: 8000,
    extraLandscapes: ["volcan", "nieve"],
  },
  {
    slug: "rn-los-flamencos",
    name: "Reserva Nacional Los Flamencos",
    region: "Norte Grande",
    city: "San Pedro de Atacama",
    lat: -23.25,
    lng: -67.76,
    image: p("atacama-luna.jpg"),
    tagline: "Salares, flamencos y el altiplano de Atacama.",
    description:
      "Siete sectores: Chaxa, Miscanti, Cejar, Valle de la Luna y más. Pase digital en pasesparques.cl.",
    highlights: ["Chaxa", "Miscanti", "Valle de la Luna"],
    priceFromCLP: 15000,
    extraLandscapes: ["desierto"],
  },
  {
    slug: "pn-villarrica",
    name: "Parque Nacional Villarrica",
    region: "Araucanía y Lagos",
    city: "Pucón",
    lat: -39.42,
    lng: -71.94,
    image: p("villarrica.jpg"),
    tagline: "El cono activo, crampones y los lagos a los pies.",
    description:
      "Sector norte en La Araucanía: ascenso al Villarrica, bosques de araucaria y termas cercanas. Pase digital en pasesparques.cl.",
    highlights: ["Cráter", "Araucarias", "Pucón"],
    priceFromCLP: 12000,
    extraLandscapes: ["volcan", "nieve"],
  },
  {
    slug: "pn-alerce-andino",
    name: "Parque Nacional Alerce Andino",
    region: "Araucanía y Lagos",
    city: "Puerto Montt",
    lat: -41.58,
    lng: -72.58,
    image: p("olmue.jpg"),
    tagline: "Alerces de mil años entre fiordos y lagunas.",
    description:
      "Bosque templado lluvioso al este de Puerto Montt. Senderos a alerzales y lagunas andinas. Pase digital en pasesparques.cl.",
    highlights: ["Alerce", "Lagunas", "Bosque templado"],
    priceFromCLP: 8000,
    extraLandscapes: ["bosque-nativo"],
  },
  {
    slug: "pn-huerquehue",
    name: "Parque Nacional Huerquehue",
    region: "Araucanía y Lagos",
    city: "Pucón",
    lat: -39.13,
    lng: -71.73,
    image: p("pucon.jpg"),
    tagline: "Lagunas de altura y araucarias a un salto de Pucón.",
    description:
      "Sendero Los Lagos, araucarias y vistas al Villarrica. Uno de los trekkings clásicos de la Araucanía. Pase digital en pasesparques.cl.",
    highlights: ["Los Lagos", "Araucarias", "Tinquilco"],
    priceFromCLP: 10000,
    extraLandscapes: ["bosque-nativo", "lago"],
  },
  {
    slug: "pn-chiloe",
    name: "Parque Nacional Chiloé",
    region: "Araucanía y Lagos",
    city: "Cucao",
    lat: -42.62,
    lng: -74.12,
    image: p("palafitos.jpg"),
    tagline: "Dunas, bosque valdiviano y el Pacífico de Cucao.",
    description:
      "Costa occidental de la Isla Grande: Chepu y Abtao, playa de Cucao y alerzales. Pase digital en pasesparques.cl.",
    highlights: ["Cucao", "Chepu", "Bosque costero"],
    priceFromCLP: 8000,
    extraLandscapes: ["bosque-nativo", "playa"],
  },
  {
    slug: "mn-cerro-nielol",
    name: "Monumento Natural Cerro Ñielol",
    region: "Araucanía y Lagos",
    city: "Temuco",
    lat: -38.72,
    lng: -72.58,
    image: p("olmue.jpg"),
    tagline: "Bosque nativo urbano sobre Temuco.",
    description:
      "Cerro de boldo, peumo y copihue en la ciudad. Senderos cortos y mirador. Pase digital en pasesparques.cl.",
    highlights: ["Mirador", "Copihue", "Temuco"],
    priceFromCLP: 4000,
    extraLandscapes: ["bosque-nativo"],
  },
  {
    slug: "pn-nonguen",
    name: "Parque Nacional Nonguén",
    region: "Valle Central",
    city: "Concepción",
    lat: -36.88,
    lng: -72.96,
    image: p("concepcion.jpg"),
    tagline: "El último bosque nativo costero del Gran Concepción.",
    description:
      "Hualqui, Chiguayante y Concepción. Senderos de bosque caducifolio y esteros. Pase digital en pasesparques.cl.",
    highlights: ["Bosque caducifolio", "Senderos", "Gran Concepción"],
    priceFromCLP: 6000,
    extraLandscapes: ["bosque-nativo"],
  },
  {
    slug: "mn-lahuen-nadi",
    name: "Monumento Natural Lahuen Ñadi",
    region: "Araucanía y Lagos",
    city: "Puerto Montt",
    lat: -41.45,
    lng: -73.02,
    image: p("olmue.jpg"),
    tagline: "Un alerzal relicto a minutos de Puerto Montt.",
    description:
      "Pasarelas entre alerces milenarios en el Ñadi. Visita corta, de alto valor botánico. Pase digital en pasesparques.cl.",
    highlights: ["Alerce", "Pasarelas", "Ñadi"],
    priceFromCLP: 5000,
    extraLandscapes: ["bosque-nativo"],
  },
  {
    slug: "pn-tolhuaca",
    name: "Parque Nacional Tolhuaca",
    region: "Araucanía y Lagos",
    city: "Curacautín",
    lat: -38.22,
    lng: -71.73,
    image: p("villarrica.jpg"),
    tagline: "Araucarias, laguna Malleco y termas de montaña.",
    description:
      "Cordillera de Malleco, bosque andino-patagónico y la laguna Malleco. Pase digital en pasesparques.cl.",
    highlights: ["Laguna Malleco", "Araucarias", "Termas"],
    priceFromCLP: 8000,
    extraLandscapes: ["bosque-nativo", "volcan"],
  },
  {
    slug: "mn-cueva-del-milodon",
    name: "Monumento Natural Cueva del Milodón",
    region: "Patagonia",
    city: "Puerto Natales",
    lat: -51.57,
    lng: -72.62,
    image: p("paine.jpg"),
    tagline: "La caverna donde se halló el milodón, a un paso de Natales.",
    description:
      "Cueva de 30 m de alto, relato paleontológico y vista al seno Última Esperanza. Pase digital en pasesparques.cl.",
    highlights: ["Cueva", "Milodón", "Natales"],
    priceFromCLP: 8000,
  },
  {
    slug: "pn-queulat",
    name: "Parque Nacional Queulat",
    region: "Patagonia",
    city: "Puyuhuapi",
    lat: -44.4,
    lng: -72.4,
    image: p("coyhaique.jpg"),
    tagline: "El ventisquero colgante sobre la Carretera Austral.",
    description:
      "Bosque siempreverde, fiordo y el glaciar colgante de Queulat. Pase digital en pasesparques.cl.",
    highlights: ["Ventisquero colgante", "Bosque", "Puyuhuapi"],
    priceFromCLP: 10000,
    extraLandscapes: ["bosque-nativo", "rios"],
  },
  {
    slug: "pn-rio-clarillo",
    name: "Parque Nacional Río Clarillo",
    region: "Centro",
    city: "Pirque",
    lat: -33.72,
    lng: -70.43,
    image: p("cajon.jpg"),
    tagline: "Espino, litre y el río a una hora de Santiago.",
    description:
      "Bosque esclerófilo del Cajón del Maipo. Senderos de río y picnic. Pase digital en pasesparques.cl.",
    highlights: ["Río Clarillo", "Bosque esclerófilo", "Pirque"],
    priceFromCLP: 8000,
    extraLandscapes: ["rios", "bosque-nativo"],
  },
  {
    slug: "pn-bosque-fray-jorge",
    name: "Parque Nacional Bosque Fray Jorge",
    region: "Norte Chico",
    city: "Ovalle",
    lat: -30.67,
    lng: -71.68,
    image: p("elqui.jpg"),
    tagline: "Bosque valdiviano en pleno desierto, gracias a la camanchaca.",
    description:
      "Reserva de la biósfera: olivillo y canelo sobre terrazas costeras del Norte Chico. Pase digital en pasesparques.cl.",
    highlights: ["Camanchaca", "Olivillo", "Biósfera"],
    priceFromCLP: 8000,
    extraLandscapes: ["desierto", "bosque-nativo"],
  },
  {
    slug: "pn-bernardo-ohiggins",
    name: "Parque Nacional Bernardo O'Higgins",
    region: "Patagonia",
    city: "Puerto Natales",
    lat: -48.5,
    lng: -74.0,
    image: p("paine.jpg"),
    tagline: "El parque más extenso de Chile: hielo, fiordos y el glaciar Pío XI.",
    description:
      "Campo de Hielo Sur, fiordos y navegación al glaciar. Pase digital en pasesparques.cl.",
    highlights: ["Pío XI", "Fiordos", "Hielo Sur"],
    priceFromCLP: 35000,
    extraLandscapes: ["nieve", "lago"],
  },
  {
    slug: "rn-magallanes",
    name: "Reserva Nacional Magallanes",
    region: "Patagonia",
    city: "Punta Arenas",
    lat: -53.15,
    lng: -71.05,
    image: p("paine.jpg"),
    tagline: "Lenga y coigüe sobre Punta Arenas, con vista al estrecho.",
    description:
      "Senderos de bosque magallánico a minutos de la ciudad. Pase digital en pasesparques.cl.",
    highlights: ["Lenga", "Mirador", "Punta Arenas"],
    priceFromCLP: 6000,
    extraLandscapes: ["bosque-nativo"],
  },
  {
    slug: "rn-altos-de-lircay",
    name: "Reserva Nacional Altos de Lircay",
    region: "Valle Central",
    city: "San Clemente",
    lat: -35.6,
    lng: -71.03,
    image: p("siete-tazas.jpg"),
    tagline: "Roble, lenga y el Enladrillado volcánico del Maule.",
    description:
      "Cordillera del Maule, sendero al Enladrillado y bosques de Nothofagus. Pase digital en pasesparques.cl.",
    highlights: ["Enladrillado", "Roble", "Maule andino"],
    priceFromCLP: 8000,
    extraLandscapes: ["bosque-nativo", "volcan"],
  },
  {
    slug: "rn-rio-de-los-cipreses",
    name: "Reserva Nacional Río de los Cipreses",
    region: "Centro",
    city: "Machalí",
    lat: -34.27,
    lng: -70.45,
    image: p("cajon.jpg"),
    tagline: "Ciprés de la cordillera y guanacos en el valle del Cachapoal.",
    description:
      "Valle andino de O'Higgins, senderos de río y fauna. Pase digital en pasesparques.cl.",
    highlights: ["Ciprés", "Guanacos", "Cachapoal"],
    priceFromCLP: 7000,
    extraLandscapes: ["rios", "bosque-nativo"],
  },
  {
    slug: "rn-rio-simpson",
    name: "Reserva Nacional Río Simpson",
    region: "Patagonia",
    city: "Coyhaique",
    lat: -45.45,
    lng: -72.33,
    image: p("coyhaique.jpg"),
    tagline: "El cañón del Simpson entre Coyhaique y Puerto Aysén.",
    description:
      "Bosque y río turquesa junto a la Carretera Austral. Pase digital en pasesparques.cl.",
    highlights: ["Río Simpson", "Cañón", "Aysén"],
    priceFromCLP: 6000,
    extraLandscapes: ["rios", "bosque-nativo"],
  },
  {
    slug: "rn-coyhaique",
    name: "Reserva Nacional Coyhaique",
    region: "Patagonia",
    city: "Coyhaique",
    lat: -45.54,
    lng: -72.0,
    image: p("coyhaique.jpg"),
    tagline: "Lenga sobre la ciudad, con vista a la pampa y la cordillera.",
    description:
      "Senderos cortos desde Coyhaique, bosque de lenga y miradores. Pase digital en pasesparques.cl.",
    highlights: ["Lenga", "Miradores", "Coyhaique"],
    priceFromCLP: 5000,
    extraLandscapes: ["bosque-nativo"],
  },
  {
    slug: "pn-villarrica-sur",
    name: "Parque Nacional Villarrica (Los Ríos)",
    region: "Araucanía y Lagos",
    city: "Panguipulli",
    lat: -39.58,
    lng: -72.05,
    image: p("villarrica.jpg"),
    tagline: "La ladera sur del Villarrica, desde Panguipulli.",
    description:
      "Sector Los Ríos del mismo volcán: bosques, lagunas y acceso por Panguipulli. Pase digital en pasesparques.cl.",
    highlights: ["Panguipulli", "Bosque", "Volcán"],
    priceFromCLP: 10000,
    extraLandscapes: ["volcan", "bosque-nativo"],
  },
  {
    slug: "rn-federico-albert",
    name: "Reserva Nacional Federico Albert",
    region: "Valle Central",
    city: "Chanco",
    lat: -35.73,
    lng: -72.55,
    image: p("concepcion.jpg"),
    tagline: "El bosque plantado que detuvo las dunas de Chanco.",
    description:
      "Pino, eucalipto y dunas costeras del Maule. Pase digital en pasesparques.cl.",
    highlights: ["Dunas", "Chanco", "Bosque costero"],
    priceFromCLP: 4000,
    extraLandscapes: ["playa", "bosque-nativo"],
  },
  {
    slug: "pn-laguna-san-rafael",
    name: "Parque Nacional Laguna San Rafael",
    region: "Patagonia",
    city: "Puerto Chacabuco",
    lat: -46.67,
    lng: -73.83,
    image: p("marmol.jpg"),
    tagline: "El glaciar San Rafael calving en la laguna.",
    description:
      "Campo de Hielo Norte, navegación a la laguna y hielo milenario. Reserva de la biósfera. Pase digital en pasesparques.cl.",
    highlights: ["Glaciar San Rafael", "Navegación", "Hielo Norte"],
    priceFromCLP: 45000,
    extraLandscapes: ["lago", "nieve"],
  },
  {
    slug: "pn-llanos-de-challe",
    name: "Parque Nacional Llanos de Challe",
    region: "Norte Chico",
    city: "Huasco",
    lat: -28.13,
    lng: -71.18,
    image: p("bahia-inglesa.jpg"),
    tagline: "Desierto florido, guanacos y el Pacífico de Huasco.",
    description:
      "Llanos costeros, cactáceas y el fenómeno del desierto florido. Pase digital en pasesparques.cl.",
    highlights: ["Desierto florido", "Guanacos", "Costa de Huasco"],
    priceFromCLP: 7000,
    extraLandscapes: ["desierto", "playa"],
  },
  {
    slug: "mn-el-morado",
    name: "Monumento Natural El Morado",
    region: "Centro",
    city: "San José de Maipo",
    lat: -33.74,
    lng: -70.06,
    image: p("cajon.jpg"),
    tagline: "Glaciar San Francisco y el morado sobre el Cajón.",
    description:
      "Trekking a la laguna y el glaciar, a dos horas de Santiago. Pase digital en pasesparques.cl.",
    highlights: ["Glaciar", "Laguna", "Cajón del Maipo"],
    priceFromCLP: 8000,
    extraLandscapes: ["nieve", "rios"],
  },
  {
    slug: "rn-nuble",
    name: "Reserva Nacional Ñuble",
    region: "Valle Central",
    city: "Pinto",
    lat: -36.85,
    lng: -71.45,
    image: p("chillan.jpg"),
    tagline: "Huemul, lenga y la cordillera de Chillán.",
    description:
      "Bosque andino y hábitat de huemul junto a las Termas de Chillán. Pase digital en pasesparques.cl.",
    highlights: ["Huemul", "Lenga", "Chillán"],
    priceFromCLP: 6000,
    extraLandscapes: ["bosque-nativo", "nieve"],
  },
  {
    slug: "rn-laguna-parrillar",
    name: "Reserva Nacional Laguna Parrillar",
    region: "Patagonia",
    city: "Punta Arenas",
    lat: -53.4,
    lng: -71.25,
    image: p("paine.jpg"),
    tagline: "Turberas, coigüe de Magallanes y una laguna escondida.",
    description:
      "Bosque magallánico al sur de Punta Arenas. Pesca y senderos de turbera. Pase digital en pasesparques.cl.",
    highlights: ["Laguna", "Turberas", "Coigüe"],
    priceFromCLP: 5000,
    extraLandscapes: ["lago", "bosque-nativo"],
  },
  {
    slug: "rn-pampa-del-tamarugal",
    name: "Reserva Nacional Pampa del Tamarugal",
    region: "Norte Grande",
    city: "Pozo Almonte",
    lat: -20.47,
    lng: -69.7,
    image: p("humberstone.jpg"),
    tagline: "Tamarugos, geoglifos y la pampa salitrera.",
    description:
      "Bosque de tamarugo en el desierto, geoglifos de Pintados y oficina salitrera cerca. Pase digital en pasesparques.cl.",
    highlights: ["Tamarugo", "Pintados", "Pampa"],
    priceFromCLP: 5000,
    extraLandscapes: ["desierto"],
  },
  {
    slug: "mn-pichasca",
    name: "Monumento Natural Pichasca",
    region: "Norte Chico",
    city: "Río Hurtado",
    lat: -30.39,
    lng: -70.87,
    image: p("elqui.jpg"),
    tagline: "Fósiles, petrificados y el valle del Hurtado.",
    description:
      "Bosque petrificado y restos de dinosaurios en el Limarí. Pase digital en pasesparques.cl.",
    highlights: ["Fósiles", "Bosque petrificado", "Hurtado"],
    priceFromCLP: 5000,
    extraLandscapes: ["vinedos"],
  },
  {
    slug: "rn-los-ruiles",
    name: "Reserva Nacional Los Ruiles",
    region: "Valle Central",
    city: "Empedrado",
    lat: -35.55,
    lng: -72.35,
    image: p("olmue.jpg"),
    tagline: "El ruil, árbol endémico del Maule, en un bosque chico y raro.",
    description:
      "Conservación del Nothofagus alessandrii. Visita breve de alto valor botánico. Pase digital en pasesparques.cl.",
    highlights: ["Ruil", "Endemismo", "Maule"],
    priceFromCLP: 4000,
    extraLandscapes: ["bosque-nativo"],
  },
  {
    slug: "rn-mocho-choshuenco",
    name: "Reserva Nacional Mocho-Choshuenco",
    region: "Araucanía y Lagos",
    city: "Panguipulli",
    lat: -39.93,
    lng: -72.03,
    image: p("villarrica.jpg"),
    tagline: "Dos volcanes gemelos y bosque sobre el Ranco.",
    description:
      "Mocho y Choshuenco, nieve, araucarias y acceso desde Panguipulli. Pase digital en pasesparques.cl.",
    highlights: ["Choshuenco", "Nieve", "Bosque"],
    priceFromCLP: 8000,
    extraLandscapes: ["volcan", "nieve"],
  },
  {
    slug: "rn-laguna-torca",
    name: "Reserva Nacional Laguna Torca",
    region: "Valle Central",
    city: "Vichuquén",
    lat: -34.77,
    lng: -72.07,
    image: p("colchagua.jpg"),
    tagline: "Cisnes de cuello negro entre Vichuquén y el mar.",
    description:
      "Humedal costero del Maule, aves y bosque de eucalipto. Pase digital en pasesparques.cl.",
    highlights: ["Cisnes", "Humedal", "Vichuquén"],
    priceFromCLP: 4000,
    extraLandscapes: ["lago", "playa"],
  },
  {
    slug: "pn-pali-aike",
    name: "Parque Nacional Pali Aike",
    region: "Patagonia",
    city: "Punta Arenas",
    lat: -52.1,
    lng: -69.73,
    image: p("paine.jpg"),
    tagline: "Campos de lava, cráteres y el viento de la pampa magallánica.",
    description:
      "Volcanismo cuaternario, cuevas arqueológicas y estepa. Pase digital en pasesparques.cl.",
    highlights: ["Cráteres", "Lava", "Pampa"],
    priceFromCLP: 8000,
    extraLandscapes: ["volcan"],
  },
  {
    slug: "mn-dos-lagunas",
    name: "Monumento Natural Dos Lagunas",
    region: "Patagonia",
    city: "Coyhaique",
    lat: -45.75,
    lng: -71.85,
    image: p("coyhaique.jpg"),
    tagline: "Dos espejos de agua y bosque de ñire cerca de Coyhaique.",
    description:
      "Lagunas El Toro y Escondida, picnic y aves. Pase digital en pasesparques.cl.",
    highlights: ["Lagunas", "Ñire", "Aves"],
    priceFromCLP: 4000,
    extraLandscapes: ["lago"],
  },
  {
    slug: "pn-pan-de-azucar",
    name: "Parque Nacional Pan de Azúcar",
    region: "Norte Grande",
    city: "Chañaral",
    lat: -26.15,
    lng: -70.65,
    image: p("bahia-inglesa.jpg"),
    tagline: "Desierto, pingüinos de Humboldt y caleta Pan de Azúcar.",
    description:
      "Costa de Atacama, cactus copiapoa, isla de pingüinos y campamento frente al Pacífico. Pase digital en pasesparques.cl.",
    highlights: ["Pingüinos", "Copiapoa", "Caleta"],
    priceFromCLP: 8000,
    extraLandscapes: ["desierto", "playa"],
  },
  {
    slug: "rn-las-chinchillas",
    name: "Reserva Nacional Las Chinchillas",
    region: "Norte Chico",
    city: "Illapel",
    lat: -31.5,
    lng: -71.1,
    image: p("elqui.jpg"),
    tagline: "La chinchilla de cola larga en el secano de Illapel.",
    description:
      "Matorral estepario, sendero interpretativo y cría de chinchilla. Pase digital en pasesparques.cl.",
    highlights: ["Chinchilla", "Secano", "Illapel"],
    priceFromCLP: 5000,
    extraLandscapes: ["desierto"],
  },
  {
    slug: "rn-huemules-de-niblinto",
    name: "Reserva Nacional Huemules de Niblinto",
    region: "Valle Central",
    city: "Coihueco",
    lat: -36.73,
    lng: -71.48,
    image: p("chillan.jpg"),
    tagline: "Santuario del huemul en la cordillera de Ñuble.",
    description:
      "Bosque andino y protección del huemul, junto a Ñuble y Chillán. Pase digital en pasesparques.cl.",
    highlights: ["Huemul", "Ñuble", "Bosque andino"],
    priceFromCLP: 5000,
    extraLandscapes: ["bosque-nativo"],
  },
  {
    slug: "pn-nevado-tres-cruces",
    name: "Parque Nacional Nevado Tres Cruces",
    region: "Norte Chico",
    city: "Copiapó",
    lat: -27.1,
    lng: -69.0,
    image: p("parinacota.jpg"),
    tagline: "Salar de Maricunga, flamencos y el Ojos del Salado al fondo.",
    description:
      "Altiplano de Atacama, lagunas Verde y Santa Rosa, volcanes de más de 6.000 m. Pase digital en pasesparques.cl.",
    highlights: ["Maricunga", "Laguna Verde", "Ojos del Salado"],
    priceFromCLP: 10000,
    extraLandscapes: ["desierto", "volcan"],
  },
  {
    slug: "rn-el-yali",
    name: "Reserva Nacional El Yali",
    region: "Centro",
    city: "Santo Domingo",
    lat: -33.75,
    lng: -71.7,
    image: p("isla-negra.jpg"),
    tagline: "El humedal Ramsar más importante de Chile central.",
    description:
      "Lagunas costeras, aves migratorias y dunas entre Santo Domingo y El Yali. Pase digital en pasesparques.cl.",
    highlights: ["Ramsar", "Aves", "Dunas"],
    priceFromCLP: 5000,
    extraLandscapes: ["playa"],
  },
  {
    slug: "rn-lago-penuelas",
    name: "Reserva Nacional Lago Peñuelas",
    region: "Centro",
    city: "Valparaíso",
    lat: -33.17,
    lng: -71.48,
    image: p("valparaiso.jpg"),
    tagline: "Embalse, bosque y la biósfera La Campana-Peñuelas.",
    description:
      "Entre Valparaíso y Santiago: laguna, aves y bosque esclerófilo. Pase digital en pasesparques.cl.",
    highlights: ["Embalse", "Biósfera", "Aves"],
    priceFromCLP: 5000,
    extraLandscapes: ["lago", "bosque-nativo"],
  },
  {
    slug: "pn-patagonia",
    name: "Parque Nacional Patagonia",
    region: "Patagonia",
    city: "Cochrane",
    lat: -47.17,
    lng: -72.5,
    image: p("coyhaique.jpg"),
    tagline: "Estepa, jeinimeni y el valle Chacabuco, de Cochrane a Chile Chico.",
    description:
      "Tres unidades: Jeinimeni, Tamango y valle Chacabuco. Guanacos, huemules y la Carretera Austral. Pase digital en pasesparques.cl.",
    highlights: ["Chacabuco", "Guanacos", "Cochrane"],
    priceFromCLP: 12000,
    extraLandscapes: ["lago", "bosque-nativo"],
  },
  {
    slug: "pn-alerce-costero",
    name: "Parque Nacional Alerce Costero",
    region: "Araucanía y Lagos",
    city: "La Unión",
    lat: -40.17,
    lng: -73.43,
    image: p("palafitos.jpg"),
    tagline: "Alerces de la cordillera de la Costa, entre Valdivia y La Unión.",
    description:
      "Alerzales costeros, alerce milenario y bosque valdiviano. Pase digital en pasesparques.cl.",
    highlights: ["Alerce milenario", "Cordillera de la Costa", "Valdivia"],
    priceFromCLP: 8000,
    extraLandscapes: ["bosque-nativo"],
  },
];

export const PARKS_PASS_URL = "https://www.pasesparques.cl/en";

export const nationalParks: CatalogItem[] = parkSeeds.map((s) => ({
  slug: s.slug,
  kind: "place" as const,
  name: s.name,
  region: s.region,
  city: s.city,
  lat: s.lat,
  lng: s.lng,
  image: s.image,
  gallery: [s.image],
  tagline: s.tagline,
  description: s.description,
  highlights: s.highlights,
  priceFromCLP: s.priceFromCLP,
  tags: ["parque", "conaf", "pasesparques", "naturaleza"],
  landscapes: ["parques", ...(s.extraLandscapes || [])] as Landscape[],
}));
